To make it easy to understand.
vuejs/jp.vuejs.org pull request #1007
Opened 2018-05-19 06:27 UTC by waterada

2018-05-20 05:37 UTC, kazupon requested changes
PRありがとうございます！ 🙏 
改善大変助かります!

レビュー 👀 コメント 💬 したので、対応お願いします！

2018-05-20 05:37 UTC, kazupon commented on src/v2/guide/class-and-style.md
> +オブジェクトによるバインドはインラインでなくてもかまいません:
`bind`を`束縛`に訳している理由なんですが、翻訳ポリシーとして日本語に訳しても違和感がないものは、原則するようにしています。
ソフトウェア用語としては、`バインド`は一般的に使われているため、そのように訳していもいいのですが、英語が不慣れの初心者の方を考えて、ここではわざと日本語にしています。

2018-05-20 05:37 UTC, kazupon commented on src/v2/guide/class-and-style.md
> +カスタムコンポーネント上で `class` 属性を使用するとき、これらのクラスはコンポーネントの root 要素 に追加されます。この要素上にすでに存在するクラスは、上書きされません。
`すでに`を追加することで確かに分かりやすくなるのですが、ここでは追加しなくても意味は通じると思うので、特になくて大丈夫です。

2018-05-20 05:37 UTC, kazupon commented on src/v2/guide/class-and-style.md
> +`v-bind:style`向けのオブジェクト構文は非常に簡単です。それは、JavaScript オブジェクトを除いては、ほとんど CSS のように見えます。CSS プロパティ名に対して、キャメルケース (camelCase) またはケバブケース (クォートとともに使うことになります) のどちらでも使用することができます:
翻訳ポリシーとしては、原文の用語は含めるようにしていますので、`kebab-case` は入れてもらえますか？

2018-05-21 00:53 UTC, waterada commented on src/v2/guide/class-and-style.md
> +オブジェクトによるバインドはインラインでなくてもかまいません:
了解しました。「束縛」で統一することにします。
ただ、ドキュメントを読んでいて、束縛の意味が「v-bind」することだと気づくのに一瞬かかりました。それこそ、bind = 束縛 という訳を知らない人には解りづらいように思えました。束縛の日本語的な意味は「動き・働きの自由に制限を加えること」ですが、ここで使っている bind の適切な意味は「結びつけること」の方かと思います。
とはいえ、統一することは最重要ですので、「束縛」で統一致します。

2018-05-21 00:54 UTC, waterada commented on src/v2/guide/class-and-style.md
> +カスタムコンポーネント上で `class` 属性を使用するとき、これらのクラスはコンポーネントの root 要素 に追加されます。この要素上にすでに存在するクラスは、上書きされません。
確かにそうですね。

2018-05-21 01:05 UTC, waterada commented on src/v2/guide/class-and-style.md
> +`v-bind:style`向けのオブジェクト構文は非常に簡単です。それは、JavaScript オブジェクトを除いては、ほとんど CSS のように見えます。CSS プロパティ名に対して、キャメルケース (camelCase) またはケバブケース (クォートとともに使うことになります) のどちらでも使用することができます:
修正します

2018-05-21 01:40 UTC, kazupon approved these changes

2018-05-21 01:40 UTC, merged

2018-05-21 01:40 UTC, kazupon commented
@waterada ありがとうございました！ 👍