To make it easy to understand
vuejs/jp.vuejs.org pull request #1009
Opened 2018-05-19 13:44 UTC by waterada

2018-05-21 15:55 UTC, kazupon requested changes
レビュー 👀コメント 💬 しました。
確認お願いします。

2018-05-21 15:55 UTC, kazupon commented on src/v2/guide/forms.md
> +しかし、時には、Vue インスタンスの動的なプロパティに値をバインドしたくなるかもしれません。それを達成するために `v-bind` を使用することができます。 加えて、`v-bind` を使用することで input 値に文字列以外の値をバインドすることができるようになります。
この`バインド`の訳は`束縛`にしておいてください。以降も対応した場合は`バインド`にしておいてください。

2018-07-27 12:00 UTC, potato4d commented
@waterada 
こちらですが、残りの対応をお願いできますでしょうか？
もし難しそうであればこちらで引き取ることができますので、ご連絡ください 💁‍♀️

2018-07-29 04:31 UTC, waterada commented
@potato4d
しばらくは時間取れそうにないので、引き取って頂いてもよいですか？
よろしくお願いします。

2018-07-30 05:51 UTC, potato4d commented
@waterada 
了解です！引き継ぎました！

@kazupon 
バインド→束縛の修正したので入れてしまいますねー（コミットログミスってちょっと逆になってしまいましたが Squash Merge のメッセージで修正しておきます 🙇 ）

2018-07-30 05:51 UTC, potato4d approved these changes

2018-07-30 05:52 UTC, merged