Translate handling edge cases
vuejs/jp.vuejs.org pull request #1011
Opened 2018-05-21 00:16 UTC by pipopotamasu

2018-05-22 10:58 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +事実、いわば"広範囲の props "のようなものと、依存性の注入について考えることができます。# TODO : expect はどう訳せばいいのだろう？
TODOの箇所が上手く翻訳できなかったので、どのように訳せばいいかご教授ください。

2018-05-22 10:58 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +- セットアップコードが削除コードから分離している状態は、セットアップしたものをプログラムでクリーンアップすることをより難しくします。 # TODO: 上手く翻訳できない
TODOの箇所が上手く翻訳できなかったので、どのように訳せばいいかご教授ください。

2018-05-22 10:58 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +この戦略を使用することで、私達はいくつかのインプット要素を持つ Pikaday さえ使うことができます。そしてそれぞれの新しいインスタンスは自動的にクリーンアップされます: # TODO : after itself が訳せない
TODOの箇所が上手く翻訳できなかったので、どのように訳せばいいかご教授ください。

2018-05-22 10:59 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +よく見てみると、これらのコンポーネントは逆説的ではありますが、それぞれ他のレンダリングツリーの子孫_と_祖先ということがわかります。 `Vue.component` でグローバルにコンポーネントを登録するとき、この逆説は自動的に解決されます。もしそれがあなたなら、ここで読むことをやめることもできます。 # TODO : if that's you が訳せない
TODOの箇所が上手く翻訳できなかったので、どのように訳せばいいかご教授ください。

2018-05-22 10:59 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +あなたは[配列](https://vuejs.org/v2/guide/list.html#Caveats)や[オブジェクト](https://vuejs.org/v2/guide/list.html#Object-Change-Detection-Caveats)、もしくは `data` と共に用いられる、Vue のリアクティブシステムに追跡されていない状態に依存しているかもしれないと言う変更
TODOの箇所が上手く翻訳できなかったので、どのように訳せばいいかご教授ください。

2018-05-24 12:00 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
内容確認お願いします！ 🙏

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
> +props とイベントが存在するにも関わらず、ときどき JavaScript で直接子コンポーネントにアクセスする必要があるかもしれません。このために `ref` 属性を使い、子コンポーネントにリファレンス ID を割り当てることができます。例えば:
`props`は`プロパティ`にしましょう。

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
> +事実、いわば"広範囲の props "のようなものと、依存性の注入について考えることができます。# TODO : expect はどう訳せばいいのだろう？
`実際、以下を除けば、いわば"広範囲のプロパティ"のようなものとした依存性の注入と考えることができます:`

という訳がいいんではないかと思います。

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
> +## プログラマティックなイベントリスナー
`Programmatic`もカタカナ訳ではなく、`プログラム的`などのように訳しましょう。

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
>  // Attach the datepicker to an input once
コードのコメントも訳しましょう！

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
> +- セットアップコードが削除コードから分離している状態は、セットアップしたものをプログラムでクリーンアップすることをより難しくします。 # TODO: 上手く翻訳できない
`セットアップコードが、クリーンアップコードとは別に保たれており、それは、セットアップしたものをプログラムでクリーンアップすることをより困難にしています。`

でどうでしょうか？

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
> +プログラマティックリスナー使用することで両方の問題を解決することができます:
ここの`programmatic`の訳もお願いします。

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
> +この戦略を使用することで、私達はいくつかのインプット要素を持つ Pikaday さえ使うことができます。そしてそれぞれの新しいインスタンスは自動的にクリーンアップされます: # TODO : after itself が訳せない
`この戦略を使用することによって、いくつかのインプット要素で Pikaday を使用することができ、そのライフサイクル自身のコードで、各新しいインスタンスは自動的にクリーンアップできます。`

という感じでしょうか。`after iteself` は前の説明内容、コードの内容から、ライフサイクル自身のコードを指していますね。

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
> +全てのコードが乗っている[この fiddle](https://jsfiddle.net/chrisvfritz/1Leb7up8/)を見てください。しかしながら注意して欲しいのが、もし1つのコンポーネント内で多くのセットアップやクリーンアップをしなければならない場合、ベストな解決策はたいていより細分化したコンポーネントを作ることです。このケースでは、再利用可能な `<input-datepic
`乗っている` -> `載っている` の typoですね。

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
> +全てのコードが乗っている[この fiddle](https://jsfiddle.net/chrisvfritz/1Leb7up8/)を見てください。しかしながら注意して欲しいのが、もし1つのコンポーネント内で多くのセットアップやクリーンアップをしなければならない場合、ベストな解決策はたいていより細分化したコンポーネントを作ることです。このケースでは、再利用可能な `<input-datepic
`しかしながら` だと固いので、ここは`しかし`の方が口語調で理解しやすいです。

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
> +よりプログラマティックリスナーの詳細を学ぶなら、[インスタンスメソッドイベント](https://vuejs.org/v2/api/#Instance-Methods-Events)の API をチェックしてください。
ここの`programmatic`も和訳お願いします 🙏

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
> +コンポーネントは自身をテンプレートで再帰的に呼び出すことができます。しかし、`name` オプションのみそうすることができます:
```
However, they can only do so with the `name`
```
の訳は以下のように意訳すると分かりやすいですね。

```
`name`オプションを使用することによって、それは可能です:
```

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
> +よく見てみると、これらのコンポーネントは逆説的ではありますが、それぞれ他のレンダリングツリーの子孫_と_祖先ということがわかります。 `Vue.component` でグローバルにコンポーネントを登録するとき、この逆説は自動的に解決されます。もしそれがあなたなら、ここで読むことをやめることもできます。 # TODO : if that's you が訳せない
意訳するとこんな感じでしょうか。

```
よく見ると、これらのコンポーネントが実際にそれぞれ他のレンダリングツリーの子孫_と_祖先になっていますね。矛盾してますね！`Vue.component` でグローバルにコンポーネントを登録するとき、この矛盾は自動的に解決されます。何を言っているのか分からないなら、これ以降読むのやめることができます。
```

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
> +今回は、そのことを `tree-folder` コンポーネントに教えてみましょう。私達はその逆説を生み出す子が、`tree-folder-contents` コンポーネントだということを知っています。なので、`beforeCreate` ライフサイクルフックが `tree-folder-contents` コンポーネントを登録するまで待ってみましょう:
paradoxは`矛盾`にしておきましょう。

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
> +通常これらを使用する必要はありませんが、手動でコンポーネントインスタンスを監視する必要があるときに用いることができます。それらはコードの統合ツールとしても役立ちます。例えば、時々サードパーティライブラリーを使用するためにこのようなパターンに遭遇するかもしれません:
`ライブラリー`は`ライブラリ`の方が自然ですね。

2018-05-24 12:00 UTC, kazupon commented on src/v2/guide/components-edge-cases.md
> +あなたは[配列](https://vuejs.org/v2/guide/list.html#Caveats)や[オブジェクト](https://vuejs.org/v2/guide/list.html#Object-Change-Detection-Caveats)、もしくは `data` と共に用いられる、Vue のリアクティブシステムに追跡されていない状態に依存しているかもしれないと言う変更
```
[配列](https://vuejs.org/v2/guide/list.html#Caveats)、または[オブジェクト](https://vuejs.org/v2/guide/list.html#Object-Change-Detection-Caveats) 、または例として`data`のようなリアクティブシステムによって追跡されていない状態に依存しているように、変更検出の警告を考慮していないかもしれません。
```
のように訳する感じでしょうか。

2018-05-24 12:02 UTC, kazupon commented
後、リンク先ですが、以下のようにいくつかVue関連のドキュメント先にリンクがあるのですが、そこは日本語訳のリンクにしておいてください。

- Vuex
- Vue公式サイト

2018-05-27 02:03 UTC, pipopotamasu commented
@kazupon レビューありがとうございます。確認します！

2018-05-28 14:52 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +事実、いわば"広範囲の props "のようなものと、依存性の注入について考えることができます。# TODO : expect はどう訳せばいいのだろう？
修正しました。
6646afd
7ccc434

2018-05-28 14:52 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +- セットアップコードが削除コードから分離している状態は、セットアップしたものをプログラムでクリーンアップすることをより難しくします。 # TODO: 上手く翻訳できない
修正しました。
6646afd

2018-05-28 14:52 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +この戦略を使用することで、私達はいくつかのインプット要素を持つ Pikaday さえ使うことができます。そしてそれぞれの新しいインスタンスは自動的にクリーンアップされます: # TODO : after itself が訳せない
修正しました。
6646afd

2018-05-28 14:52 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +よく見てみると、これらのコンポーネントは逆説的ではありますが、それぞれ他のレンダリングツリーの子孫_と_祖先ということがわかります。 `Vue.component` でグローバルにコンポーネントを登録するとき、この逆説は自動的に解決されます。もしそれがあなたなら、ここで読むことをやめることもできます。 # TODO : if that's you が訳せない
修正しました。
6646afd

2018-05-28 14:52 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +あなたは[配列](https://vuejs.org/v2/guide/list.html#Caveats)や[オブジェクト](https://vuejs.org/v2/guide/list.html#Object-Change-Detection-Caveats)、もしくは `data` と共に用いられる、Vue のリアクティブシステムに追跡されていない状態に依存しているかもしれないと言う変更
修正しました。
6646afd

2018-05-28 14:53 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +props とイベントが存在するにも関わらず、ときどき JavaScript で直接子コンポーネントにアクセスする必要があるかもしれません。このために `ref` 属性を使い、子コンポーネントにリファレンス ID を割り当てることができます。例えば:
修正しました。
969abfa

2018-05-28 14:53 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +## プログラマティックなイベントリスナー
修正しました。
b1d89e6

2018-05-28 14:53 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
>  // Attach the datepicker to an input once
修正しました。
5f0c72e

2018-05-28 14:54 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +プログラマティックリスナー使用することで両方の問題を解決することができます:
修正しました。
b1d89e6

2018-05-28 14:54 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +全てのコードが乗っている[この fiddle](https://jsfiddle.net/chrisvfritz/1Leb7up8/)を見てください。しかしながら注意して欲しいのが、もし1つのコンポーネント内で多くのセットアップやクリーンアップをしなければならない場合、ベストな解決策はたいていより細分化したコンポーネントを作ることです。このケースでは、再利用可能な `<input-datepic
修正しました。
80bedef
97811a8

2018-05-28 14:55 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +よりプログラマティックリスナーの詳細を学ぶなら、[インスタンスメソッドイベント](https://vuejs.org/v2/api/#Instance-Methods-Events)の API をチェックしてください。
修正しました。
b1d89e6

2018-05-28 14:55 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +コンポーネントは自身をテンプレートで再帰的に呼び出すことができます。しかし、`name` オプションのみそうすることができます:
修正しました。
c2edd4e

2018-05-28 14:56 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +今回は、そのことを `tree-folder` コンポーネントに教えてみましょう。私達はその逆説を生み出す子が、`tree-folder-contents` コンポーネントだということを知っています。なので、`beforeCreate` ライフサイクルフックが `tree-folder-contents` コンポーネントを登録するまで待ってみましょう:
修正しました。
6255b28

2018-05-28 14:56 UTC, pipopotamasu commented on src/v2/guide/components-edge-cases.md
> +通常これらを使用する必要はありませんが、手動でコンポーネントインスタンスを監視する必要があるときに用いることができます。それらはコードの統合ツールとしても役立ちます。例えば、時々サードパーティライブラリーを使用するためにこのようなパターンに遭遇するかもしれません:
修正しました。
55bb7a7

2018-05-28 14:56 UTC, pipopotamasu commented
> 後、リンク先ですが、以下のようにいくつかVue関連のドキュメント先にリンクがあるのですが、そこは日本語訳のリンクにしておいてください。

以下のコミットで修正しました。
436d94f

2018-05-28 14:57 UTC, pipopotamasu commented
@kazupon こちら修正完了しました。確認お願いします。

2018-05-29 02:34 UTC, kazupon approved these changes

2018-05-29 02:34 UTC, kazupon commented
👍 
ありがとうございました！マージします！

2018-05-29 02:34 UTC, merged

2018-05-29 10:03 UTC, pipopotamasu commented
@kazupon レビューありがとうございました！