issue #1000 に対応
vuejs/jp.vuejs.org pull request #1025
Opened 2018-05-24 06:52 UTC by desigrammer

#1000 における更新に対応しました。
レビューをおねがいします。

2018-05-24 10:52 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
対応お願いします。 🙏

2018-05-24 10:52 UTC, kazupon commented on src/v2/api/index.md
> +  `$emit` を1つのイベント名のみと共に使う場合:
`1つの`という意訳の修飾はここでは`のみ` (`only`)があるので必要ないですね。

2018-05-25 01:23 UTC, desigrammer commented on src/v2/api/index.md
> +  `$emit` を1つのイベント名のみと共に使う場合:
'an' を訳す気持ちが強く出すぎたようです。修正します。

2018-05-25 01:27 UTC, kazupon approved these changes

2018-05-25 01:27 UTC, merged

2018-05-25 01:27 UTC, kazupon commented
@desigrammer ありがとうございます！