[WIP] Vue コンポーネント npm パッケージ化翻訳
vuejs/jp.vuejs.org pull request #1038
Opened 2018-05-28 09:50 UTC by desigrammer

#1033 に対応しています。ページを何回かに分割して翻訳、随時コミットいたします。
終了予定は 2018 6/3 までの予定です。

2018-06-04 10:21 UTC, kazupon requested changes
翻訳ありがとうございます！
レビュー 👀 コメント 💬 しました。
確認お願いします！

2018-06-04 10:21 UTC, kazupon commented on src/v2/cookbook/packaging-sfc-for-npm.md
> +> 「なぜみんなは `.vue` ファイルを直接使ってくれないんだ？これがコンポーネントを共有する最も簡単な方法だろ？」
少し、口調が砕けすぎているので、以下でお願いします。

```
「なぜみんなは `.vue` ファイルを直接使ってくれないんだろう？これがコンポーネントを共有する最も簡単な方法でしょう？」
```

2018-06-04 10:21 UTC, kazupon commented on src/v2/cookbook/packaging-sfc-for-npm.md
> +その考えは正しく、`.vue` ファイルは直接共有する事ができ、Vue コンパイラを含んで [ビルドされた Vue](https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds) を利用する人は誰でもそのファイルを直ちに利用できます。また、サーバサイドレンダリングのためのビルドにおいては文字列の連結を最
リンク`https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds`ですが、日本語の公式ドキュメント内のリンク先がお願いします 🙏 
https://jp.vuejs.org/v2/guide/installation.html#さまざまなビルドについて

2018-06-04 10:21 UTC, kazupon commented on src/v2/cookbook/packaging-sfc-for-npm.md
> +            compileTemplate: true, // 明示的にテンプレートをレンダ関数に変換
`レンダ` ではなく、 `描画` でお願いします。日本語ドキュメントでは、`描画`に統一してますので。

2018-06-04 10:21 UTC, kazupon commented on src/v2/cookbook/packaging-sfc-for-npm.md
> +また、ここでコンポーネントに付与された `name` の値に注目すべきです。コンポーネントに付与されるのはパスカル・ケースの名称で、これはここまでの手順で利用されてきたケバブ・ケースの名称に対応していなければなりません。
`パスカル・ケース` 、`ケバブ・ケース` のおいて `-` と対応するよう `・` にしていますが、この`・`削除お願いします！日本語ドキュメントでは、このように統一していますので。

2018-06-05 03:00 UTC, desigrammer commented
承知しました。修正します。

2018-06-05 03:13 UTC, desigrammer commented
レビューしていただいた箇所を修正しました。改めてレビューをお願いできますでしょうか。

2018-06-05 04:41 UTC, kazupon approved these changes

2018-06-05 04:41 UTC, merged

2018-06-05 04:41 UTC, kazupon commented
@desigrammer 
翻訳ありがとうございました！ 🎉