本家の更新を反映( 本家 f3d9557 )
vuejs/jp.vuejs.org pull request #1056
Opened 2018-06-06 09:13 UTC by desigrammer

#1044 に対応しました。レビューをお願いします。

2018-06-06 09:14 UTC, desigrammer commented
個人的に`meetup` を `集会` としているのが気になるのですが `ミートアップ` もしくは `勉強会` の方がよろしいでしょうか。

2018-06-07 01:43 UTC, kazupon requested changes
PRありがとうございます！
レビュー 👀 コメント 💬 しました。
対応お願いします！ 🙏

2018-06-07 01:43 UTC, kazupon commented on src/v2/guide/join.md
> +- **自身で集会を開催する。** もし Vue の集会が近隣でまだ開催されていなければ、  [vuemeetups.org の情報](https://www.vuemeetups.org/resources/#introduction) を使う事が成功につながります！
`集会` は `ミートアップ`でいいと思います。

2018-06-07 03:01 UTC, desigrammer commented
レビューして頂いたコメントを元に修正しました。
改めてレビューをお願いできますでしょうか。

2018-06-07 06:27 UTC, kazupon approved these changes
👍

2018-06-07 06:28 UTC, merged

2018-06-07 06:28 UTC, kazupon commented
ありがとうございました！