WIP [Cookbook]Translate client-side storage
vuejs/jp.vuejs.org pull request #1090
Opened 2018-06-26 11:43 UTC by nicedchy

WIPのPRです。
大まかな翻訳は終了していますが、細かい表現、外部リンクなどを修正中です。
適宜指摘して頂けると助かります 🙏

2018-06-26 12:25 UTC, ysgk commented on src/v2/cookbook/client-side-storage.md
`to add a new cat` は `a small form at the bottom` にかかると考えるのが自然かなと思いました。
「上部のシンプルなリスト（）と新しい猫を追加するための下部の小さなフォーム」

2018-06-26 12:34 UTC, ysgk commented on src/v2/cookbook/client-side-storage.md
細かくて恐縮ですが、`serialize` は 単に `シリアライズ` とするか `直列化` が一般的な訳語かと思います。`シリアライズ化` では `-ise` と `化` で意味が重複していますので :sweat_smile:

2018-06-26 12:49 UTC, ysgk commented on src/v2/cookbook/client-side-storage.md
ここの一文目がちょっと間違ってて、 `localStorage.name` みたいにプロパティにダイレクトにアクセスするのではなく `getItem`と`setItem`というAPIを使うように切り替えたという意味ですね。

最後の文は注意喚起のニュアンスが足りてなくて、`Web アプリケーションがクライアントサイドストレージを使用するときはいつでも、ユーザーはそれにアクセスして好きなように変更することができるということを忘れないでください`くらいの表現のほうがいいかなーと思いました。

2018-06-26 13:14 UTC, ysgk commented on src/v2/cookbook/client-side-storage.md
`live` の訳、悩ましいですよね...（特に案は無い）

2018-06-27 01:22 UTC, nicedchy commented on src/v2/cookbook/client-side-storage.md
レビューありがとうございます。
`シリアライズ` に寄せたいと思います〜。

2018-06-27 01:57 UTC, nicedchy commented
WIPを外しました。
レビューお願いします 🙏

2018-06-27 09:03 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
対応お願いします！

2018-06-27 09:03 UTC, kazupon commented on src/v2/cookbook/client-side-storage.md
> +クライアントサイドストレージは、パフォーマンスの向上をアプリケーションに対してすばやく追加する優れた方法です。ブラウザ自体にデータを格納することで、ユーザが必要とするたびにサーバから情報を取得するのをスキップすることができます。オフラインのとき特に便利ですが、オンラインユーザでもリモートサーバと比較してローカルデータを使用することにメリットがあります。クライアントサイドストレージは、[cooki
`cookies` も翻訳してもいい気がします。

2018-06-27 09:03 UTC, kazupon commented on src/v2/cookbook/client-side-storage.md
> +このクッキングブックでは最も単純なストレージメカニズムの、ローカルストレージに焦点を当てます。ローカルストレージはデータを格納するための key/value システムを使用します。単純な値だけを格納することに限られますが JSON で値をエンコード及びデコードする場合は複雑なデータを格納できます。一般的に、ローカルストレージは保持したいと思う小さなデータセット、環境設定やフォームデータなどに適し
`クッキングブック` ではなく、 `クックブック` ですね。

2018-06-27 09:03 UTC, kazupon commented on src/v2/cookbook/client-side-storage.md
> +このアプリケーションでは、"ダイレクト" アクセスに対しローカルストレージ APIs を使用するように切り替えました。どちらも機能しますが API メソッドのほうが一般的に好まれます。`mounted` は値を取得し JSON の値を解析する必要があります。もし何か問題が発生した場合データが破損していると判断しそれを削除します。（Web アプリケーションがクライアントサイドストレージを使用すると
`APIs` は日本語訳では、 `API` でいいと思います。

2018-06-27 09:03 UTC, kazupon commented on src/v2/cookbook/client-side-storage.md
> +猫を処理するための3つのメソッドがあります。`addCat` と `removeCat` は `this.cats` に格納されている "ライブ" Vue データの更新を処理します。次にデータのシリアライズと永続化を処理する `saveCats` を実行します。あなたは次のバージョンを試すことができます:
`live`の訳ですが、ここはまさに TV の生方法でよく使うライブの意味なので、`"生"`のような訳はいかがでしょうか？

2018-06-27 09:32 UTC, nicedchy commented
@kazupon 
レビューしていただいた項目を修正しました。

2018-06-27 10:02 UTC, kazupon approved these changes

2018-06-27 10:03 UTC, kazupon commented
@nicedchy 
ありがとうございます！ ✨ 
ようさそうです！
マージします！

2018-06-27 10:03 UTC, merged