[Components In-Depth]: Propsの翻訳
vuejs/jp.vuejs.org pull request #1107
Opened 2018-07-15 04:28 UTC by potato4d

resolve #919

## About

Components In-Depth の Props のページについて翻訳を行いました。

## Refs

### 原文
https://vuejs.org/v2/guide/components-props.html

### 翻訳対象
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/guide/components-props.md

2018-07-15 04:29 UTC, potato4d commented
@re-fort 
大変遅くなってしまいすみません 🙇 
翻訳について一旦完了しましたので、レビューお願いできますでしょうか！

2018-07-15 04:30 UTC, potato4d commented on src/v2/guide/components-props.md
> +> This prevents child components from accidentally mutating the parent's state, which can make your app's data flow harder to understand.
@re-fort 
ここだけ翻訳がうまく思いつきませんでした。
文脈としては、 props を利用することでデータの流れが単一となり、フローが追いやすくなるはずなのですが、原文が `This prevents child components from accidentally mutating the parent's state, which can make your app's data flow **harder** to understand.` となっていて少し不思議です。ご意見いただけますか？

2018-07-15 04:31 UTC, potato4d commented on src/v2/guide/components-props.md
> +1. **プロパティを初期値として受け渡し、子コンポーネントにてローカルのデータとして後で利用したいと考える場合** この場合、プロパティの値をローカルの data の初期値として定義することを推奨します:
@re-fort 
また、 props が "プロパティ"、 data が "データプロパティ"、 computed が "算出プロパティ" となってきており、props をプロパティと翻訳すると文章の読みづらさに影響してくるため、そろそろ props 表記に寄せるべきかと考えていたりするのですが、いかがでしょうか？

2018-07-18 06:18 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
内容確認お願いします。

2018-07-18 06:18 UTC, kazupon commented on src/v2/guide/components-props.md
>  <!-- Dynamically assign the value of a variable -->
コメントも翻訳お願いします！ 🙏

2018-07-18 06:18 UTC, kazupon commented on src/v2/guide/components-props.md
> +上の 2 つの例では、文字列の値を渡していますが、プロパティには任意の型の値を渡すことが可能です。
`_any_` のitalicが、翻訳の方にないようです。

2018-07-18 06:18 UTC, kazupon commented on src/v2/guide/components-props.md
> +> This prevents child components from accidentally mutating the parent's state, which can make your app's data flow harder to understand.
`which can make your app's data flow **harder** to understand.` の `which` は、`child components from accidentally mutating the parent's state` の関係代名詞な気がします。以下な感じでどうでしょうか？
`これによって、アプリのデータフローを理解しづらい可能性のある子コンポーネントによる誤った親の状態変更から、防ぎます。`

2018-07-18 06:34 UTC, potato4d commented
@kazupon 
レビューありがとうございます 🙇 
`which can make your app's data ~……` の部分、確かにそういうことなきがします。助かりました :pray:

対応いたしましたので再度ご確認お願いいたします！

2018-07-18 06:54 UTC, kazupon approved these changes

2018-07-18 06:55 UTC, potato4d commented
@kazupon 
良さそうなのでこれはマージしちゃいますね。

@re-fort 
Props を "プロパティ" として訳し続けるかどうかはちょっと議論の余地があると思うので、よければどこかのタイミングでご回答いただけると！

2018-07-18 06:55 UTC, merged

2018-07-18 15:42 UTC, re-fort commented on src/v2/guide/components-props.md
> +1. **プロパティを初期値として受け渡し、子コンポーネントにてローカルのデータとして後で利用したいと考える場合** この場合、プロパティの値をローカルの data の初期値として定義することを推奨します:
@potato4d  確認おそくなってすみません！
そうですねー、それは少し思ってました
property, propertiesはプロパティとして、propsはそのままにするのも良いかと思います！

2018-07-19 01:40 UTC, potato4d commented on src/v2/guide/components-props.md
> +1. **プロパティを初期値として受け渡し、子コンポーネントにてローカルのデータとして後で利用したいと考える場合** この場合、プロパティの値をローカルの data の初期値として定義することを推奨します:
@re-fort ではちょっと混在しそうなところにおいての props は props としましょう！
試しにこのドキュメントについて更新 PR を後ほどで打ってみますね〜