dockerize vuejs appを翻訳
vuejs/jp.vuejs.org pull request #1126
Opened 2018-07-25 05:55 UTC by resessh

遅くなってすみません。
意訳やあまり納得のいっていない部分などもあるため、一旦レビューをお願いしたいです。

this closes #1086

2018-07-25 06:17 UTC, potato4d requested changes
PR ありがとうございます！
詳細の翻訳についてのレビューは後ほど行いますが、一旦クックブックのレビューフォーマット周り + α だけ書いておきます。

2018-07-25 06:17 UTC, potato4d commented on src/v2/cookbook/dockerize-vuejs-app.md
> +## 代替案
クックブックでは統一して「代替パターン」と翻訳しています。ご連絡が漏れてしまってすみません 🙇

2018-07-25 06:17 UTC, potato4d commented on src/v2/cookbook/dockerize-vuejs-app.md
> +よくある代替案は以下の通りです:
こちらも代替パターンで 🙇

2018-07-25 06:17 UTC, potato4d commented on src/v2/cookbook/dockerize-vuejs-app.md
> +# 本番ステージ
単語としては `environment` の意味になってしまうのですが、この場合においてだと「環境」としたほうがわかりやすいかもしれませんね

2018-07-25 06:17 UTC, potato4d commented on src/v2/cookbook/dockerize-vuejs-app.md
> +# ビルドステージ
単語としては `environment` の意味になってしまうのですが、この場合においてだと「環境」としたほうがわかりやすいかもしれませんね

2018-07-25 06:22 UTC, resessh commented on src/v2/cookbook/dockerize-vuejs-app.md
> +# 本番ステージ
`本番環境ステージ` という意味で大丈夫でしょうか？

2018-07-25 06:23 UTC, potato4d commented on src/v2/cookbook/dockerize-vuejs-app.md
> +# 本番ステージ
「本番環境」くらいまで崩してしまっても良いかもしれませんねーというところでした。
ここは任意でお任せします！

2018-07-25 06:25 UTC, resessh commented on src/v2/cookbook/dockerize-vuejs-app.md
> +# 本番ステージ
ステージの扱いは苦慮したのでそうします！ありがとうございます！ 🙏

2018-07-25 06:30 UTC, resessh commented on src/v2/cookbook/dockerize-vuejs-app.md
> +* SPA を [Amazon S3](https://aws.amazon.com/jp/s3/) でホスティングし、 [Amazon CloudFront](https://aws.amazon.com/jp/cloudfront/)（[こちら](https://serverless-stack.com/chapters/deploy-the-frontend.html) のリンクで詳細なガ
👀 awsは公式の日本語ドキュメントがあるのでlink先を変更

2018-07-25 09:47 UTC, resessh commented
#1129 がマージされたら追従します

2018-07-25 10:15 UTC, potato4d commented
@resessh 
お手数おかけします 🙇

2018-07-25 10:49 UTC, ysgk commented on src/v2/cookbook/dockerize-vuejs-app.md
>  WORKDIR /app
既に存在する `app` フォルダを `WORKDIR` に指定するという文脈なので `作成する` ではなく 他の表現に修正お願いします 🙇

2018-07-25 10:51 UTC, ysgk commented on src/v2/cookbook/dockerize-vuejs-app.md
>  COPY package*.json ./
`if available` は `package-lock.json` の方だけにかかるので、それがわかる書き方にしてください。

2018-07-25 10:56 UTC, ysgk commented on src/v2/cookbook/dockerize-vuejs-app.md
ここの `a very good reason` の `good` は `好ましい` というよりは `十分な`、`もっともな` の意味です。

2018-07-25 11:01 UTC, ysgk commented on src/v2/cookbook/dockerize-vuejs-app.md
ここの `good reasons` も同じです。

2018-07-25 11:12 UTC, ysgk commented on src/v2/cookbook/dockerize-vuejs-app.md
`each running` 以降は `small services` を修飾しているだけなので、文頭に持ってきたほうが収まりが良さそうです。
`独自のプロセスで動き、軽量な機構で連携する小さなサービスの集まりとして単一のアプリケーションを構築することになります。`

2018-07-25 11:19 UTC, ysgk commented on src/v2/cookbook/dockerize-vuejs-app.md
typo `強力` -> `協力`

2018-07-25 11:28 UTC, ysgk commented on src/v2/cookbook/dockerize-vuejs-app.md
`では無い` -> `ではない`

2018-07-25 11:33 UTC, ysgk commented
@resessh いくつかコメントしました。ご確認ください🙏

2018-07-26 00:35 UTC, resessh commented on src/v2/cookbook/dockerize-vuejs-app.md
>  WORKDIR /app
直訳太郎すぎる…

2018-07-26 01:41 UTC, resessh commented on src/v2/cookbook/dockerize-vuejs-app.md
`very` を含めて日本語でナチュラルな訳にすると `とてもよい理由` 程度にしてもいいのかなと思ったのですがどうでしょう…？

2018-07-26 01:42 UTC, resessh commented on src/v2/cookbook/dockerize-vuejs-app.md
こちらは `もっともな理由` でいこうと思います

2018-07-26 01:50 UTC, ysgk commented on src/v2/cookbook/dockerize-vuejs-app.md
個人的には、理由を 良い/悪い で表現するのがあまりピンときません。「悪い理由」ってなんだろう？とか考えてしまいます。`とてももっともな` の方が意味が取りやすいと思うのですがいかがですか？

2018-07-26 01:50 UTC, resessh commented on src/v2/cookbook/dockerize-vuejs-app.md
`連携`、`集まり` など単語選びも含め非常に勉強になりました。こちらをそのまま使わせていただきます 🙇

2018-07-26 01:51 UTC, ysgk commented on src/v2/cookbook/dockerize-vuejs-app.md
あるいは、単に `十分な理由` でも very の語感は出ると思います。

2018-07-26 01:52 UTC, resessh commented on src/v2/cookbook/dockerize-vuejs-app.md
なるほど、たしかにそうですね。こちらも `とてももっともな理由` でいきたいと思います 🙏

2018-07-26 01:56 UTC, resessh commented on src/v2/cookbook/dockerize-vuejs-app.md
🤦‍♂️

2018-07-26 02:07 UTC, resessh commented
ここまでご指摘いただいた点の対応終わっています。

2018-07-27 11:51 UTC, potato4d approved these changes
@resessh
おまたせしました 🙇 
だすにあたって特別問題なさそうです！ありがとうございます！

@ysgk
レビューコメントありがとうございます！負担がグッと減って助かりました :pray:

2018-07-27 11:51 UTC, merged