いくつかの誤訳の修正と訳文の改善
vuejs/jp.vuejs.org pull request #1139
Opened 2018-07-27 19:41 UTC by ysgk

[クラスとスタイルのバインディング](https://jp.vuejs.org/v2/guide/class-and-style.html) ページを読んでいていくつか翻訳ミスが気になったので修正してみました。

レビューよろしくお願いします 🙏

2018-07-27 19:49 UTC, ysgk commented on src/v2/guide/class-and-style.md
・`need` は必要なことというよりは `需要` の意味ですね。
・`only need to`
・最後の `evaluate to objects or arrays.` は `オブジェクトや配列に（評価結果として）なる` という意味なので、`返す` としてみました。

2018-07-27 19:51 UTC, ysgk commented on src/v2/guide/class-and-style.md
冗長で文の意味が取りづらかったので、簡潔な表現に置き換えました。`真偽性` というのはそれほど一般的な言葉ではないかもしれませんが、意味は外してないかなと。

2018-07-27 19:52 UTC, ysgk commented on src/v2/guide/class-and-style.md
`given` は `もし仮に〜` なのでこうしました

2018-07-27 19:54 UTC, ysgk commented on src/v2/guide/class-and-style.md
↑の方で `truthy (true になりうる)` と説明してあるので、ここではそのまま使っても良いかなと思いました。

2018-07-27 19:56 UTC, ysgk commented on src/v2/guide/class-and-style.md
誤訳修正。

本当は `JavaScript オブジェクトであることを除けば` と書きたかったけど、である/ですます 混在を textlint に怒られた :cry:

2018-07-27 19:57 UTC, ysgk commented on src/v2/guide/class-and-style.md
`detect and add` が両方 `appropriate prefixes` に掛かると思われます。

2018-07-28 11:12 UTC, re-fort commented on src/v2/guide/class-and-style.md
良いと思います！
お手数ですが、mdnへのリンクを[ja](https://developer.mozilla.org/ja/docs/Glossary/Truthy)版にしていただけると！

2018-07-28 11:19 UTC, re-fort commented on src/v2/guide/class-and-style.md
truthyが日本語で表現しにくい概念ならそのまま使いたいですが、
そうではないので個人的には上の`truthy (true になりうる)`を`真と評価される`と訳してしまって、ここも同じ訳を適用したほうが良いかなと思います

2018-07-28 11:21 UTC, re-fort requested changes
誤訳修正/翻訳改善ありがとうございます！
なんこかコメントしていますので、確認していただけると:pray:

2018-07-28 12:03 UTC, ysgk commented on src/v2/guide/class-and-style.md
なるほど。適用してみたらそれなりに読みやすかったので、それで行きます 👍

2018-07-28 12:05 UTC, ysgk commented
@re-fort レビューありがとうございます 🙏
ご指摘の点を反映しました。

2018-07-28 13:00 UTC, re-fort approved these changes
LGTM:+1:
ありがとうございます:blush:

2018-07-28 13:00 UTC, merged

2018-07-28 13:58 UTC, kazupon commented
@ysgk 
レビュー＆修正、いつもありがとうございます！