reactivity の改善
vuejs/jp.vuejs.org pull request #1140
Opened 2018-07-28 18:36 UTC by ysgk

筆が乗ったので昨日に引き続いて訳文の改善です。
誤訳の修正と、熟れない表現を結構修正しています。 
レビューをお願いします 🙏 

原文
https://vuejs.org/v2/guide/reactivity.html

2018-07-28 18:38 UTC, ysgk commented on src/v2/guide/reactivity.md
・`インターフェース` -> `インスタンス`
・`dependency` は `依存性` で統一しました。

2018-07-28 18:40 UTC, ysgk commented on src/v2/guide/reactivity.md
・`a class of` = `...の類の`

2018-07-28 18:42 UTC, ysgk commented on src/v2/guide/reactivity.md
・`In case you haven’t noticed yet` = `まだ気づいていないといけないから`
日本語としては `おそらく既にお気づきでしょうが` のほうが自然ですね。

2018-07-28 18:44 UTC, ysgk commented on src/v2/guide/reactivity.md
誤訳修正

2018-07-28 18:44 UTC, ysgk commented on src/v2/guide/reactivity.md
表現の改善と誤訳修正

2018-08-04 15:57 UTC, re-fort commented on src/v2/guide/reactivity.md
> +プレーンな JavaScript オブジェクトを `data` オプションとして Vue インスタンスに渡すとき、Vue はその全てのプロパティを渡り歩いて、それらを [Object.defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/def
たびたびすみません。
今回の改善内容外ですが、リンクを[日本語](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty)に差し替えていただけると:pray:

2018-08-04 16:10 UTC, re-fort commented on src/v2/guide/reactivity.md
> +`vm.$nextTick()` というメソッドもあります。これは、グローバルな Vue を必要とせず、コールバックの `this` コンテキストが自動的に現在の Vue インスタンスに束縛されるため、コンポーネント内で特に役立ちます:
インスタンスメソッドのインスタンスが落ちてしまっているので、追加していただけると！

2018-08-04 16:12 UTC, re-fort requested changes
@ysgk 
確認遅くなりました。
すごく読みやすくなりましたね:blush:
1点だけ修正おねがいします:pray:

2018-08-07 07:19 UTC, ysgk commented
@re-fort 
レビューありがとうございます 🙏
ご指摘の点を修正しました。

2018-08-07 07:28 UTC, re-fort approved these changes

2018-08-07 07:29 UTC, re-fort commented
@ysgk ありがとうございます:blush:

2018-08-07 07:29 UTC, merged