WIP 公式blog/Vue CLI 3.0 is here!の翻訳
vuejs/jp.vuejs.org pull request #1181
Opened 2018-08-25 06:46 UTC by chi-bd

https://medium.com/the-vue-point/vue-cli-3-0-is-here-c42bebe28fbb
の翻訳です

2018-08-26 07:00 UTC, potato4d commented
@chi-bd こちら火曜日あたりをめどに見ます 🙇

2018-08-30 07:41 UTC, potato4d requested changes
@chi-bd 
翻訳ありがとうございます。遅くなり恐縮ですが、2点の修正と、2点の提案について意見をもらえると幸いです🙏

2018-08-30 07:41 UTC, potato4d commented on src/_posts/vue-cli-3-0-is-here.md
> +Vue CLI 3 で、同じコードベースを使用してアプリケーション、 UMD ライブラリ、またはネイティブ Web コンポーネントを構築できます。どんなターゲットを構築していても同じ Vue 開発エクスペリエンスを楽しむことができます。
[note][want comment]
エクスペリエンスは体験に翻訳してしまっても良いかもしれないですね

2018-08-30 07:41 UTC, potato4d commented on src/_posts/vue-cli-3-0-is-here.md
> +1. どんな Vue アプリのデフォルトにもなるよう、可能な限りツールチェインにベストプラクティスを組込む
[must]
1. を複数続けても Markdown パーサーによっては正しく認識されますが、 ここは 2. でお願いします 🙇

2018-08-30 07:41 UTC, potato4d commented on src/_posts/vue-cli-3-0-is-here.md
> +## 今日それを試してみましょう！
[note][want comment]
ドキュメントではなくブログの体裁ですし、もう少し触りたくなるようなしゃれた言い回しにしてしまっても良いかもしれないですね。

2018-08-30 07:41 UTC, potato4d commented on src/_posts/vue-cli-3-0-is-here.md
> +- [hot module replacement](https://webpack.js.org/concepts/hot-module-replacement/)、[コード分​​割](https://webpack.js.org/guides/code-splitting/)、 [tree Shaking](https://webpack.js.org/guides/tree-shaking
[must]
本家が Medium なので修正できないですが、 hot module replacement / tree Shaking はそれぞれ Hot Module Replacement / Tree Shaking なのでこちらだけでも正しい表記にしておきましょう🙏

2018-08-30 12:50 UTC, potato4d approved these changes
@chi-bd よさそうです。ありがとうございます！！

2018-08-30 12:51 UTC, merged

2018-08-30 12:57 UTC, kazupon commented
@chi-bd いつも、ありがとうございます！