🍒 Update comparison.md (#1811)
vuejs/jp.vuejs.org pull request #1244
Opened 2018-10-01 05:23 UTC by potato4d

resolve #1235

2018-10-01 08:05 UTC, kazupon requested changes

2018-10-01 08:05 UTC, kazupon commented on src/v2/guide/comparison.md
> +- 性能面では、Ember 2.0 で最新の Glimmer エンジンのアップデートがされた後にも関わらず、Vue は大きく差をつけて Ember よりも[優れています](https://stefankrause.net/js-frameworks-benchmark8/table.html)。Ember では性能が重要な状況において、手動でランループ（run loop）を管理する必要がある一方
`Ember 3.x.` の漏れてるようなのでお願いします！ 🙏

2018-10-02 05:11 UTC, potato4d commented on src/v2/guide/comparison.md
> +- 性能面では、Ember 2.0 で最新の Glimmer エンジンのアップデートがされた後にも関わらず、Vue は大きく差をつけて Ember よりも[優れています](https://stefankrause.net/js-frameworks-benchmark8/table.html)。Ember では性能が重要な状況において、手動でランループ（run loop）を管理する必要がある一方
@kazupon おっと、申し訳ないです 🙇

2018-10-02 05:13 UTC, potato4d commented
@kazupon こちら対応しました :pray:

2018-10-02 05:16 UTC, kazupon approved these changes

2018-10-02 05:16 UTC, merged