Translate Vue CLI related doc updates
vuejs/jp.vuejs.org pull request #1363
Opened 2018-12-22 03:02 UTC by oohira

## 概要

Vue CLI 関連の未対応Issueを訳しました。今さらですが、Issue 1つにつき Pull Request も1つ作った方がレビューしやすいでしょうか？

* resolve #1341 
* resolve #1344 

## 補足

* [Doc]: Recommend Vue CLI 3 instead of Vue CLI 2 #1341
    * cherry-pick & translate vuejs/vuejs.org@eb2f374
* [Doc]: brush up tooling section with redirects to CLI #1344
    * cherry-pick & translate vuejs/vuejs.org@2f6dbef

2018-12-22 03:07 UTC, oohira commented on src/v2/guide/typescript.md
> +> [Vue CLI](https://cli.vuejs.org) は、TypeScript ツールのサポートを組み込みで提供します。次期メジャーバージョンの Vue (3.x) では、クラスベースのコンポーネント API をもつ TypeScript サポートと TSX サポートの大幅な改善も予定しています。
>  In our next major version of Vue (3.x), we are also planning to considerably improve our TypeScript support with built-in class based components API and TSX support.

原文で以下の解釈のどちらが正しいのか自信をもてませんでした。supportが対になっているのかなと思って前者で訳していますが、ご指摘あればお願いします。

1. improve our (TypeScript support with built-in class based components API) and (TSX support).
1. improve our TypeScript support with built-in (class based components API and TSX support).

2018-12-23 14:05 UTC, kazupon requested changes
PRありがとうございました！
レビュー 👀 コメント 💬 しました！
対応お願いいたします！

2018-12-23 14:05 UTC, kazupon commented on src/v2/guide/single-file-components.md
> +CLI はツール設定の大部分の面倒を見てくれますが、 [設定オプション](https://cli.vuejs.org/config/) を通してきめ細かなカスタマイズをすることも許しています。
allow の訳ですが意訳ですが、`カスタマイズをすることも許しています` より `カスタマイズをすることもできます` の方が読み手が分かりやすいので、そちらの訳でお願いしたいです。 🙏

2018-12-23 14:05 UTC, kazupon commented on src/v2/guide/typescript.md
> +> [Vue CLI](https://cli.vuejs.org) は、TypeScript ツールのサポートを組み込みで提供します。次期メジャーバージョンの Vue (3.x) では、クラスベースのコンポーネント API をもつ TypeScript サポートと TSX サポートの大幅な改善も予定しています。
前者で大丈夫だと思います！

2018-12-23 14:05 UTC, kazupon commented on src/v2/guide/unit-testing.md
> +> [Vue CLI](https://cli.vuejs.org/) には、[Jest](https://github.com/facebook/jest) または [Mocha](https://mochajs.org/) を使って難しい設定なしにユニットテストするための組み込みのオプションがあります。カスタムセットアップのためのより詳細なガイダンスとなる公式の [vue-test-util
`vue-test-utils` 、本家公式の方がそうなっているんですね。。。個人的に表記は本家も合わせて `Vue Test Utils` にしたいところです。

2018-12-24 01:38 UTC, oohira commented on src/v2/guide/single-file-components.md
> +CLI はツール設定の大部分の面倒を見てくれますが、 [設定オプション](https://cli.vuejs.org/config/) を通してきめ細かなカスタマイズをすることも許しています。
レビューありがとうございます。 97ca679 で修正済みです。

2018-12-24 01:40 UTC, oohira commented on src/v2/guide/unit-testing.md
> +> [Vue CLI](https://cli.vuejs.org/) には、[Jest](https://github.com/facebook/jest) または [Mocha](https://mochajs.org/) を使って難しい設定なしにユニットテストするための組み込みのオプションがあります。カスタムセットアップのためのより詳細なガイダンスとなる公式の [vue-test-util
本家にPR出しました。一応、本家にマージされてから日本語の方も対応しようと思います。

* https://github.com/vuejs/vuejs.org/pull/1921

2018-12-26 14:11 UTC, oohira commented on src/v2/guide/unit-testing.md
> +> [Vue CLI](https://cli.vuejs.org/) には、[Jest](https://github.com/facebook/jest) または [Mocha](https://mochajs.org/) を使って難しい設定なしにユニットテストするための組み込みのオプションがあります。カスタムセットアップのためのより詳細なガイダンスとなる公式の [vue-test-util
お待たせしました。 489475015a39997c659459ce613127fd63a78927 で修正しました。

なお、先の翻訳時に見出し (`## テストツールとセットアップ`) 部分の削除が漏れていたため、今回の修正で合わせて反映しました 🙇

2018-12-27 02:05 UTC, kazupon approved these changes

2018-12-27 02:05 UTC, kazupon commented
ありがとうございます！マージしますね！

2018-12-27 02:06 UTC, merged