該当箇所の訳出
vuejs/jp.vuejs.org pull request #1371
Opened 2018-12-31 09:54 UTC by superyusuke

## 概要

resolve #1297

リントの語調統一ルールにひっかかって、エラーが出た状態でプルリク出させていただきました。自分ではですますに統一したつもりです。申し訳ありません。

## 補足

2018-12-31 10:03 UTC, potato4d requested changes
ひとまず誤検知について該当箇所を書きました！ Suggestion も使ってあるので、適宜取り込んで修正お願いします 🙇

2018-12-31 10:03 UTC, potato4d commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +最後に scoped slot を追加して、望む仕事をしてもらうことにしましょう。これによって、親コンポーネントの中から、子コンポーネントのプロパティにアクセすることができるようになります。子コンポーネントの中に `<slot>` タグを追加し、さらに `v-bind` もしくは `:propName` を使って、親コンポーネントへと露出させたい値をプロパティとして渡します。これは通常の pro
ここの「である」が誤検知されているみたいですね……。お手数ですが言い換えてみてください。もし思いつかなそうであれば、後で考えて提案させてもらいます！

2018-12-31 10:03 UTC, potato4d commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +このような非常に複雑な解決法は魅力的に思われかもしれませんが、ある一定のレベルまでその複雑さが進んでしまうと、その抽象性が、この機能を構成する他のコードの部分よりもかなり高くなってしまい、浮いた存在になってしまうでしょう。その段階まできたのであれば、add-on に抽出することを検討する段階でしょう。(訳注: add-on はおそらく、plugin や mixin などのことです)
「その段階まできたのであれば」が誤検知みたいですね。こんな感じでどうでしょう？
（中身の文章自体の訳の正確さはまだ見ていないので、どこかで修正依頼を出すかもしれません）

```suggestion
このような非常に複雑な解決法は魅力的に思われるかもしれませんが、ある一定のレベルまでその複雑さが進んでしまうと、その抽象性が、この機能を構成する他のコードの部分よりもかなり高くなってしまい、浮いた存在になってしまうでしょう。そこまできた場合は、add-on に抽出することを検討する段階でしょう。(訳注: add-on はおそらく、plugin や mixin などのことです)
```

2018-12-31 10:03 UTC, potato4d commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +このパターンは Google Map の場合にしか使えないわけではありません。どんなライブラリであれ、ベースとなるコンポーネントをセットして、(ベースコンポーネントを呼び出したコンポーネントが実行する) API を露出させればいいのです。
「どんなライブラリであれ、」が該当しますね。以下でどうでしょう？

```suggestion
このパターンは Google Map の場合にしか使えないわけではありません。どんなライブラリでも、ベースとなるコンポーネントをセットして、(ベースコンポーネントを呼び出したコンポーネントが実行する) API を露出させればいいのです。
```

2018-12-31 17:31 UTC, superyusuke commented
一旦申請しました〜

2019-01-01 18:45 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
対応お願いします。

後、いくつか `訳注` が入っていますが、日本語公式ドキュメントの貢献ガイドラインでは書いていませんが、あまり入れない形で訳して提供しています。

訳注あると確かに読み手の参考になっていいのですが、なるべく無い形にしたいので、文章に意訳的な形で盛り込む形式にしてもらえると助かります。

どうしても、訳注として残したい場合は、コメントください。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +slot 内の template が、slot の content をレンダリングをする役割を持った子コンポーネントの側の「データ」へ、アクセスできたらいいのに、と思うことはないでしょうか。
slot、template、そして content をそのまま英語のままにしていますが、ここの文章の文脈では、特にそのまま訳しても文章として問題ないので、訳すようお願いします。
ref: 日本語公式ドキュメント
https://jp.vuejs.org/v2/guide/components-slots.html

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +とくにそれが有効なのは、子コンポーネントの data プロパティを使用するカスタム template を作成する必要がある場合です。まさに `scoped slots` を使用するのに最適な場面です。
ここの文章も `template` も同じく、文脈上問題ないので、訳すようお願いします。 🙏

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +外部 API の設定と使用準備をするコンポーネントを実装する場合を想定してみましょう。そのコンポーネントは、他のコンポーネントから使用されるわけですが、具体的な template と密接には結びついません。そのためレンダリングする template が異なる様々な場所で使いまわすことができ、それでいて特定の API を持つ同じベースオブジェクトを使用します。
ここの `template` も上記コメントと同じく、訳すようお願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +3. これら2つの object を `GoogleMapLoader` を使用する親コンポーネントに対して露出させている。
`露出` という `expose` の訳はあまりソフトウェア業界の翻訳用語としてはあまり聞かないので、ここでは `公開` という意訳の方がよいと思います。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +template の中にマップのためのコンテナを作成しましょう。このコンテナへ Google Maps API から抽出した [Map](https://developers.google.com/maps/documentation/javascript/reference/map#Map) がマウントされます。
ここの `template` は、 SFC の template ブロックのことなので、この文章ではこのままででいいですが、注釈しておくと分かりやすいですね。

(そもそも、原文もちょっと分かりづらいですね。。。せめて quote してあると分かりやすいですね。。。余力があれば、本家にPR送ってもいいかもしれません。)

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +次に、親コンポーネントから props を受け取る必要がありますね。この props を使って Google Map を設定します。この props は次の2つから成ります。
突然、ここで `ありますね。` という少し体裁が口語調なのですが、 `あります。` の方が読み手に自然なので、そちらでお願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +(訳注: 作成されたインスタンスというのは GoogleMapLoader コンポーントのことで、このコンポーネントの data の google, map へ値をセットしている)
`コンポーント` 、typo なので修正お願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +ここまでは順調ですね。マップに作るのに必要な全ての作業が終了しましたので、あとはいつも通りに他のオブジェクトをこのマップ（マーカー、ポリラインなど）に追加していば、マップコンポーネントは完成します。
`順調ですね。` 
ここも少しくだけた口語調になっていますが、 `順調です。` でお願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +しかし今回は `GoogleMapLoader` には map オブジェクトを準備する役割「だけ」を与えたいわけですね。つまり、マーカー、ポリラインなど他の要素はこのコンポーネントにはレンダリングさせたくないわけです。
`与えたいわけですね。`
ここも少しくだけた口語調になっていますが、 `与えたいわけです。` でお願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +とくにそれが有効なのは、子コンポーネントの data プロパティを使用するカスタム template を作成する必要がある場合です。まさに `scoped slots` を使用するのに最適な場面です。
`scoped slots` ですが、なるべく日本語公式ドキュメントを一貫性保ちたいので、こちらも `スコープ付きスロット` で訳お願いします。
`スコープ付きスロット (scoped slots)` でも可です。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +そうするためには、`GoogleMapLoader` を使用する親コンポーネント(訳注: 今回の例では `TravelMap`)が、`GoogleMapLoader` の `this.google` と `this.map` にアクセスできるようにしなくてはいけません。こういうときに [scoped slots](https://vuejs.org/v2/guide/components-slo
ここの文章の `scoped slots` の `スコープ付きスロット` でお願いします。
後リンク先も、読み手が英語のリンク先に飛んで困らないためにも、以下日本語公式ドキュメントのリンクでお願いします。
https://jp.vuejs.org/v2/guide/components-slots.html#%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97%E4%BB%98%E3%81%8D%E3%82%B9%E3%83%AD%E3%83%83%E3%83%88

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +そうするためには、`GoogleMapLoader` を使用する親コンポーネント(訳注: 今回の例では `TravelMap`)が、`GoogleMapLoader` の `this.google` と `this.map` にアクセスできるようにしなくてはいけません。こういうときに [scoped slots](https://vuejs.org/v2/guide/components-slo
`露出` も `公開` でお願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +template の中で、`GoogleMapLoader` コンポーネントをレンダーし、さらにこのコンポーネントへ、マップをを初期化するために必要な props を渡します。
`レンダー` は `描画` でお願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +template の中で、`GoogleMapLoader` コンポーネントをレンダーし、さらにこのコンポーネントへ、マップをを初期化するために必要な props を渡します。
`マップをを` typoですね。
`マップを` で修正お願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +このコンポーネントの Script 部分はこうなるでしょう。
`Script 部分` -> `script の部分` でお願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +まだ scoped slot を使っていないので、追加していきましょう。
ここも `scoped slot` -> `スコープ付きスロット` でお願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +### 3. scoped slot を追加して、親コンポーネントへ google と map のプロパティを露出させる
```suggestion
### 3. スコープ付きスロットを追加して、親コンポーネントに google と map プロパティを公開する
```

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +最後に scoped slot を追加して、望む仕事をしてもらうことにしましょう。これによって、親コンポーネントの中から、子コンポーネントのプロパティにアクセすることができるようになります。子コンポーネントの中に `<slot>` タグを追加し、さらに `v-bind` もしくは `:propName` を使って、親コンポーネントへと露出させたい値をプロパティとして渡します。これは通常の pro
ここも `scoped slot` -> `スコープ付きスロット` でお願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +最後に scoped slot を追加して、望む仕事をしてもらうことにしましょう。これによって、親コンポーネントの中から、子コンポーネントのプロパティにアクセすることができるようになります。子コンポーネントの中に `<slot>` タグを追加し、さらに `v-bind` もしくは `:propName` を使って、親コンポーネントへと露出させたい値をプロパティとして渡します。これは通常の pro
ここの `露出` も `公開` でお願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +さて、子コンポーネントに slot を用意しましたので、次にそうやって親コンポーネントへと露出した props を受け取って、それを使うことにしましょう。
```suggestion
さて、子コンポーネントにスロットを用意しましたので、次にそうやって親コンポーネントに公開した props を受け取って、それを使うことにしましょう。
```

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +### 4. `slot-scope` を用いて、露出された props を親コンポーネントで受け取る
```suggestion
### 4. `slot-scope` を用いて、公開された props を親コンポーネントで受け取る
```

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +### 4. `slot-scope` を用いて、露出された props を親コンポーネントで受け取る
ここの `露出` もこのように `公開` でお願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +親コンポーネントで露出された props を受け取るために、temlate 要素を用意して、その要素に `slot-scope` 属性を付与します。この属性の中では、子コンポーネントから露出されている props を全てもったオブジェクトにアクセスすることができます。オブジェクトそれ自体を使用することもできますし、[オブジェクトのプロパティを分割して](https://vuejs.org/v2/
```suggestion
親コンポーネントで公開された props を受け取るために、template 要素を用意して、その要素に `slot-scope` 属性を付与します。この属性の中では、子コンポーネントから公開されている props を全てもったオブジェクトにアクセスすることができます。オブジェクトそれ自体を使用することもできますし、[オブジェクトのプロパティを分割して](https://vuejs.org/v2/guide/components-slots.html#Destructuring-slot-scope) 必要な値だけを受け取ることもできます。
```

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +親コンポーネントで露出された props を受け取るために、temlate 要素を用意して、その要素に `slot-scope` 属性を付与します。この属性の中では、子コンポーネントから露出されている props を全てもったオブジェクトにアクセスすることができます。オブジェクトそれ自体を使用することもできますし、[オブジェクトのプロパティを分割して](https://vuejs.org/v2/
ここの `露出` もこのように `公開` でお願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +こうすることで `google` と `map` というプロパティは `TravelMap` コンポーネントのスコープには存在しないにも関わらず、これにアクセスすることができ、そしてそれを template の中で使用することができます。
```suggestion
こうすることで `google` と `map` というプロパティは `TravelMap` コンポーネントのスコープには存在しないにも関わらず、これにアクセスすることができ、そしてそれを template 要素の中で使用することができます。
```

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +こうすることで `google` と `map` というプロパティは `TravelMap` コンポーネントのスコープには存在しないにも関わらず、これにアクセスすることができ、そしてそれを template の中で使用することができます。
`template 要素` にした方がコードと照らし合わせて理解しすいので、こちらにしましょう！

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +(訳注:次の一文は、翻訳はをしたものの、正確な意味がわかりません。申し訳ない) Scoped slot は、レンダーされた要素ではなく、代わりに template を slot に渡すことができます。`scoped` と呼ばれているのは、これを使うことで子コンポーネントのデータにアクセスでき、それでいて template は親コンポーネントの scope でレンダーされるからです。 これによって
```suggestion
スコープ付きスロットは、描画された要素ではなく、代わりに template 要素をスロットに渡すことができます。`scoped` と呼ばれているのは、これを使うことで子コンポーネントのデータにアクセスでき、それでいて template 要素は親コンポーネントの scope で描画されるからです。 これによって、親コンポーネントからのカスタムコンテンツによるテンプレートで自由に埋め込むことができます。(注意: 2.5 以降では `scope-slot` の対象は template 要素だけでなく、
他の要素にも摘要することができます。)
```

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +(訳注:次の一文は、翻訳はをしたものの、正確な意味がわかりません。申し訳ない) Scoped slot は、レンダーされた要素ではなく、代わりに template を slot に渡すことができます。`scoped` と呼ばれているのは、これを使うことで子コンポーネントのデータにアクセスでき、それでいて template は親コンポーネントの scope でレンダーされるからです。 これによって
`v2.5` 時点では、 scoped slot は `template` 要素だけでなく、 `p` や `span` などの要素にも、子コンポーネントの `slot` タグに設定されたプロパティに `slot-scope` でアクセスできるようになっています。
この cookbook 執筆者は、ひょっとしたらそのことが知らない状態で書いたのかもしれませんね。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
>  ### 5. Create factory components for Markers and Polylines
ここの訳を見つけることができませんでした。漏れているようでしたら、すいませんがお願いします 🙏

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +またどちらのコンポーネントも、要素を作るために必要な追加の props をうけとっています。今回の例では、`GoogleMapMarker` コンポーネントは `marker` を、`GoogleMapLine` コンポーネントは `path` をそれぞれ受け取っていますね。
```suggestion
またどちらのコンポーネントも、要素を作るために必要な追加の props をうけとっています。今回の例では、`GoogleMapMarker` コンポーネントは `marker` を、`GoogleMapLine` コンポーネントは `path` をそれぞれ受け取っています。
```

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +またどちらのコンポーネントも、要素を作るために必要な追加の props をうけとっています。今回の例では、`GoogleMapMarker` コンポーネントは `marker` を、`GoogleMapLine` コンポーネントは `path` をそれぞれ受け取っていますね。
口語調があったので、このように修正お願いします。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +では先ほど作った factory コンポーネントを使うことで、マップに要素を追加させるようにしましょう。そのためには factory コンポーネントをレンダーするわけですが、その際に `google` と `map` の2つのオブジェクトを渡します。そうすることで、このデータが正しいところへと流れていきます。(訳注: つまりそれぞれの factory コンポーネントの必要な場所へ)
```suggestion
では先ほど作ったファクトリーコンポーネントを使うことで、マップに要素を追加させるようにしましょう。そのためにはファクトリーコンポーネントを描画するわけですが、その際に `google` と `map` の2つのオブジェクトを渡します。そうすることで、このデータが正しいところへと流れていきます。(訳注: つまりそれぞれのファクトリーコンポーネントの必要な場所へ)
```

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +さあさあ、これらの値を直接渡していきます。
```suggestion
さて準備ができましたので、これらの値を直接渡していきます。
```

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +さあさあ、これらの値を直接渡していきます。
`Here we go` の意訳として、ゆるすぎず、硬すぎず、こんな感じではいかがでしょうか。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +それから script の中で、factory component を script の中でインポートし、marker と lines という名前でコンポーネントに値をセットします。
```suggestion
それから script の中で、ファクトリーコンポーネントを script の中でインポートし、marker と lines という名前でコンポーネントに値をセットします。
```

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +それから script の中で、factory component を script の中でインポートし、marker と lines という名前でコンポーネントに値をセットします。
factory component の訳、統一するために訳しました。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
>  ## When To Avoid This Pattern
ここの部分、訳漏れているようなので、お願いします！ 🙏

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +このような非常に複雑な解決法は魅力的に思われるかもしれませんが、ある一定のレベルまでその複雑さが進んでしまうと、その抽象性が、この機能を構成する他のコードの部分よりもかなり高くなってしまい、浮いた存在になってしまうでしょう。その段階にまできた場合には、add-on に抽出することを検討する段階でしょう。(訳注: add-on はおそらく、plugin や mixin などのことです)
```suggestion
このような非常に複雑な解決法は魅力的に思われるかもしれませんが、ある一定のレベルまでその複雑さが進んでしまうと、その抽象性が、この機能を構成する他のコードの部分よりもかなり高くなってしまい、浮いた存在になってしまうでしょう。その段階にまできた場合には、プラグインやミックスインのようなアドオンとして抽出することを検討する段階でしょう。
```

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +このような非常に複雑な解決法は魅力的に思われるかもしれませんが、ある一定のレベルまでその複雑さが進んでしまうと、その抽象性が、この機能を構成する他のコードの部分よりもかなり高くなってしまい、浮いた存在になってしまうでしょう。その段階にまできた場合には、add-on に抽出することを検討する段階でしょう。(訳注: add-on はおそらく、plugin や mixin などのことです)
訳注は文章の意訳的に含めてこのように訳した文章にするといいと思います。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +さあ全てやりとげました。こまごまと作業をしてきた結果として `GoogleMapLoader` コンポーネントを、マップを使う際のベースとして使いまわすことができるようになりました。それぞれの用途に合わせた template を渡せばこのコンポーネントに渡せば、どんなものにでも対応できます。例えば今回のケースとは異なるマーカーや、ポリラインがない場合にも使えますね。今回紹介したパターンを使うこと
```suggestion
以上です。こまごまと作業をしてきた結果として `GoogleMapLoader` コンポーネントを、マップを使う際のベースとして使いまわすことができるようになりました。それぞれの用途に合わせたテンプレートをこのコンポーネントに渡せば、どんなものにでも対応できます。例えば今回のケースとは異なるマーカーや、ポリラインがない場合にも使えます。今回紹介したパターンを使うことで `GoogleMapLoader` にケースによってことなる必要なコンテンツを渡すだけで、この目的を達成できます。
```

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +さあ全てやりとげました。こまごまと作業をしてきた結果として `GoogleMapLoader` コンポーネントを、マップを使う際のベースとして使いまわすことができるようになりました。それぞれの用途に合わせた template を渡せばこのコンポーネントに渡せば、どんなものにでも対応できます。例えば今回のケースとは異なるマーカーや、ポリラインがない場合にも使えますね。今回紹介したパターンを使うこと
`That's it`  ですが、`以上です。` のような方が、硬すぎず、ゆるすぎず、読みてにはちょうどいいです。

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +このパターンは Google Map の場合にしか使えないわけではありません。どんなライブラリの場合にも、ベースとなるコンポーネントをセットして、(ベースコンポーネントを呼び出したコンポーネントが実行する) API を露出させればいいのです。
```suggestion
このパターンは Google Map の場合にしか使えないわけではありません。どんなライブラリの場合にも、ベースとなるコンポーネントをセットして、(ベースコンポーネントを呼び出したコンポーネントが実行する) API を公開させればいいのです。
```

2019-01-01 18:45 UTC, kazupon commented on src/v2/cookbook/practical-use-of-scoped-slots.md
> +このパターンは Google Map の場合にしか使えないわけではありません。どんなライブラリの場合にも、ベースとなるコンポーネントをセットして、(ベースコンポーネントを呼び出したコンポーネントが実行する) API を露出させればいいのです。
ここの `露出` も `公開` でお願いします。

2019-01-11 04:24 UTC, potato4d commented
@superyusuke
こちらいかがでしょうか？もし忙しいようであれば、連休中に引き継いでやることも可能なので、ご連絡いただければと思います。
もちろん、引き続き対応してもらう形でも大丈夫です！

2019-01-11 09:09 UTC, superyusuke commented
@potato4d 
連絡遅くなり申し訳ありません…
訳注をいれずに文章に入れるというのが少し難しく、できれば引き継いでいただけると助かります。

2019-01-25 04:36 UTC, potato4d commented
@superyusuke 
遅くなりました。引き継ぎますー。

2019-02-18 14:46 UTC, potato4d commented
この PR のまま引き継ぐのがちょっとコスト的に高いので別途 PR を出します 🙇

2019-02-18 14:46 UTC, closed without merging