Translate 1580, 1587, 1588
vuejs/jp.vuejs.org pull request #1593
Opened 2019-03-29 14:51 UTC by oohira

## 概要

* resolve #1580 
* resolve #1587  
* resolve #1588 

## 補足

* cherry-pick & translate vuejs/vuejs.org@1367e20
* cherry-pick & translate vuejs/vuejs.org@f1d244b
* cherry-pick & translate vuejs/vuejs.org@abf9cda

2019-03-30 13:15 UTC, kazupon requested changes

2019-03-30 13:15 UTC, kazupon commented on src/v2/api/index.md
> +    - `type`: 次のネイティブコンストラクタのいずれかです: `String`, `Number`, `Boolean`, `Array`, `Object`, `Date`, `Function`, `Symbol`, カスタムコンストラクタ関数、またはそれらの配列。プロパティが指定された型かチェックし、そうでなければ警告を出します。プロパティの型に関する [詳細](../guid
`type` 、 `default`、 `required` 、そして `validator` も一応訳して頂けますか？
APIの部分で似たような部分、これまでに訳しているので、一貫性を取るために訳しておきたいです。
(`validator` は日本語訳は一般的にないので、`バリデーター` でいいと思います。)

2019-03-31 10:12 UTC, potato4d commented on src/v2/api/index.md
> +    - `type`: 次のネイティブコンストラクタのいずれかです: `String`, `Number`, `Boolean`, `Array`, `Object`, `Date`, `Function`, `Symbol`, カスタムコンストラクタ関数、またはそれらの配列。プロパティが指定された型かチェックし、そうでなければ警告を出します。プロパティの型に関する [詳細](../guid
@kazupon 
[imo] `validator` の日本語訳ですが、grep してみたら「バリデータ」と訳されたあとがあるみたいなので、「バリデータ」で良さそうではないでしょうか〜。

https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/src/v2/guide/migration.md#two-way-%E3%83%95%E3%82%A3%E3%83%AB%E3%82%BF-%E7%BD%AE%E3%81%8D%E6%8F%9B%E3%81%88

2019-03-31 11:48 UTC, oohira commented on src/v2/api/index.md
> +    - `type`: 次のネイティブコンストラクタのいずれかです: `String`, `Number`, `Boolean`, `Array`, `Object`, `Date`, `Function`, `Symbol`, カスタムコンストラクタ関数、またはそれらの配列。プロパティが指定された型かチェックし、そうでなければ警告を出します。プロパティの型に関する [詳細](../guid
レビューありがとうございます。原文の修正は、これらがpropsの名前だから太字ではなくコード例としてバッククォートで囲むべき、という意図だと思っています。コードとして使う名前という解釈だと訳さない方がよいと思いますが、訳した方がよさそうでしょうか？

2019-03-31 14:26 UTC, kazupon commented on src/v2/api/index.md
> +    - `type`: 次のネイティブコンストラクタのいずれかです: `String`, `Number`, `Boolean`, `Array`, `Object`, `Date`, `Function`, `Symbol`, カスタムコンストラクタ関数、またはそれらの配列。プロパティが指定された型かチェックし、そうでなければ警告を出します。プロパティの型に関する [詳細](../guid
>原文の修正は、これらがpropsの名前だから太字ではなくコード例としてバッククォートで囲むべき、という意図だと思っています。

確かに、原文の修正よく見ていると、確かにpropsのコードに対応しているので、ここは訳さなくていいですね。

バッククォートで囲ったままで良さそうです。

2019-03-31 14:26 UTC, kazupon approved these changes

2019-04-01 08:34 UTC, potato4d approved these changes

2019-04-01 08:34 UTC, merged