Translate list rendering
vuejs/jp.vuejs.org pull request #164
Opened 2016-09-28 08:54 UTC by nakajmg

Closes #133

[リストレンダリング](http://rc.vuejs.org/guide/list.html) を翻訳しました。
レビューお願いします🙋

2016-09-29 01:46 UTC, kazupon requested changes
レビュー 👀 しました。レビューコメント内容の対応お願いします！

2016-09-29 01:46 UTC, kazupon commented on src/guide/list.md
> +あなたはまた、区切り文字として `in` の代わりに `of` を使用することができます。これはJavaScriptのイテレータ構文に近いものです:
`これはJavaScriptのイテレータ構文` ですが、スペース入れて下記のようにお願いします。
`これは JavaScript のイテレータ構文`

2016-09-29 01:46 UTC, kazupon commented on src/guide/list.md
> +2つ目の引数としてキーに対して英シリアスも提供できます:
`2 つ目の引数としてキーも提供することができます:` の訳でいきましょう！

2016-09-29 01:46 UTC, kazupon commented on src/guide/list.md
>  ```
上にある `And another for the index:` の訳漏れありました。

2016-09-29 01:46 UTC, kazupon commented on src/guide/list.md
> +> このセクションでは、[コンポーネント](/guide/components.html)についての知識を取り上げます。遠慮なく飛ばして、後で戻ってきてください。
`このセクションでは、[コンポーネント](/guide/components.html)についての知識を取り上げます。遠慮なく飛ばして、後で戻ってきてください。`

この部分の訳ですが、ちょっと原文にニュアンスを加えていますが、下記のような訳でいきましょう！

`このセクションでは、[コンポーネント](/guide/components.html)についての知識を前提としています。もし分からなければ、このセクションを遠慮なく飛ばして、理解した後に戻ってきてください。`

2016-09-29 01:46 UTC, kazupon commented on src/guide/list.md
> +これは、単純なToDoリストの完全な例です:
半角スペースいれましょう！

- before: `単純なToDoリスト`
- after: `単純な ToDo リスト`

2016-09-29 01:46 UTC, kazupon commented on src/guide/list.md
> +Vue が `v-for` でレンダリングされた要素のリストを更新する際、標準では "in-place patch" 戦略が用いられます。もしデータのアイテムの順番が変更されたら、代わりにDOM要素を項目の順序と一致するように移動させます。Vue は全ての要素に単純にその場でパッチして、特定のインデックスでレンダリングされるかが反映されたのを確認します。これは Vue 1.x にあった機能の `
`in-place patch` ですが、この訳 `配置されたパッチ (in-palce patch)` のように、訳と原文と入れた形でいきましょう！
`in-place` 調べた感じですと、`配置済み` 、`整っている` という意味のようです

2016-09-29 01:46 UTC, kazupon commented on src/guide/list.md
> +Vue が `v-for` でレンダリングされた要素のリストを更新する際、標準では "in-place patch" 戦略が用いられます。もしデータのアイテムの順番が変更されたら、代わりにDOM要素を項目の順序と一致するように移動させます。Vue は全ての要素に単純にその場でパッチして、特定のインデックスでレンダリングされるかが反映されたのを確認します。これは Vue 1.x にあった機能の `
`代わりにDOM要素` に半角スペースいれて、`代わりに DOM 要素` にしましょう！

2016-09-29 01:46 UTC, kazupon commented on src/guide/list.md
> +この標準のモードは効率がいいです。しかしこれは、**レンダリングされたリストが子コンポーネントの状態や、一時的なDOMの状態に依存していないときにだけ適しています (例: フォームのインプットの値)**。
ここの`DOM` という部分も同様に前後に半角スペースいれましょう！

2016-09-29 01:46 UTC, kazupon commented on src/guide/list.md
> +繰り返されるDOMの内容が単純でない限り、またはあなたがパフォーマンスの向上を標準の動作に意図的に頼っていない限り、可能なときはいつでも `v-for` に `key` を与えることが推奨されます。
ここのDOMも同様に半角スペースですね。

2016-10-05 04:35 UTC, nakajmg reviewed
Reviewの機能の使い方把握できてなく、全部 `pending` になってました 😂
コメント入れてるところのチェックお願いします 🙏 🙏 🙏

2016-10-05 04:35 UTC, nakajmg commented on src/guide/list.md
>  ## key
この `##key` の部分、あまり自信がない部分があるので見てもらえますでしょうか 🙏

2016-10-05 04:35 UTC, nakajmg commented on src/guide/list.md
> +Vue が `v-for` でレンダリングされた要素のリストを更新する際、標準では "in-place patch" 戦略が用いられます。もしデータのアイテムの順番が変更されたら、代わりにDOM要素を項目の順序と一致するように移動させます。Vue は全ての要素に単純にその場でパッチして、特定のインデックスでレンダリングされるかが反映されたのを確認します。これは Vue 1.x にあった機能の `
"in-place patch" はそのままで大丈夫でしょうか？

2016-10-05 04:35 UTC, nakajmg commented on src/guide/list.md
> +Vue が `v-for` でレンダリングされた要素のリストを更新する際、標準では "in-place patch" 戦略が用いられます。もしデータのアイテムの順番が変更されたら、代わりにDOM要素を項目の順序と一致するように移動させます。Vue は全ての要素に単純にその場でパッチして、特定のインデックスでレンダリングされるかが反映されたのを確認します。これは Vue 1.x にあった機能の `
> Vue will simply patch each element in-place and make sure it reflects what should be rendered at that particular index.

ここの訳、日本語的に難しい感じになっております…😰

2016-10-05 04:35 UTC, nakajmg commented on src/guide/list.md
> -Since it's a generic mechanism for Vue to identify nodes, the `key` also has other uses that are not specifically tied to `v-for`, as we will see later in the guide.
> Since it's a generic mechanism for Vue to identify nodes,

ここの `it's` が何を指してるか読み取りきれませんでした。

"it's ~ to  ~ for" な構文を素直に訳すと 「Vueがノードを識別するのは汎用的な仕組みなので」になるのかなと思ったのですが、`it's` が `v-for` と `key` を組み合わせて使うことを指してると読み取って訳しました💁🏻

2016-10-05 04:35 UTC, nakajmg commented on src/guide/list.md
> +繰り返されるDOMの内容が単純でない限り、またはあなたがパフォーマンスの向上を標準の動作に意図的に頼っていない限り、可能なときはいつでも `v-for` に `key` を与えることが推奨されます。
原文の

> It is recommended to provide a `key` with `v-for` whenever possible, 

を訳では最後に持ってきてるのですが、ガイドライン的には最初に持ってきたほうがよい、といったことはありますか？であれば👇のような感じになるかなと思います。

> 可能なときはいつでも `v-for` に `key` を与えることが推奨されます。繰り返されるDOMの内容が単純でない限り、またはあなたがパフォーマンスの向上を標準の動作に意図的に頼っていない限りは。

2016-10-05 04:35 UTC, nakajmg commented on src/guide/list.md
> +Vue が `v-for` でレンダリングされた要素のリストを更新する際、標準では "in-place patch" 戦略が用いられます。もしデータのアイテムの順番が変更されたら、代わりにDOM要素を項目の順序と一致するように移動させます。Vue は全ての要素に単純にその場でパッチして、特定のインデックスでレンダリングされるかが反映されたのを確認します。これは Vue 1.x にあった機能の `
`in-place` 、プログラム的には `その場で〜` というニュアンスかと思っていたのですが

> 配置済み 、整っている

という訳にすると以下の文はどう訳せばよさそうでしょうか？

> Vue will simply patch each element in-place

2016-10-05 08:02 UTC, kazupon commented on src/guide/list.md
> +Vue が `v-for` でレンダリングされた要素のリストを更新する際、標準では "in-place patch" 戦略が用いられます。もしデータのアイテムの順番が変更されたら、代わりにDOM要素を項目の順序と一致するように移動させます。Vue は全ての要素に単純にその場でパッチして、特定のインデックスでレンダリングされるかが反映されたのを確認します。これは Vue 1.x にあった機能の `
なるほど。`in-place` の訳、`その場で〜`の方がしっくり来ますね！
そうなると、`in-place patch` は `その場でパッチを適用する` という訳になっていいですね！ 😉

2016-10-05 08:08 UTC, kazupon commented on src/guide/list.md
> +Vue が `v-for` でレンダリングされた要素のリストを更新する際、標準では "in-place patch" 戦略が用いられます。もしデータのアイテムの順番が変更されたら、代わりにDOM要素を項目の順序と一致するように移動させます。Vue は全ての要素に単純にその場でパッチして、特定のインデックスでレンダリングされるかが反映されたのを確認します。これは Vue 1.x にあった機能の `
> Vue will simply patch each element in-place

ですが、以下でいかがでしょうか？

`Vue は単純に各要素にその場でパッチを適用して`

2016-10-05 08:14 UTC, kazupon commented on src/guide/list.md
> +繰り返されるDOMの内容が単純でない限り、またはあなたがパフォーマンスの向上を標準の動作に意図的に頼っていない限り、可能なときはいつでも `v-for` に `key` を与えることが推奨されます。
ガイドラインが曖昧で申し訳ないです。 :bow:
読みやすさ、理解しやすさを優先したいので、最初にもってきても大丈夫です。 🙆 
以下でどうでしょう？

> 可能なときはいつでも `v-for` に `key` を与えることが推奨されます。これは、繰り返される DOM の内容が単純でない、またはあなたがパフォーマンスの向上を標準の動作に意図的に頼っていない場合に限ります。

2016-10-05 08:17 UTC, kazupon requested changes
すいません、GitHub の新しい Review 機能でコメントしたら、よく分からない酷い状態になってしまいました。。。 😭 

とりあえず、一旦レビューコメント内容を commit お願いします :bow:

2016-10-05 08:59 UTC, nakajmg commented
レビューを反映してcommitしました 🙏

2016-10-05 09:53 UTC, kazupon requested changes
再レビュー 👀 しました。再度お願いします！ 🙏

2016-10-05 09:53 UTC, kazupon commented on src/guide/list.md
> +Vue が `v-for` でレンダリングされた要素のリストを更新する際、標準では "その場でパッチを適用する" (in-place patch) 戦略が用いられます。もしデータのアイテムの順番が変更されたら、代わりに DOM 要素を項目の順序と一致するように移動させます。Vue は各要素にその場でパッチを適用して、特定のインデックスでレンダリングされるかが反映されたのを確認します。これは Vu
`Vue は各要素にその場でパッチを適用して、特定のインデックスでレンダリングされるかが反映されたのを確認します。` の訳の部分ですが、Vue 2.0 の virtual-dom のpatch の動きをふまえると、以下の訳になるかと思います。

`Vue は各要素にその場でパッチを適用して、その特定のインデックスでレンダリングされる必要があるのかどうか、それを反映するのを確認します。`

2016-10-05 09:53 UTC, kazupon commented on src/guide/list.md
> +可能なときはいつでも `v-for` に `key` を与えることが推奨されます。これは、繰り返される DOM の内容が単純でない、またはあなたがパフォーマンスの工場を標準の動作に意図的に頼っていない場合に限ります。
typo ありました。

`工場` -> `向上`

2016-10-13 09:45 UTC, nakajmg commented
レビュー反映しました 🙏 🙏 🙏

2016-10-13 10:04 UTC, kazupon approved these changes
👍 
ありがとうございました！
マージしますね！

2016-10-13 10:04 UTC, merged