"Unit Testing" の翻訳 #147
vuejs/jp.vuejs.org pull request #166
Opened 2016-09-28 11:33 UTC by mikakane

ご確認よろしくお願いいたします

2016-09-29 02:48 UTC, kazupon requested changes
レビュー 👀 しました！レビューコメントの対応お願いします！

2016-09-29 02:48 UTC, kazupon commented on src/guide/unit-testing.md
> +テストツールは、モジュールベースのビルドシステムで動作するものならどのようなものでも問題ありませんが、テストツールをお探しの場合、[Karma](http://karma-runner.github.io/0.12/index.html) を試してみて下さい。 Karma には多くのコミュニティ製プラグインが存在し、[Webpack](https://github.com/webpack/kar
謙譲語で訳さなくても大丈夫です。:)
`お探しの場合` は `探している場合` にしましょう！

2016-09-29 02:48 UTC, kazupon commented on src/guide/unit-testing.md
> +テストツールは、モジュールベースのビルドシステムで動作するものならどのようなものでも問題ありませんが、テストツールをお探しの場合、[Karma](http://karma-runner.github.io/0.12/index.html) を試してみて下さい。 Karma には多くのコミュニティ製プラグインが存在し、[Webpack](https://github.com/webpack/kar
edit miss だと思いますが、 `[ Karma]` のように半角スペースがはいっています。

2016-09-29 02:48 UTC, kazupon commented on src/guide/unit-testing.md
>  ## Simple Assertions
タイトルも訳しましょう！ :)

2016-09-29 02:48 UTC, kazupon commented on src/guide/unit-testing.md
> +テスト設計の観点から、コンポーネントのテスタビリティを向上させるためにコンポーネント内で特別な何かを行う必要はありません。単純に options を export するだけで構いません。
`単純に options を export するだけです。`  でも伝わるので `構いません` はいらないので抜きましょう！

2016-09-29 02:48 UTC, kazupon commented on src/guide/unit-testing.md
> +// Vue と テスト対象の component を import する
`component` と `import` はカタカナで訳しても伝わるので、それでいきましょう！

2016-09-29 02:48 UTC, kazupon commented on src/guide/unit-testing.md
> +//　ここでは Jasmine 2.0 をもちいたテスト記述を行っています。
`もちいた` は `用いた` にしましょう！漢字の方が理解しやすいので。

2016-09-29 02:48 UTC, kazupon commented on src/guide/unit-testing.md
> +コンポーネントをテストする際には、 Vue と合わせて options のオブジェクトを import し、検証を実施します。
`import` はカタカナ訳にしましょう！

2016-09-29 02:48 UTC, kazupon commented on src/guide/unit-testing.md
> +  // コンポーネントの　options 内にある関数を実行し、
`コンポーネントの　options` ですが、余分は半角スペースは削除しましょう！

2016-09-29 02:48 UTC, kazupon commented on src/guide/unit-testing.md
> +// state の更新後、生成されたHTMLの検証を行う
半角スペースいれましょう！

- before: `生成されたHTMLの検証`
- after: `生成された HTML の検証`

2016-09-29 02:48 UTC, kazupon commented on src/guide/unit-testing.md
> +  // state変更後、DOMが更新されるまでの "tick"で待機する
ここも同じくは半角スペースいれましょう！

- before: `state変更後、DOMが更新されるまでの "tick"で待機する`
- after: `state 変更後、DOM が更新されるまでの "tick" で待機する

2016-09-29 02:48 UTC, kazupon commented on src/guide/unit-testing.md
> +コンポーネントを特別な状態で描画し検証する(例えば、子コンポーネントを無視した浅い描画など)ような、テストをより簡単にするためのヘルパーセットの開発も検討しています。
ここは主語`私たちは`文脈上いれましょう！
これより前にはテストのやり方について説明でしたが、ここで内容が変わるので。

2016-09-29 03:39 UTC, mikakane commented
@kazupon 確認ありがとうございます！
指摘頂いた点+αで修正を加えましたのでご確認お願いします！

2016-09-29 07:14 UTC, kazupon commented on src/guide/unit-testing.md
> +テストツールは、モジュールベースのビルドシステムで動作するものならどのようなものでも問題ありませんが、テストツールをお探しの場合、[Karma](http://karma-runner.github.io/0.12/index.html) を試してみて下さい。 Karma には多くのコミュニティ製プラグインが存在し、[Webpack](https://github.com/webpack/kar
上記の半角スペースの件、まだ修正されていないようなので、お願いします！

2016-09-29 07:14 UTC, kazupon commented on src/guide/unit-testing.md
> +// Vue と テスト対象の component を import する
後、上記の部分もですね。

2016-09-29 07:16 UTC, kazupon requested changes
下記コメントの部分もお願いします！
https://github.com/vuejs/jp.vuejs.org/pull/166#discussion_r81076828
https://github.com/vuejs/jp.vuejs.org/pull/166#discussion_r81076787

2016-09-30 01:27 UTC, mikakane commented
@kazupon すみません。修正漏れ対応しました。
半角スペースの件、ちょっとわからなかったのですが []() の前後のスペースを取り除くという事で問題なかったですか？

2016-09-30 01:45 UTC, kazupon commented
たびたび、ありがとうございます！
半角スペースの件説明不足ですいません 🙇 
下記画像の部分です。

<img width="283" alt="hankaku" src="https://cloud.githubusercontent.com/assets/72989/18978132/f2d56144-86fa-11e6-9802-731d36e0cbbb.png">

2016-10-01 05:47 UTC, mikakane commented
@kazupon 
すみません。どういう現象かよく分からず困惑しているのですが,
https://github.com/vuejs/jp.vuejs.org/pull/166/files
のページ Safariで見た際には ご指摘のスペース確認出来るのですが、
Chrome Mac やFirefoxでは確認できませんでした。

なお該当のファイルをRawでみた場合は、どのブラウザでもスペースは確認できませんでした。
https://raw.githubusercontent.com/mikakane/jp.vuejs.org/821c66ab68c561a0e38f2efd5d141c2e6a057bc3/src/guide/unit-testing.md

エディタ上もスペースなしの状態でdiff検出なしとなっていて、
修正どのような形で加えれば…と若干悩んでいます。

2016-10-01 05:51 UTC, mikakane commented
@kazupon 文字をドラッグしてみた所、Safari特有の謎パティングなのでは？と若干思ったりもしています。
![2016-10-01 14 50 30](https://cloud.githubusercontent.com/assets/1859101/19012113/86488a64-87e6-11e6-852b-0532b472de52.png)

2016-10-01 08:29 UTC, kazupon commented
確かに Safari で起きてますね。。。
Chrom や、 ファイル を raw で見たところ、こちらでもスペースがないこと確認しました。
なぞですね。。。Safari 、というより GitHub の viewer の問題かもしれませんね。

この問題に時間を浪費するのはもったいないので、
マージしますね。

2016-10-01 08:29 UTC, kazupon approved these changes

2016-10-01 08:29 UTC, merged