[WIP] Translate Single File Components
vuejs/jp.vuejs.org pull request #168
Opened 2016-09-28 15:43 UTC by hypermkt

Closes https://github.com/vuejs/jp.vuejs.org/issues/144

2016-10-04 12:24 UTC, hypermkt commented
textlintで警告なしを確認

2016-10-04 12:25 UTC, hypermkt reviewed
自己レビューコメントを追加

2016-10-04 12:25 UTC, hypermkt commented on src/guide/single-file-components.md
> +多くの Vue プロジェクトでは、グローバルコンポーネントは各ページの本体でコンテナー要素を参照した `new Vue({ el: '#container '})` に沿って宣言されたのを使用します。
ここの翻訳が意味が通るか不安です。

2016-10-04 12:25 UTC, hypermkt commented on src/guide/single-file-components.md
> +- あなたのバンドルに [envify](https://github.com/hughsk/envify) グローバル変換を適用してください。 これは minifier で Vue ソースコード内で環境変数の条件上で囲われた箇所全てを取り除くことを許可します。
minifierは翻訳できなかったのでそのままとしました

2016-10-04 12:28 UTC, hypermkt commented on src/guide/single-file-components.md
> +- **CSS サポート無し**だと、 HTML と JavaScript がコンポーネントにモジュール化されている間、これ見よがしに無視されます
上記２行の翻訳も不安です。

2016-10-04 12:28 UTC, hypermkt commented
@kazupon 
翻訳が完了しましたのでお手すきの時にレビューお願いします。翻訳が不安な箇所に自己コメントを追加しました。

2016-10-04 15:49 UTC, kazupon requested changes
レビュー 👀 しました！レビューコメントの対応お願いします！

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +多くの Vue プロジェクトでは、グローバルコンポーネントは各ページの本体でコンテナー要素を参照した `new Vue({ el: '#container '})` に沿って宣言されたのを使用します。
ここの訳ですが、以下な感じでどうでしょうか。

```
多くの Vue プロジェクトでは、グローバルコンポーネントは、`new Vue({ el: '#container '})` の後に各ページの body においてコンテナ要素をターゲットにすることに続いて、`Vue.component` を使用して定義されています。
```

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +これはビューを拡張するだけに利用された小さな中規模プロジェクトにおいてはとても有効です。 あなたのフロントエンドで JavaScript 全体を操作するようなもっと複雑なプロジェクトでは、これらの点において不利益になることは明白です。:
`ビュー` ですが、他のセクションの部分で、`view` としているのでこれに統一とさせてください。

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +これはビューを拡張するだけに利用された小さな中規模プロジェクトにおいてはとても有効です。 あなたのフロントエンドで JavaScript 全体を操作するようなもっと複雑なプロジェクトでは、これらの点において不利益になることは明白です。:
以降では列挙しますが、`〜すること`という文体にした方が、文脈的に分かりやすいです。

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +- **グローバル宣言**は全てのコンポーネントにユニークな名前を強制します
`**グローバル宣言**は全てのコンポーネントにユニークな名前を強制すること`

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +- シンタックスハイライトの無い**文字列テンプレート**と複数行 HTML 時に醜いスラッシュが強要されます
`シンタックスハイライトの無い**文字列テンプレート**と複数行 HTML の時に醜いスラッシュが強要されること`

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +- **CSS サポート無し**だと、 HTML と JavaScript がコンポーネントにモジュール化されている間、これ見よがしに無視されます
`**CSS サポート無し**だと、 HTML と JavaScript がコンポーネントにモジュール化されている間、これ見よがしに無視されること`

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +- **ビルドステップ無し**だと Pug(前 Jade) や Babel のようなプリプロセッサよりむしろ、 HTML や ES5 JavaScript を制限します
`**ビルド処理がない**と Pug(前 Jade) や Babel のようなプリプロセッサよりむしろ、 HTML や ES5 JavaScript を制限されること`

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +title: シングルファイル・コンポーネント
`シングルファイル・コンポーネント`ですが、`単一ファイルコンポーネント`の訳にしましょう！

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +これら全ては Webpack や Browserify のビルドツールにより実現された `.vue` 拡張子の **シングルファイル・コンポーネント** で解決します。
ここも`単一ファイルコンポーネント`でお願いします。

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +こちらが `Hello.vue` と呼ばれたファイルのシンプルな例です:
`シンプル` も `単純` に一応訳しましょう！

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +約束したとおり、 Jade 、 Babel(ES2015 モジュールと一緒に）や Stylus などより美しくかつ機能が豊富なコンポーネントもプリプロセッサとして利用できます。
`Jade` 、原文が `Pug` と統一できてないですね。。。
翻訳の方は、`Pug` にしましょう！

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +## 紹介
ここのタイトルですが、セクションの全体の流れからすると導入部分なので、`はじめに` または、`まえがき` のような訳の方がいいですね！

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +## はじめに
ここも文脈的にタイトルの翻訳として、`はじめる` という訳の方がいい感じがします！

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +これらのリソースに飛び込んだ後は、 [webpack-simple](https://github.com/vuejs-templates/webpack-simple) テンプレートを確認することをオススメします。手順に沿って学習することで、あっという間に ES2015 とホットリローディングで動作した `.vue` コンポーネントの Vue プロジェクトを持っているはずです！
`dive into` のここでの訳は、`没頭する` または `のめり込む` 的な訳の方がいいと思います。

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +Webpack でバンドルの中に含まれる前にそれぞれのモジュールは "loader" により変換されます。また Vue では `.vue` シングルファイル・コンポーネントを翻訳するために [vue-loader](https://github.com/vuejs/vue-loader) を推奨しています。 [webpack-simple](https://github.com/vuejs-te
ここも`単一ファイルコンポーネント`でオネガイします。

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +Webpack でバンドルの中に含まれる前にそれぞれのモジュールは "loader" により変換されます。また Vue では `.vue` シングルファイル・コンポーネントを翻訳するために [vue-loader](https://github.com/vuejs/vue-loader) を推奨しています。 [webpack-simple](https://github.com/vuejs-te
translating、これ素朴に訳すと `翻訳` になりますが、実際にはコンパイルと等価なので、`コンパイル`で訳しましょう!

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +Webpack の [DefinePlugin](http://webpack.github.io/docs/list-of-plugins.html#defineplugin) を使用して本番環境を指定ください。そうすると UglifyJS が圧縮・縮小化時に自動的に警告部を切り落としてくれます。 以下はコンフィグ例です:
ここでは、`コンフィグ` は `設定` で訳しましょう!

2016-10-04 15:49 UTC, kazupon commented on src/guide/single-file-components.md
> +- あなたのバンドルに [envify](https://github.com/hughsk/envify) グローバル変換を適用してください。 これは minifier で Vue ソースコード内で環境変数の条件上で囲われた箇所全てを取り除くことを許可します。
そのままで大丈夫です。:)

2016-10-04 23:26 UTC, hypermkt commented
レビューありがとうございます！指摘いただいた箇所を修正します！

2016-10-05 15:49 UTC, hypermkt commented on src/guide/single-file-components.md
> +title: シングルファイル・コンポーネント
了解です！

2016-10-05 15:56 UTC, hypermkt commented on src/guide/single-file-components.md
> +## 紹介
確かに自分でも違和感を感じていました。`前書き` にします！

2016-10-05 15:56 UTC, hypermkt commented on src/guide/single-file-components.md
> +これら全ては Webpack や Browserify のビルドツールにより実現された `.vue` 拡張子の **シングルファイル・コンポーネント** で解決します。
了解です！

2016-10-06 13:04 UTC, hypermkt commented on src/guide/single-file-components.md
> +- あなたのバンドルに [envify](https://github.com/hughsk/envify) グローバル変換を適用してください。 これは minifier で Vue ソースコード内で環境変数の条件上で囲われた箇所全てを取り除くことを許可します。
了解です！

2016-10-06 13:08 UTC, hypermkt commented on src/guide/single-file-components.md
> +約束したとおり、 Jade 、 Babel(ES2015 モジュールと一緒に）や Stylus などより美しくかつ機能が豊富なコンポーネントもプリプロセッサとして利用できます。
なるほど、名前変更があったんですね・・・。了解です！
https://github.com/pugjs/pug/issues/2184

2016-10-06 13:09 UTC, hypermkt commented on src/guide/single-file-components.md
> +これらのリソースに飛び込んだ後は、 [webpack-simple](https://github.com/vuejs-templates/webpack-simple) テンプレートを確認することをオススメします。手順に沿って学習することで、あっという間に ES2015 とホットリローディングで動作した `.vue` コンポーネントの Vue プロジェクトを持っているはずです！
確かに `没頭する` の方が自然ですね。

2016-10-06 13:13 UTC, hypermkt commented on src/guide/single-file-components.md
> +これはビューを拡張するだけに利用された小さな中規模プロジェクトにおいてはとても有効です。 あなたのフロントエンドで JavaScript 全体を操作するようなもっと複雑なプロジェクトでは、これらの点において不利益になることは明白です。:
`view` で統一します。

2016-10-06 13:15 UTC, hypermkt commented on src/guide/single-file-components.md
> +Webpack の [DefinePlugin](http://webpack.github.io/docs/list-of-plugins.html#defineplugin) を使用して本番環境を指定ください。そうすると UglifyJS が圧縮・縮小化時に自動的に警告部を切り落としてくれます。 以下はコンフィグ例です:
了解です！

2016-10-06 13:20 UTC, hypermkt commented
@kazupon レビュー頂いた箇所の修正が完了しましたので再度ご確認お願いします！

2016-10-06 15:44 UTC, kazupon approved these changes
👍 
ありがとうございました！
🙆 です。
マージしますね！

2016-10-06 15:44 UTC, merged

2016-10-06 15:45 UTC, hypermkt commented
ご確認ありがとうございます！