Translate events
vuejs/jp.vuejs.org pull request #169
Opened 2016-09-29 09:38 UTC by kitak

Closes https://github.com/vuejs/jp.vuejs.org/issues/134

"Event Handling"のドキュメントを翻訳しました。レビューをお願いします。

2016-09-29 09:55 UTC, kazupon requested changes
レビュー 👀 しました。レビューコメント対応お願いします！

2016-09-29 09:55 UTC, kazupon commented on src/guide/events.md
> +多くのイベントハンドラのロジックはよく複雑になっていくので、`v-on` 属性の値に JavaScript 式を記述し続けるのは現実的ではありません。そのため、`v-on` は他にも呼び出したいメソッドの名前を受け付けます。
`よく複雑` という訳より、 `より複雑` の方が文脈上しっくりきますね。

2016-09-30 00:16 UTC, kitak commented on src/guide/events.md
> +多くのイベントハンドラのロジックはよく複雑になっていくので、`v-on` 属性の値に JavaScript 式を記述し続けるのは現実的ではありません。そのため、`v-on` は他にも呼び出したいメソッドの名前を受け付けます。
👍

2016-09-30 00:16 UTC, kitak commented
@kazupon 

レビューしていただいた点を修正しました。

2016-09-30 04:23 UTC, kazupon approved these changes
👍 
マージします！

2016-09-30 04:24 UTC, merged