Traslate "Render Functions"
vuejs/jp.vuejs.org pull request #170
Opened 2016-10-01 04:15 UTC by tejitak

I translated the section "render function" #139 
@kazupon Could you please review it?

2016-10-01 09:49 UTC, kazupon requested changes
レビュー  👀 しました。確認お願いします。

2016-10-01 09:49 UTC, kazupon commented on src/guide/render-function.md
> +私たちが先ほど作成したアンカーヘッダコンポーネントは比較的シンプルです。ステートの管理や渡されたステートの watch をしておらず、また、何もライフサイクルメソッドを持ちません。実際、これはいくつかのプロパティを持つただの関数です。
`ステート`ですが、これでも普段使っているので通じるかと思いますが、一応 `状態` で訳しましょう！
他の部分もお願いします！

2016-10-01 09:49 UTC, kazupon commented on src/guide/render-function.md
> +このようなケースにおいて、私たちは `関数型` としてのコンポーネントと特徴づけることができます。それはステートレス ( `data` が無い)でインスタンスレス ( `this` のコンテキストが無い) を意味します。**関数型コンポーネント** は次のような形式をしています。
`ステートレス` は `状態が持たない` にしましょう！

2016-10-01 09:49 UTC, kazupon commented on src/guide/render-function.md
> +このようなケースにおいて、私たちは `関数型` としてのコンポーネントと特徴づけることができます。それはステートレス ( `data` が無い)でインスタンスレス ( `this` のコンテキストが無い) を意味します。**関数型コンポーネント** は次のような形式をしています。
同じく、`インスタンスレス` は `インスタンスを持たない` にしましょう！

2016-10-01 09:49 UTC, kazupon commented on src/guide/render-function.md
> +こちらが、渡されるプロパティに応じてより具体的なコンポーネントにデリゲートする `smart-list` コンポーネントの例です。
`デリゲート` は `委譲` で行きましょう！

2016-10-01 09:49 UTC, kazupon commented on src/guide/render-function.md
> +もしかするとあなたは Vue のテンプレートが実際に render 関数にコンパイルされることを知ることに興味を持つかもしれません。これは普段あなたは知る必要もない実装の詳細ですが、どのように特定のテンプレート機能がコンパイルされるかをもし見たいならこれに興味を持つかもしれません。以下は `Vue.compile` を使ってテンプレート文字列のライブコンパイルをするちょっとしたデモです。
`ライブコンパイル` ですが `その場でコンパイル` の方が分かりやすいような感じがします。

2016-10-01 11:46 UTC, tejitak commented
@kazupon レビューしていただきありがとうございます!! fixしました。

2016-10-02 13:37 UTC, kazupon approved these changes
ありがとうございます！OKです！

2016-10-02 13:38 UTC, merged