Fix1729
vuejs/jp.vuejs.org pull request #1735
Opened 2019-07-01 13:40 UTC by syagawa

## 概要

resolve #1729

2019-07-03 23:18 UTC, oohira requested changes
PRありがとうございます！お手数ですが、レビュー指摘の確認をお願いします 🙏

2019-07-03 23:18 UTC, oohira commented on src/v2/guide/comparison.md
> +最後に、Vue は [CLI project generator](https://github.com/vuejs/vue-cli)を提供しており、対話形式のプロジェクト構築ウィザードによって新しいプロジェクトを簡単に始めることができます。[instant prototyping](https://cli.vuejs.org/guide/prototyping.html#instant-pro
> CLI project generator

固有名詞ではないので、修正前の日本語訳を残した方が良いかなと思います。

> instant prototyping コンポーネントにそれを使うこともできます。

そういうコンポーネントがあるのではなく、「コンポーネントの高速なプロトタイピングに使える」と言っているのだと思います。

> この分野で進歩を遂げています、ですが

「。」の間違い

2019-07-03 23:18 UTC, oohira commented on src/v2/guide/comparison.md
> +- Vue CLI はアップグレード可能なランタイム依存関係の上で動くため、[プラグイン](https://cli.vuejs.org/guide/plugins-and-presets.html#plugins)による拡張が可能なのに対し、プロジェクトの作成時にいかなる設定もできません。
読点が2回入ると「〇〇なのに対して、△△」という対比が伝わりづらくなってしまうので、「プラグインで拡張できるアップグレード可能なランタイム依存関係の上で動作するのに対し、」ぐらいでいかがでしょうか？

2019-07-03 23:18 UTC, oohira commented on src/v2/guide/comparison.md
> +- Vue が様々な目的やビルドシステムのために様々なデフルトのオプションを提供しているのに対し、シングルページアプリケーションを構築することを想定した 1 つのテンプレートしか提供していません。
「様々な」が2回続いてしまうので、修正前の訳を踏襲して「幅広いデフォルトオプションを提供している」でいかがでしょうか。typo (`デフルト`) があるのでご注意ください

2019-07-04 03:55 UTC, syagawa commented
レビュー有難うございます。タイポもありましたね、申し訳ないです。
修正させて頂きました、ご確認をお願いします。

2019-07-04 12:04 UTC, oohira approved these changes
修正ありがとうございます。LGTM 👍

2019-07-04 12:04 UTC, merged