サーバサイドレンダリング
vuejs/jp.vuejs.org pull request #176
Opened 2016-10-03 12:38 UTC by mikakane

レビューお願いします！

2016-10-04 08:50 UTC, kazupon requested changes
レビュー 👀 しました！指摘内容多くて恐縮ですが、対応よろしくお願いします！

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +Google や Bing は、同期的な Javascript のアプリケーションを上手にインデックスしてくれます。 _同期的な_ というのが重要で、もしあなたのアプリケーションが、ローディングのスピナーから始まり、 Ajax 経由でコンテンツを取得しようとするならば、クローラはローディングの完了を待ってくれないでしょう。
翻訳typoお願いします！

`Javascript` -> `JavaScript`

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +どうです？こうわくないでしょう？もちろんこの例は大半のアプリケーションより随分とシンプルなものです。まだこの段階では、次のような事は考えなくても良いでしょう:
下記でお願いします！
`こうわくないでしょう？` -> `怖くないでしょう？`

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +- Vuex State との合成
Hydration の訳ですが、一旦`ハイドレーション(Hydration)`にしておいてください！
最終的にこちらで良い訳が思いついたら、こちらで対応します！
なので、`Vuex の状態ハイドレーション (Hydration)` でオネガイします。

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +- Response ストリーム
`Response ストリーミング` でお願いします。

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +これで以上です！ [アプリケーションの全体](https://github.com/chrisvfritz/vue-ssr-demo-simple) はここから確認でき、クローンして、色々試してみる事が出来ます。ローカル環境でアプリケーションを実行して、右クリックメニューの "ページのソースを表示" (もしくはそれに近い何か)を選択することで、サーバサイドレンダリングが実際に動いている事を確認で
`Body` -> `body` ですね。

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +## ストリームを用いたレスポンス
`レスポンスのストリーミング` で行きましょう！

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +Vue は __ストリーム__ への出力もまたサポートしており、ストリームをサポートする Web サーバではこちらの方が好まれるかもしれません。ストリームを用いることで、描画が完全に終わってからまとめてレスポンスの出力を行うのではなく、 _描画の進捗に応じて_ 出力を行えるようになります。結果として特段のデメリット無く、レスポンス速度を向上させる事が出来ます。
ここでは、`__ストリーム__` と訳していますが、Node 固有の技術用語なので、 `__ストリーム (stream)__` というように原文と訳をいっしょした形でお願いします。

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +Vue は __ストリーム__ への出力もまたサポートしており、ストリームをサポートする Web サーバではこちらの方が好まれるかもしれません。ストリームを用いることで、描画が完全に終わってからまとめてレスポンスの出力を行うのではなく、 _描画の進捗に応じて_ 出力を行えるようになります。結果として特段のデメリット無く、レスポンス速度を向上させる事が出来ます。
`ストリームをサポートする` ですが、`ストリーミングをサポートする` でオネガイします。

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +上に挙げた例をストリームに対応させる場合、 `server.get('*', ...)` ブロックの中身を単純に次の用に書き換えてやれば OK です:
ここも `ストリーム` でなく、 `ストリーミング` でお願いします！

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
>    // Render our Vue app to a stream
ここのコメントの訳もお願いします！

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +このように、ストリームが初めて触れる概念でも、前の例と比べてもそんなに複雑になるということはありません。私達がすることといえば次の5つです:
`ストリームが初めて触れる概念でも` ですが、 `ストリームという新しい概念に触れる場合でも` でいきましょう！

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +  // アプリケーションより前の HTML をレスポンスに書き込む
`アプリケーションによって出力される HTML より前の HTML 内容をレスポンスに書き込む` にしましょう！

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +  // 新しい chunk が生成されたら...
ここのコメントですが、原文がちょっと分かりにくいので、下記のようにしましょう！

`新しい chunk がアプリケーションによって HTML が描画されたら...`

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +    // chunk をレスポンスに書き込む
`その chunk をレスポンスに書き込む`

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +  // 全ての chunks が生成されたら...
`全ての chunk がアプリケーションによって生成されたら...`

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +    // アプリケーションより後ろの HTML をレスポンスに書き込む
`アプリケーションによって出力される HTML より後の HTML 内容をレスポンスに書き込む`

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +2. アプリケーション以前の HTML をレスポンスに書き込む
`アプリケーションによって出力される HTML より前の HTML 内容をレスポンスに書き込む`

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +4. アプリケーションより後ろの HTML をレスポンスに書き込み、終了する。
`アプリケーションによって出力される HTML より後の HTML 内容をレスポンスに書き込み、終了する`

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +3. アプリケーションの HTML を書き込み描画可能にする。
`アプリケーションで描画される HTML を利用可能なものとして書き込む`

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +5. エラーハンドリングを行う。
`任意のエラーをハンドリングする`

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
>  ### Setup
ここのタイトルも翻訳お願いします！

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +まずは、描画処理に [キャッシュオブジェクト](https://www.npmjs.com/package/vue-server-renderer#cache) を備える必要があります。 [lru-cache](https://github.com/isaacs/node-lru-cache) を用いたシンプルな例を確認してみましょう:
`renderer` は `レンダラ` でいきましょう！

下記のようにしてください。

`描画処理に [キャッシュオブジェクト](https://www.npmjs.com/package/vue-server-renderer#cache) を備える` -> `[キャッシュオブジェクト](https://www.npmjs.com/package/vue-server-renderer#cache) によるレンダラを準備する`

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +### キャッシュしやすいコンポーネントのために
ここは一応原文を忠実に訳した `キャッシュするための理想的なコンポーネント` にしましょう！

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +"純粋な"コンポーネントは - 同じ porps に対して必ず同じ HTML を生成する事が保証されている限り - どのようなものでも安全にキャッシュすることが出来ます。 よくある例としては次のようなものがあります:
`Any "pure" component can be safely cached - that is, any component that is guaranteed to generate the same HTML given the same props. ` 、ここの訳ですが、React の pure component とほぼ同じような内容を定義しているので、下記のようにお願いします。

`"ピュア(pure)"コンポーネントは、同じ props に対して必ず同じ HTML を生成することを保証しているコンポーネントで 、安全にキャッシュすることができます。`

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +- Static なコンポーネント (例えば、常に同じ HTML を生成するもので `serverCacheKey` 関数がただ `true` を返すのみで良いケース)
ここの `Static` は `静的` に訳しましょう！

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +## ビルド、ルーティング、そして Vuex State の活用
`Vuex State Hydration` とりあえず、`Vuex の状態ハイドレーション`にしておいてください。

2016-10-04 08:50 UTC, kazupon commented on src/guide/ssr.md
> +- [vue-server-renderer ドキュメント](https://www.npmjs.com/package/vue-server-renderer#api): ここで触れた内容に関するより詳しい解説に加え、[複数リクエストによる障害について](https://www.npmjs.com/package/vue-server-renderer#why-use-bundlerender
`preventing cross-request contamination` の訳ですが、`複数リクエストによる汚染防止` な感じで原文訳に近いかたちにしておいてださい。

2016-10-04 10:12 UTC, mikakane commented
@kazupon 
レビューありがとうございます！
指摘いただいた点など反映してpushさせてもらいました！

PS. ストリームとストリーミングの表記ゆれ、使い分けはどのようにすればよいでしょうか？
一応全体的にストリーミングに修正し、__ストリーム (stream)__ の項目のみストリームとしております。

2016-10-04 10:49 UTC, kazupon approved these changes
修正内容確認しました。 🙆 です。

2016-10-04 10:55 UTC, kazupon commented
>PS. ストリームとストリーミングの表記ゆれ、使い分けはどのようにすればよいでしょうか？
一応全体的にストリーミングに修正し、ストリーム (stream) の項目のみストリームとしております。

そうですね。
Node.js のコンテキストでは、ストリームは概念であり、Node.jsランタイムの中ではオブジェクトです。
現実世界の例ですと、水道の管ですね。
ストリーミングは、データの流れを表す概念であり、Node.jsランタイムの中では、データを流したり止めたりするなどの処理になります。
ストリーミングを現実世界で例えると、水道の蛇口をひねったり、閉じたり、フィルタをかましたりといったようなことでしょうか。

2016-10-04 11:04 UTC, kazupon requested changes
すいません。:bow: 
さっきの stream / streaming の違いを踏まえて、改めてレビューし直しました。
再度お願いしいます！ :bow:

2016-10-04 11:04 UTC, kazupon commented on src/guide/ssr.md
> +  // ストリーミングに Vue アプリケーションを書き込む
`ストリームに Vue アプリケーションを書き込む`

2016-10-04 11:04 UTC, kazupon commented on src/guide/ssr.md
> +1. ストリーミングを利用する準備
`ストリーム` でお願いします。

2016-10-04 11:04 UTC, kazupon commented on src/guide/ssr.md
> +このように、ストリーミングという新しい概念に触れる場合でも、前の例と比べてもそんなに複雑になるということはありません。私達がすることといえば次の5つです:
ここも、`ストリーム` でお願いします。

2016-10-04 18:30 UTC, mikakane commented
表記修正しました。ご確認よろしくお願いします

2016-10-05 01:46 UTC, kazupon approved these changes

2016-10-05 01:47 UTC, kazupon commented
ありがとうございました！ 🎉

2016-10-05 01:47 UTC, merged