Lang ja 2.0
vuejs/jp.vuejs.org pull request #177
Opened 2016-10-04 07:11 UTC by sshono1210

レビューお願い致します！

2016-10-04 09:46 UTC, kazupon requested changes
レビュー 👀 しました！レビューコメントの対応お願いします！ :bow:

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +Vue コミュニティは驚くべき速さで成長しています、そしてこのページを読んでいるのであればもう参加する準備ができていることでしょう。・・・ようこそ、Vue コミュニティへ！
文章の繋がりに違和感があるので、下記にしましょう！

`Vue コミュニティは驚くべき速さで成長しています。そしてこのページを読んでいるのであればもう参加する準備ができていることでしょう。`

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +- [Github](https://github.com/vuejs): 報告すべきバグや要請したい仕様があれば、GitHub のイシューが最適です。プルリクエストも歓迎します！
`GitHub のイシュー` ですが、GitHub の主要な機能用語なので、とりあえず `GitHub issues` にしておきましょう！

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +### エコシステムを調査する
ここのタイトル訳ですが、`調査する` だと少し硬いニュアンスなので、`調べる` にしておきましょう！

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +### コードのコントリビュート
`Contribute` の訳ですが、`貢献` でお願いします！

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +他のプロジェクトと同様に、コントリビュートのルールがあります。あなたを手伝ったり、プルリクエストをアクセプトするのをできるだけ早く確実に行うために、[the contributing guide](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) を読んで下さい。
ここの`コントリビュート`も`貢献`でお願いします。

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +他のプロジェクトと同様に、コントリビュートのルールがあります。あなたを手伝ったり、プルリクエストをアクセプトするのをできるだけ早く確実に行うために、[the contributing guide](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) を読んで下さい。
`あなたを手伝ったり`  -> `あなたを助けたり`

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +他のプロジェクトと同様に、コントリビュートのルールがあります。あなたを手伝ったり、プルリクエストをアクセプトするのをできるだけ早く確実に行うために、[the contributing guide](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) を読んで下さい。
`アクセプトする` -> `受け入れる`  でお願いします！

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +その後、Vue のコアリポジトリにコントリビュートをする準備をします:
ここの`コントリビュート`も`貢献`でお願いします。

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +- [vue-router](https://github.com/vuejs/vue-router): SPA のためのルーティングシステム
`SPA のためのルーティングシステム` -> `SPA 向けのルーティングシステム`

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +・・・沢山の小さな公式 [姉妹ライブラリ](https://github.com/vuejs) もね。
`・・・などの多くの小さい公式 [相棒的なライブラリ](https://github.com/vuejs) も同様です。` の方がいいかも。

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +### 知見をシェアする（積み上げる）
`知見を共有する (そして築き上げる)` の方がよいでしょう！

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +フォーラムや Gitter channel で質問に答えたりリソースをシェアするのとは別に、あなたが知っていることをシェアして広める方法が他にもいくつかあります:
share の訳ですが、`共有する` でオネガイします！

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +- **学習資料を開発する.** 一番いい学習方法は教えることだと良く言われます。もしあなたが Vue でしている面白いことがあれば、ブログ記事を書いたり、ワークショップを開催したり、ソーシャルメディアにシェアする gist を公開するだけでも専門知識を強化します。
`Develop learning materials.` の訳ですが、 文脈上、`学習教材を作成する` でいいと思います。

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +- **学習資料を開発する.** 一番いい学習方法は教えることだと良く言われます。もしあなたが Vue でしている面白いことがあれば、ブログ記事を書いたり、ワークショップを開催したり、ソーシャルメディアにシェアする gist を公開するだけでも専門知識を強化します。
`もしあなたが Vue でしている面白いことがあれば` -> `もし Vue で何か面白いことをしているならば` で行きましょう！

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +- **学習資料を開発する.** 一番いい学習方法は教えることだと良く言われます。もしあなたが Vue でしている面白いことがあれば、ブログ記事を書いたり、ワークショップを開催したり、ソーシャルメディアにシェアする gist を公開するだけでも専門知識を強化します。
`シェアする` -> `共有したり` ですね。

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +Vue はすでに世界的に広まっており、コアチームでさえ少なくとも６つのタイムゾーンに所在します。[フォーラム](http://forum.vuejs.org/) は7ヶ国語を含んでおり私達のドキュメントの多くが [actively-maintained translations](https://github.com/vuejs?utf8=%E2%9C%93&query=vuejs.org) さ
`国際的到達` -> `国際的な広がり` にしましょう！

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +もしそうであれば、ぜひ [these docs](https://github.com/vuejs/vuejs.org/) または他の公式に管理されているドキュメントのリポジトリを気軽にフォークしてください。いくらか前に進めたら、メインリポジトリのイシューにあげるかプルリクエストを出しましょう、そうしたら私達があなたを手助けするためにより多くのコントリビューターに相談します。
`イシュー` は `GitHub Issues` にしておきましょう！

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +もしそうであれば、ぜひ [these docs](https://github.com/vuejs/vuejs.org/) または他の公式に管理されているドキュメントのリポジトリを気軽にフォークしてください。いくらか前に進めたら、メインリポジトリのイシューにあげるかプルリクエストを出しましょう、そうしたら私達があなたを手助けするためにより多くのコントリビューターに相談します。
`コントリビューター` は `貢献者` にしておきましょう！

2016-10-04 09:46 UTC, kazupon commented on src/guide/join.md
> +Vue はすでに世界的に広まっており、コアチームでさえ少なくとも６つのタイムゾーンに所在します。[フォーラム](http://forum.vuejs.org/) は7ヶ国語を含んでおり私達のドキュメントの多くが [actively-maintained translations](https://github.com/vuejs?utf8=%E2%9C%93&query=vuejs.org) さ
`actively-maintained translations` ですが、`活動的にメンテナンスされ翻訳` にしておきましょう！

2016-10-05 05:15 UTC, sshono1210 commented
レビューありがとうございます！内容を反映してみましたので、再レビューお願いいたします！

2016-10-05 07:36 UTC, kazupon requested changes
再レビュー 👀 しました。2 点対応お願いします！

2016-10-05 07:36 UTC, kazupon commented on src/guide/join.md
> +Vue コミュニティは驚くべき速さで成長しています、そしてこのページを読んでいるのであればもう参加する準備ができていることでしょう。
こちらの説明不足ですいません。`... welcome!` の部分は残しておいてください。`・・・ようこそ！` でお願いします :bow:

2016-10-05 07:36 UTC, kazupon commented on src/guide/join.md
> +他のプロジェクトと同様に、貢献のルールがあります。あなたを助けたり、プルリクエストを受け入れるするのをできるだけ早く確実に行うために、[the contributing guide](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) を読んで下さい。
ここもすいません。 :bow:
`受け入れるするのを` を `受け入れるのを` でお願いします！

2016-10-05 09:04 UTC, sshono1210 commented
二点、修正しましたのでご確認のほどお願い致します！

2016-10-05 09:56 UTC, kazupon approved these changes
ありがとうございます！ 🙆 です！マージしますね！

2016-10-05 09:56 UTC, merged