インストールの翻訳
vuejs/jp.vuejs.org pull request #181
Opened 2016-10-06 17:10 UTC by satotakumi

close #126 

レビューお願いします！

2016-10-06 17:12 UTC, satotakumi commented
変わってた事に気付かなかったです。出直してきます。

2016-10-07 11:40 UTC, kazupon reviewed
翻訳ありがとうございます！
レビュー 👀 しました。
大方問題ないです。
引き続き、よろしくお願いします！

2016-10-07 15:55 UTC, satotakumi commented
@kazupon レビューありがとうございました！
差分取り込んだので、再度レビューお願いします！

2016-10-07 23:08 UTC, kazupon requested changes
レビュー 👀 しました！レビューコメントの内容、お願いします。 🙏

2016-10-07 23:08 UTC, kazupon commented on src/guide/installation.md
> +**重要** Github上の `/dist` フォルダに存在するビルドされたファイルは、リリース時にのみチェックインされます。 Github 上の最新のソースコードから Vue を使用するためには、あなた自身がそれをビルドしなければなりません！
細かいですが、`Github` を `GitHub` に変更お願いします！

2016-10-08 02:44 UTC, satotakumi commented on src/guide/installation.md
> +**重要** Github上の `/dist` フォルダに存在するビルドされたファイルは、リリース時にのみチェックインされます。 Github 上の最新のソースコードから Vue を使用するためには、あなた自身がそれをビルドしなければなりません！
修正しました！

2016-10-08 02:44 UTC, kazupon approved these changes

2016-10-08 02:46 UTC, kazupon commented
👍 
ありがとうございました！
マージします！

2016-10-08 02:46 UTC, merged