[Doc]: Minor A11y & Perf fixes
vuejs/jp.vuejs.org pull request #1833
Opened 2019-09-22 00:34 UTC by oohira

## 概要

* resolve #1796 

## 補足

* cherry-pick & translate vuejs/vuejs.org@5c3b286

2019-09-23 16:28 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
よろしくお願いします！

2019-09-23 16:28 UTC, kazupon commented on themes/vue/layout/page.ejs
> +        <input type="text" id="search-query-menu" aria-label="Search Vue.JS site" class="search-query st-default-search-input">
`aria-label` もローカライズしてもらえると助かります！ 🙏

2019-09-23 16:28 UTC, kazupon commented on themes/vue/layout/partials/main_menu.ejs
> +    <input type="text" id="search-query-<%- context %>" class="search-query st-default-search-input" aria-label="Search">
ここの、 `aria-label` もですね。

2019-09-23 16:28 UTC, kazupon commented on themes/vue/layout/partials/sponsors.ejs
> +      <img src="https://opencollective.com/vuejs/tiers/platinum-sponsors/<%- i %>/avatar.svg" alt="Vue.JS sponsor">
細かいですが、 `alt` もローカライズ必要かなと思います。

2019-09-23 16:28 UTC, kazupon commented on themes/vue/layout/partials/sponsors.ejs
> +      <img src="https://opencollective.com/vuejs/tiers/gold-sponsors/<%- i %>/avatar.svg" alt="Vue.JS sponsor">
ここの `alt` も同じく。

2019-09-23 16:28 UTC, kazupon commented on themes/vue/layout/search-page.ejs
> +      <a target="_blank" href="https://www.algolia.com/" aria-label="Search">
ここの `aria-label` もですね。

2019-09-24 15:16 UTC, oohira commented on themes/vue/layout/page.ejs
> +        <input type="text" id="search-query-menu" aria-label="Search Vue.JS site" class="search-query st-default-search-input">
手抜きスミマセン...翻訳しました。

なお、`Vue.JS` という表記を使っている箇所がないので、本家に忠実に訳すべきか迷いましたが `Vue.js` で統一しました。

```html
<input type="text" id="search-query-menu" aria-label="Vue.js のサイトを検索" class="search-query st-default-search-input">
```

2019-09-24 15:18 UTC, oohira commented on themes/vue/layout/partials/main_menu.ejs
> +    <input type="text" id="search-query-<%- context %>" class="search-query st-default-search-input" aria-label="Search">
ありがとうございます。翻訳済みです。

2019-09-24 15:18 UTC, oohira commented on themes/vue/layout/partials/sponsors.ejs
> +      <img src="https://opencollective.com/vuejs/tiers/platinum-sponsors/<%- i %>/avatar.svg" alt="Vue.JS sponsor">
翻訳しました。前述のとおり、`Vue.js` で統一しています。

2019-09-24 15:18 UTC, oohira commented on themes/vue/layout/partials/sponsors.ejs
> +      <img src="https://opencollective.com/vuejs/tiers/gold-sponsors/<%- i %>/avatar.svg" alt="Vue.JS sponsor">
翻訳済みです。

2019-09-24 15:20 UTC, oohira commented on themes/vue/layout/search-page.ejs
> +      <a target="_blank" href="https://www.algolia.com/" aria-label="Search">
翻訳済みです。上の方の input の属性もあわせて翻訳しました。

```html
<input
      class="search-query"
      v-model="search"
      placeholder="Vue.js のサイトを検索"
      aria-label="検索"
```

2019-09-24 16:22 UTC, kazupon approved these changes
👍 ありがとうございます。

2019-09-24 16:22 UTC, merged