Translate comparison.md for Vue 2.0 to Japanese
vuejs/jp.vuejs.org pull request #185
Opened 2016-10-31 15:41 UTC by ktsn

Close #150

🙇 

少し気になる点に関してインラインでコメントを入れます。

2016-10-31 15:52 UTC, ktsn commented on src/guide/comparison.md
> +- テンプレートを書く上で必要となる実装やコーディングスタイルの決定はずっと少ないです
> stylistic decision

これを「スタイルの決定」のように訳すとちょっと意味がわかりづらいかと思って、「**コーディング**スタイルの決定」としています。

2016-10-31 15:52 UTC, ktsn commented on src/guide/comparison.md
> +- それはより英語らしく読めます（例えば、for each item in items - 訳注：items の中のそれぞれの item）
この訳注はアリでしょうか？

2016-10-31 15:52 UTC, ktsn commented on src/guide/comparison.md
> +- ユーザーが作ったテンプレートからプロジェクトを生成することは、開発スタイルを決定する前の企業の環境では特に役立ちますが、そのようなことはできません。
`enterprise environments with pre-established conventions` の訳に自信がないです。

convention を辞書で引くと

> a method or style often used in literature, art, the theatre etc to achieve a particular effect

とあったので、この文は開発スタイルを決める段階で試行錯誤することなのかと思い、この訳にしています。
（「合意が取れる前」でも良いかも……？）

2016-11-01 02:51 UTC, kazupon requested changes
レビューしました！ 👀 
レビューコメント内容の対応お願いします！

2016-11-01 02:51 UTC, kazupon commented on src/guide/comparison.md
> +- テンプレートを書く上で必要となる実装やコーディングスタイルの決定はずっと少ないです
👍 
分かりやすくていいと思います。

2016-11-01 02:51 UTC, kazupon commented on src/guide/comparison.md
> +- それはより英語らしく読めます（例えば、for each item in items - 訳注：items の中のそれぞれの item）
`訳注`をつければ、翻訳独自であることが分かるので、特に問題ないのでアリです。
これでいきましょう！

2016-11-01 02:51 UTC, kazupon commented on src/guide/comparison.md
> +オプショナルな `scoped` 属性は、要素に一意な属性（`data-v-1` のようなもの）を付与し、`.list-container:hover` を `.list-container[data-v-1]:hover` のようなものにコンパイルすることで、この CSS のスコープをあなたのコンポーネントに限定します。
`optional` はここでは `任意の` とか意味が通じるので、これでどうでしょうか。

2016-11-01 02:51 UTC, kazupon commented on src/guide/comparison.md
> +大きなアプリケーションのために、Vue も React も強力なルーティングの解法を提供しています。React コミュニティは状態管理という観点でとても革新的な解法を持っています（例えば、Flux/Redux）。これらの状態管理のパターンと、[さらに Redux 自体](https://github.com/egoist/revue)は簡単に Vue のアプリケーションと統合することができます。
`Elm-inspired` の訳ですが、 `Elm に触発された` とか、どうでしょうか。

2016-11-01 02:51 UTC, kazupon commented on src/guide/comparison.md
> +- ユーザーが作ったテンプレートからプロジェクトを生成することは、開発スタイルを決定する前の企業の環境では特に役立ちますが、そのようなことはできません。
👍 
いいと思います。

2016-11-01 05:02 UTC, ktsn commented on src/guide/comparison.md
> +オプショナルな `scoped` 属性は、要素に一意な属性（`data-v-1` のようなもの）を付与し、`.list-container:hover` を `.list-container[data-v-1]:hover` のようなものにコンパイルすることで、この CSS のスコープをあなたのコンポーネントに限定します。
「任意の scoped 属性」だと「すべての」という意味に聞こえてくるので、「任意に付与できる scoped 属性」でいかがでしょう？

2016-11-01 06:05 UTC, kazupon commented on src/guide/comparison.md
> +オプショナルな `scoped` 属性は、要素に一意な属性（`data-v-1` のようなもの）を付与し、`.list-container:hover` を `.list-container[data-v-1]:hover` のようなものにコンパイルすることで、この CSS のスコープをあなたのコンポーネントに限定します。
確かにそうですね。`任意に付与できる scoped 属性` にしましょう！

2016-11-01 06:16 UTC, ktsn commented
@kazupon 修正しました！

2016-11-01 08:01 UTC, kazupon approved these changes
👍 
翻訳ありがとうございました！
問題ないのでマージしますね！

2016-11-01 08:01 UTC, merged