Translate components
vuejs/jp.vuejs.org pull request #186
Opened 2016-11-01 14:45 UTC by kdnk

時間かかってしまいました。。。
確認お願いします！

2016-11-01 17:05 UTC, kazupon requested changes
翻訳ありがとうございます！
レビュー 👀 しました。
レビューコメントの対応お願いします！

2016-11-01 17:05 UTC, kazupon commented on src/guide/components.md
> +レンダリングされる内容は以下になります:
`render` の訳については、`描画` で今後統一したいので、それでお願いします。

2016-11-01 17:05 UTC, kazupon commented on src/guide/components.md
> +同じカプセル化は、ディレクティブ、フィルタ、そしてトランジションのようなアセットタイプに対して適用されます。
`such as directives`なので、`ディレクティブ、フィルタ、そしてトランジションのような`ではなく、`ディレクティブのような`ですね。

2016-11-01 17:05 UTC, kazupon commented on src/guide/components.md
> +すべての Vue インスタンスは [Events interface](/api/#Instance-Methods-Events) を実装しています。これは以下をできることを意味します:
`Events interface` はそのまま、`イベントインタフェース` と訳すことにしましょう！

2016-11-01 17:05 UTC, kazupon commented on src/guide/components.md
> +- `$on(eventName)`を使用してイベントをリッスンします。
`listen` は `購読` の訳でお願いします！

2016-11-01 17:05 UTC, kazupon commented on src/guide/components.md
> +それに加えて、親コンポーネントは、子コンポーネントが使われているテンプレート内で直接 `v-on` を使用することで、子コンポーネントからのイベントをリッスンすることができます。
ここの `listen` も `購読` でお願いします！

2016-11-01 17:05 UTC, kazupon commented on src/guide/components.md
> +コンポーネントの root 要素でのネイティブイベントをリッスンしたいときがあるかもしれません。このような場合、`v-on` に `.native` 修飾子を使用することができます。例:
ここの `listen` も `購読` でお願いします！

2016-11-01 17:05 UTC, kazupon commented on src/guide/components.md
> +より複雑なケースでは、専用の [state-management pattern](/guide/state-management.html) 採用することを考えるべきです。
`state-management pattern` は `状態管理パターン` でお願いします！

2016-11-01 17:05 UTC, kazupon commented on src/guide/components.md
> +レンダリング結果は以下になります:
`rendered` は `描画された` でお願いします！

2016-11-01 17:05 UTC, kazupon commented on src/guide/components.md
> +レンダリングされる結果は以下になります:
ここの `rendered` も `描画された` でお願いします！

2016-11-01 17:05 UTC, kazupon commented on src/guide/components.md
> +`<keep-alive>` のさらなる詳細については、[API reference](/api/#keep-alive) を確認して下さい。
`API referecen` は `API リファレンス` の訳にしておいてください！

2016-11-01 17:05 UTC, kazupon commented on src/guide/components.md
> +<p class="tip"> `$refs` はコンポーネントがレンダリングされた後にのみ追加されます。そしてそれはリアクティブではありません。直接子コンポーネントを操作するための最終手段としての意味しかありません。 - テンプレートまたは算出プロパティ(computed property)の中での `$refs` の使用は避けるべきです。</p>
ここの `rendered` も `描画された` でお願いしいます！

2016-11-01 17:05 UTC, kazupon commented on src/guide/components.md
> +Vue では、素の HTML 要素をレンダリングするのはとても高速です。しかし、ときどき、静的なコンテンツを **大量に** 含むコンポーネントがあるかもしれません。このような場合、以下のように root 要素で `v-once` ディレクティブを追加することによって、コンポーネントを一度のみ評価しキャッシュしておくことを保証することができます。
`Rendering` はとりあえず、`描画する`でお願いします！

2016-11-04 11:21 UTC, kdnk commented
修正しました！
確認お願い致します！

2016-11-04 11:40 UTC, kazupon approved these changes
確認しました！
ありがとうございます！

2016-11-04 11:40 UTC, merged