translate custom directives
vuejs/jp.vuejs.org pull request #188
Opened 2016-11-04 01:14 UTC by massa142

Close #141

遅くなってすみません :bow:
'Custom Directives' を翻訳しました。レビューをお願い致します。

2016-11-04 02:06 UTC, kazupon commented
ありがとうございます！
レビューしますね！

2016-11-04 09:00 UTC, kazupon requested changes
レビュー 👀 しました。
レビューコメントの対応お願いします！！

2016-11-04 09:00 UTC, kazupon commented on src/guide/custom-directive.md
> +Vue 2.0 では、コードの再利用と抽象化における基本の形はコンポーネントです。 - しかしながら、通常の要素で低レベル DOM にアクセスしなければならないケースがあるかもしれません。こういった場面では、カスタムディレクティブが役立つでしょう。
原文と同じ段落構成にしておいてください！

2016-11-04 09:00 UTC, kazupon commented on src/guide/custom-directive.md
> +さあ、これを実現させるディレクティブを作りましょう。
ここも、原文と同じ段落構成にしておいてください！

2016-11-04 09:00 UTC, kazupon commented on src/guide/custom-directive.md
> +- `inserted`: ひも付いている要素が親 Node に挿入された時に呼ばれます。(これは親 Node が存在していることのみ保証します。必ずしも in-document ではありません)
訳、`これは親 Node が存在していることのみ保証します。必ずしも in-document ではありません` ですが、
下記の方が分かりやすいような気がします。

`これは、親 Node が存在している時にだけ保証します。必ずしも、ドキュメントにあるとは限りません。`

2016-11-04 09:00 UTC, kazupon commented on src/guide/custom-directive.md
> +- `update`: 含んでいるコンポーネントが更新された後に呼ばれます。__しかし、おそらく子コンポーネントが更新される前でしょう。__ ディレクティブの値が変化してもしなくても、バインディングされている値と以前の値との比較によって不要な更新を回避することができます。(フック引数に関しては下記を参照してください)
`含んでいるコンポーネントが更新された後に呼ばれます。`という訳ですが、以下でどうでしょうか？

`ひも付いた要素を抱合しているコンポーネントが更新される度に呼ばれます。`

2016-11-04 09:00 UTC, kazupon commented on src/guide/custom-directive.md
> +- `componentUpdated`: 含んでいるコンポーネント __と子コンポーネント__ が更新された後に呼ばれます。
`含んでいるコンポーネント __と子コンポーネント__ が更新された後に呼ばれます。` という訳ですが、以下でいかがでしょうか？

`抱合しているコンポーネントと__と子コンポーネント__が更新された後に呼ばれます。`

2016-11-04 23:26 UTC, kazupon approved these changes

2016-11-04 23:27 UTC, kazupon commented
レビュー指摘内容の方、こちらで対応しますね！
翻訳ありがとうございました！

2016-11-04 23:27 UTC, merged

2016-11-05 02:56 UTC, massa142 commented
@kazupon
対応ありがとうございました！