add retireing vue-resource blog translation
vuejs/jp.vuejs.org pull request #190
Opened 2016-11-05 02:34 UTC by chi-bd

slackで事前共有済みのものから、
* fetch APIのURLを日本語版に張り替え
* 一部の日本語を微調整

してあります。
現在作業中であろう2.0日本語ドキュメント公開の後で構わないのでよろしくお願いします。

2016-11-07 03:45 UTC, kazupon requested changes
レビュー 👀 しました！
レビューコメント 💬 の内容、確認お願いします！

2016-11-07 03:45 UTC, kazupon commented on src/_posts/retiring-vue-resource.md
> +2. 同じ問題を解決するための優れた 3rd パーティの ajax ライブラリがあり、より積極的に改良/保守されていて、かつユニバーサル/isomorphic（Node とブラウザの両方で動作し、そのことはサーバーサイドレンダリング用途での Vue 2.0 にとって重要）になるよう設計されています。
`universal` の訳 ユニバーサルですが、一応 isomorphic と対応させて、`クライアントとサーバなど異なる環境で同じコードが動作する` と説明付けておいた方がいいと思います。

ちなみに、isomorphic ですが、現状は、`クライアントとサーバで同じ (HTML) ページを生成する技術` のことを指しているようです。

universal と isomorphic についてはこちらが参考になります。
http://qiita.com/kyrieleison/items/4ac5bcc331aee6394440

2016-11-07 03:45 UTC, kazupon commented on src/_posts/retiring-vue-resource.md
> +1. ルーティングや state 管理とは異なり、ajax は Vue のコアとの緊密な統合を必要とする問題領域ではありません。
`state` は `状態` でも通じるので、これに訳してもいい気がします。

2016-11-07 03:45 UTC, kazupon commented on src/_posts/retiring-vue-resource.md
> +我々が初期の頃 vuejs organization にそれを移したのは、コミュニティが本質的な問題を解決するためのライブラリを寄付することは良いことだと思ったからであり、また我々は PageKit チームがプロジェクトに投下したすべての作業に大いに感謝しています。
`我々` という言葉は少し硬いので、`私たち` にしましょう！

2016-11-07 03:45 UTC, kazupon commented on src/_posts/retiring-vue-resource.md
> +我々が初期の頃 vuejs organization にそれを移したのは、コミュニティが本質的な問題を解決するためのライブラリを寄付することは良いことだと思ったからであり、また我々は PageKit チームがプロジェクトに投下したすべての作業に大いに感謝しています。
他に`我々`と訳したところも、`私たち`でお願いします！

2016-11-07 03:45 UTC, kazupon commented on src/_posts/retiring-vue-resource.md
> +1. ルーティングや state 管理とは異なり、ajax は Vue のコアとの緊密な統合を必要とする問題領域ではありません。
他にも`state`としていることころは、`状態`でお願いします！

2016-11-07 03:45 UTC, kazupon commented on src/_posts/retiring-vue-resource.md
> +3. (1)及び(2)であるならば、vue-resource の現状を維持することは二度手間かつ不要なメンテナンスの負担をもたらしていることが明らかです。
`(1)及び(2)であるならば` ですと、プログラムっぽい感じですので、`(1) と (2) であるので` とかの訳のように、少し読み手にとって自然と読みやすい感じしましょう！

2016-11-07 22:33 UTC, chi-bd commented on src/_posts/retiring-vue-resource.md
> +2. 同じ問題を解決するための優れた 3rd パーティの ajax ライブラリがあり、より積極的に改良/保守されていて、かつユニバーサル/isomorphic（Node とブラウザの両方で動作し、そのことはサーバーサイドレンダリング用途での Vue 2.0 にとって重要）になるよう設計されています。
ユニバーサルに対する訳注を追加してください、という意味だと解釈しましたが、下記の理由を踏まえたうえでも本当に必要かどうかを再確認させてください。
* isomorphicの直後のコメントは訳注として追加したものではなく、原文の"(works in both Node and Browsers, which is important for Vue 2.0 with its server-side rendering usage)"の訳そのものであること
* このコメントはisomorphic単体に対するものではなく"universal/isomorphic"のセットに対するものであると解されること

「"universal/isomorphic"をセットで扱い、あえて訳さない」という落としどころもあるかな、とは思います。

2016-11-08 06:35 UTC, kazupon commented on src/_posts/retiring-vue-resource.md
> +2. 同じ問題を解決するための優れた 3rd パーティの ajax ライブラリがあり、より積極的に改良/保守されていて、かつユニバーサル/isomorphic（Node とブラウザの両方で動作し、そのことはサーバーサイドレンダリング用途での Vue 2.0 にとって重要）になるよう設計されています。
なるほど。
そうですね、`universal/isomorphic` という用語は、この記事では訳さないことにしましょう！

2016-11-08 10:57 UTC, chi-bd commented
指摘事項を反映して追加commitしておきました。よろしくお願いします

2016-11-08 10:58 UTC, kazupon approved these changes
👍

2016-11-08 10:58 UTC, merged

2016-11-08 10:58 UTC, kazupon commented
ありがとうございました！