#1896 Translate security guid line page
vuejs/jp.vuejs.org pull request #1929
Opened 2019-11-18 10:32 UTC by unotovive

## 概要

resolve #1896 

## 補足

#1895 の翻訳

2019-11-23 14:04 UTC, oohira requested changes
翻訳ありがとうございます 👍 

いくつかレビュー指摘していますので、ご確認ください。私がまだレビューアーとしてまとまった文書をチェックしたことがないので、「この指摘違うのでは？」というものがあれば、鵜呑みにせずぜひフィードバックください 🙏

2019-11-23 14:04 UTC, oohira commented on src/v2/guide/security.md
> +例えばこのようなテンプレートの場合:
* MUST: `render function` は [描画関数](https://jp.vuejs.org/v2/guide/render-function.html) のことだと思うので、`描画関数` でお願いします
* nits: 次の「例えばこのような〜」の文は、原文に合わせてそのまま1文目と同じ行に続けていただけますか。原文と行数が揃っていた方が、レビュー時のdiffが見やすかったり、今後の更新も追いやすかったりしますので。44行目や76行目なども同様です

2019-11-23 14:04 UTC, oohira commented on src/v2/guide/security.md
> +もし `userProvidedString` に以下が含まれていると
MUST: 日本語翻訳ガイドで [原文に使われる ':' や '!' や '?' などの記号は極力残して翻訳](https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#%E5%8E%9F%E6%96%87%E3%81%AB%E4%BD%BF%E3%82%8F%E3%82%8C%E3%82%8B--%E3%82%84--%E3%82%84--%E3%81%AA%E3%81%A9%E3%81%AE%E8%A8%98%E5%8F%B7%E3%81%AF%E6%A5%B5%E5%8A%9B%E6%AE%8B%E3%81%97%E3%81%A6%E7%BF%BB%E8%A8%B3) というルールがありますので、末尾のコロンは削除せずに残していただきたいです。これ以降でも何箇所か削除されているようなので、あわせて修正いただけますか

2019-11-23 14:04 UTC, oohira commented on src/v2/guide/security.md
> +Vue では、このようにスクリプトのインジェクションを防ぎます。このエスケープ処理は `textContent` 等のネイティブブラウザ API を使用して行われるため、ブラウザ自体が脆弱な場合では脆弱性が存在します。
SHOULD: 64行目のように `ブラウザ自体が脆弱な場合のみ` とした方がニュアンスが近そうです

2019-11-23 14:04 UTC, oohira commented on src/v2/guide/security.md
> +例えば、CodePen や JSFiddle などのサービスでは、ユーザによって提供されるコンテンツを実行できます。しかしこれらは、 iframe 内で、ある程度予想されサンドボックス化されている状態です。重要な機能が本質的にある程度の脆弱性を必要とする場合、その機能の重要性と脆弱性によって起こる最悪な可能性との比較は貴方のチームに委ねられます。
IMO: `しかし、これは想定通りで、iframe 内である程度サンドボックス化されている状況においてです。〜その機能の重要性と脆弱性による最悪のシナリオとをてんびんにかけることは、あなたのチームに委ねられます。` ぐらいでしょうか。 `貴方` と漢字を使っている既存箇所はない気がします

2019-11-23 14:04 UTC, oohira commented on src/v2/guide/security.md
> + `javascript:` の利用によって JavaScript を実行する方法を防ぐ対策をしていない URL には潜在的にセキュリティの問題点があります。これの対策に、[sanitize-url](https://www.npmjs.com/package/@braintree/sanitize-url) 等のライブラリがあります。
* IMO: `URL を "無害化" して javascript: の利用による JavaScript 実行を防いでいない場合、潜在的なセキュリティの問題があります` ぐらいでどうでしょうか
* MUST: 最後の `but note:` の部分は、tip の中に入れるのではなく、原文にあわせてこの文に続けてほしいです

2019-11-23 14:04 UTC, oohira commented on src/v2/guide/security.md
> +<p class="tip">しかし注意して下さい、フロントエンドで URL の無害化処理を行ったことがある場合、それはすでにセキュリティ上の問題をはらんでいます。ユーザの入力による URL は、常にバックエンドでデータベースに保存する前の処理が必要です。そうすることでモバイルのネイティブアプリを含め、API に接続するすべてのクライアントで問題を回避することができます。また、無害化処理がされた
MUST: 細かいですが `_every_ client` 部分のスタイル指定は残していただけますか

2019-11-23 14:04 UTC, oohira commented on src/v2/guide/security.md
> +ユーザによるクリックジャックを完全に防止するためには、CSS の完全な制御は iframe 内のサンドボックス化された場所でのみ行うことをお勧めします。または、スタイルバインディングを介してユーザにコントロールを与えたい場合は、下記のように [object syntax](class-and-style.html#Object-Syntax-1) を利用し、ユーザが制御できるプロパティを限定する
IMO: `allowing users to provide values` のニュアンスを残したいです。 `特定のプロパティの値だけを設定できるようにする`  ぐらいでしょうか

2019-11-23 14:04 UTC, oohira commented on src/v2/guide/security.md
> +テンプレートとレンダリング関数に副作用が生じることは無いため、Vue で `<script>` 要素をレンダリングすることは強くお勧めしません。ただしこれは、実行時に JavaScript として評価される文字列を含めるための唯一の方法ではありません。
MUST: `テンプレートと描画関数は副作用をもつべきではないため、` かなと思います。独自に script タグを定義すると副作用が出てしまうのでやめておけ、と言いたいのだと思います。

2019-11-23 14:04 UTC, oohira commented on src/v2/guide/security.md
> +1. 開発者が、ユーザ提供の無害化されていないコンテンツを Vue テンプレートとしてレンダリングするように明示的に支持している場合。これは本質的に安全ではなく、また Vue がそのコンテンツの元を感知する方法はありません。
nits: typo 支持 → 指示

2019-11-23 14:04 UTC, oohira commented on src/v2/guide/security.md
> +2. 開発者が。HTML ページ全体に Vue をマウントしている場合。このページにはサーバでレンダリングされたユーザ提供のコンテンツが含まれています。問題は基本的に\#1と同じですが、開発者が気づかぬうちにそうしてしまうことがあります。これにより、プレーンな HTML としては無害だとしても、Vue テンプレートとしては安全でない HTML を攻撃者が設置することできる脆弱性が発生します。
* nits: typo `開発者が。HTML ページ全体に` → `開発者が、HTML ページ全体に`
* IMO: 途中で文を切らない方が1つ目と対称性があって分かりやすい気がします。 `開発者が、サーバでレンダリングされたユーザ提供のコンテンツを含む HTML ページ全体に Vue をマウントしている場合`
* MUST: 最終行を訳し忘れているようですので、お願いできますか

2019-11-23 14:04 UTC, oohira commented on src/v2/guide/security.md
> +SSR を利用する場合、上記の推奨事項に加えていくつかセキュリティ上の懸念があります。別途、[SSR documentation](https://ssr.vuejs.org/) で解説されているベストプラクティスを参照してください。
MUST: 翻訳ページ https://ssr.vuejs.org/ja/ があるので、リンク先とタイトルを日本語ページに合わせていただけますか

2019-11-23 14:12 UTC, oohira commented
@kazupon @potato4d セキュリティガイドラインということもあって他の文書よりも訳には気を使う文書だと思いますので、最終確認はお願いしたいです。

いくつか気になったけど、判断がつかず指摘していないものがあります。もしルールなどあれば教えていただきたいです

1. `sanitize` を `無害化` と訳していただいていますが、`サニタイズ` のままにするなり `無害化 (sanitize)` とするなり、何かしら原文が伝わるように残した方がよいか
1. `user-provided content` を `ユーザ提供のコンテンツ` と訳していただいていますが、既存文書にはなさそうでした。 `ユーザー入力のコンテンツ` ぐらいの方がよいか
1. `HTML, CSS, or JavaScript` を `HTML・CSS・JavaScript` と訳していただいていますが、区切りを原文のままカンマにするのか、日本語の読点にするのか、特にルールはないのか

2019-11-25 14:56 UTC, kazupon requested changes
私の方でもレビュー 👀 しました。
翻訳ありがとうございます！

訳内容、全体としてはは大筋間違っているところなく、 細かいところは、@oohira さんが指摘した部分を修正お願いします。

2019-11-25 14:56 UTC, kazupon commented on src/v2/guide/security.md
> +どのような Web アプリケーションでも、ユーザの入力による無害化されていないコンテンツを HTML ・ CSS ・  JavaScript として実行できるようにすることは潜在的な危険があるため、可能な限り避ける必要があります。しかしながら、ある程度のリスクなら許容される場合もあります。
`HTML, CSS, or JavaScript` を訳す際の `,` ですが、こちらは 全角の `、` でお願いします。 🙏

2019-11-25 14:56 UTC, kazupon commented on src/v2/guide/security.md
> +この例をご覧ください:
ここは特にかしこまる必要はないので、 `ご覧ください`  ではなく、 `見てください` でいいですね。

2019-11-25 14:56 UTC, kazupon commented on src/v2/guide/security.md
> +ユーザによるクリックジャックを完全に防止するためには、CSS の完全な制御は iframe 内のサンドボックス化された場所でのみ行うことをお勧めします。または、スタイルバインディングを介してユーザにコントロールを与えたい場合は、下記のように [object syntax](class-and-style.html#Object-Syntax-1) を利用し、ユーザが制御できるプロパティを限定する
`object syntax` は[こちら](https://jp.vuejs.org/v2/guide/class-and-style.html#%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E6%A7%8B%E6%96%87)で `オブジェクト構文` で訳されているので、そちらの合わせるようお願いします。

2019-11-25 14:56 UTC, kazupon commented on src/v2/guide/security.md
> +ユーザによるクリックジャックを完全に防止するためには、CSS の完全な制御は iframe 内のサンドボックス化された場所でのみ行うことをお勧めします。または、スタイルバインディングを介してユーザにコントロールを与えたい場合は、下記のように [object syntax](class-and-style.html#Object-Syntax-1) を利用し、ユーザが制御できるプロパティを限定する
細かいですが、 `コントロール` のところも、 `制御` にしておいた方が、訳の文章として一貫性がありますね。

2019-11-25 14:56 UTC, kazupon commented on src/v2/guide/security.md
> +一般的なルールとして、無害化されていないユーザー提供のコンテンツ（HTML ・ CSS ・ JavaScript）を実行することは、攻撃にさらされる可能性があるということです。このアドバイスは Vue に限らず、他のフレームワーク、さらにはフレームワークを利用していない場合でも有効です。
`HTML, CSS, or JavaScript` を訳す際の , ですが、こちらは 全角の `、` でお願いします。 🙏

2019-11-25 14:56 UTC, kazupon commented on src/v2/guide/security.md
> +ユーザによるクリックジャックを完全に防止するためには、CSS の完全な制御は iframe 内のサンドボックス化された場所でのみ行うことをお勧めします。または、スタイルバインディングを介してユーザにコントロールを与えたい場合は、下記のように [object syntax](class-and-style.html#Object-Syntax-1) を利用し、ユーザが制御できるプロパティを限定する
`like this:` の `:` が抜けているので、それも残しておいてください。 🙏

2019-11-25 15:01 UTC, kazupon commented
@oohira 

> * `sanitize` を `無害化` と訳していただいていますが、`サニタイズ` のままにするなり `無害化 (sanitize)` とするなり、何かしら原文が伝わるように残した方がよいか

そうですね。本当に入門されている方もいるかと思うので、併記形式 `無害化 (sanitize)` にしておいた方が、よさそうです。

> * `user-provided content` を `ユーザ提供のコンテンツ` と訳していただいていますが、既存文書にはなさそうでした。 `ユーザー入力のコンテンツ` ぐらいの方がよいか

うーん、そうですね。少し意訳気味かつ、原文も残す形で`ユーザー入力のコンテンツ (user-provided content)` でいかがでしょうか。

2019-11-28 14:36 UTC, potato4d commented
こちら遅れましたが私の方でも見ます👀

2019-12-15 16:17 UTC, kazupon commented
@potato4d 
見れますか？

2019-12-16 05:49 UTC, potato4d requested changes
遅くなりましたがいくつかコメント出しました 🙇

2019-12-16 05:49 UTC, potato4d commented on src/v2/guide/security.md
> +<p class="tip">ユーザが提供した HTML は、サンドボックス化された iframe、またはそれを提供したユーザのみがアクセスできるアプリの一部という場合を除き、100%安全とはみなされないことに注意して下さい。また、ユーザが独自の Vue テンプレートを作成できるようにすることも同様の危険があります。</p>
[nits]
「ください」は平仮名に開いてやるとよいかと思います。

2019-12-16 05:49 UTC, potato4d commented on src/v2/guide/security.md
> +すべての HTML 要素には、`onclick` や `onfocus`、`onmouseenter` 等の JavaScript 文字列を値として受け入れる属性があります。ユーザによって提供された JavaScript をこれらのイベント属性にバインドすることは、潜在的なセキュリティリスクとなるので避ける必要があります。
[nits]
`s/等/など/` しておくとよいかとー。

2019-12-16 05:49 UTC, potato4d commented on src/v2/guide/security.md
> +1. 開発者が、ユーザ提供の無害化されていないコンテンツを Vue テンプレートとしてレンダリングするように明示的に支持している場合。これは本質的に安全ではなく、また Vue がそのコンテンツの元を感知する方法はありません。
- IMO: origin のコンテンツがどういったものであるかに関心を持てるかどうかだと思うので、 `知る方法` にしてもよさそうです。
- IMO: origin の役も `オリジナルのコンテンツ` としても良いかとおもいますが、どうでしょう

2019-12-20 15:12 UTC, kazupon commented
@unotovive レビュー大体終わったので、こちらコメントのところ対応お願いできますか？ 🙏

2019-12-23 22:31 UTC, Lamar80 commented
こんにちは、お元気ですか。 返信が遅くなってすみません。 私のメールにwhatsapp番号を常に記載していない場合があります。

On Fri, Dec 20, 2019, 3:12 PM kazuya kawaguchi <notifications@github.com>
wrote:

> @unotovive <https://github.com/unotovive>
> レビュー大体終わったので、こちらコメントのところ対応お願いできますか？ 🙏
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vuejs/jp.vuejs.org/pull/1929?email_source=notifications&email_token=AKVJVYFPZKGR6N2RBDBAAUDQZTOHRA5CNFSM4JORJTQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHNFVYQ#issuecomment-567958242>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKVJVYAVK2WRLB2GLJ2UTXLQZTOHRANCNFSM4JORJTQQ>
> .
>

2019-12-24 04:37 UTC, unotovive commented
@oohira @kazupon @potato4d レビューありがとうございます！
遅くなりましたが、こちら修正いたしました。ご確認いただければと思います

2019-12-30 17:45 UTC, kazupon approved these changes
ありがとうございます！一旦マージします。

2019-12-30 17:45 UTC, merged