Document gotcha with :is and DOM props
vuejs/jp.vuejs.org pull request #1955
Opened 2019-12-05 07:03 UTC by inosy22

## 概要

resolve #1947

## 補足

こちらのコミットの翻訳になります。
vuejs/vuejs.org@3d96b74

レビューよろしくお願いいたします🙏

2019-12-07 05:24 UTC, oohira commented on src/v2/guide/components.md
> +`value` などの一部のプロパティが、期待通りに動作するためには、[`.prop` 修飾子](../api/#v-bind) を使ってバインドする必要があります。
nits: 細かいですが、原文では1段落なので合わせていただいてもよいでしょうか？

![image](https://user-images.githubusercontent.com/4208984/70369462-f9344900-18fc-11ea-8d73-9176faf59e92.png)

2019-12-07 05:26 UTC, oohira requested changes
@inosy22 翻訳ありがとうございます！スタイルの調整だけお願いします 🙏

2019-12-09 03:21 UTC, inosy22 commented on src/v2/guide/components.md
> +`value` などの一部のプロパティが、期待通りに動作するためには、[`.prop` 修飾子](../api/#v-bind) を使ってバインドする必要があります。
レビューありがとうございます！後ほど対応いたします！

2019-12-10 09:43 UTC, inosy22 commented
@oohira 修正させていただきました！
お手数ですが再度ご確認いただけると幸いです。

2019-12-10 14:26 UTC, oohira approved these changes

2019-12-10 14:26 UTC, merged

2019-12-10 14:27 UTC, oohira commented
@inosy22 LGTM. ありがとうございました！ 👍

2019-12-12 09:20 UTC, inosy22 commented
ご確認ありがとうございました！