翻訳の改善
vuejs/jp.vuejs.org pull request #209
Opened 2017-01-25 03:56 UTC by knzm

ドキュメントを読んでいて気になった部分を修正しました。

2017-01-25 06:00 UTC, kazupon requested changes
PRありがとうございました！
助かります！ 🙏 
レビュー 👀 しましたので、確認お願いします！

2017-01-25 06:00 UTC, kazupon commented on src/v2/guide/components.md
> +コンポーネントは Vue.js の最も強力な機能の 1 つです。基本的な HTML 要素を拡張して再利用可能なコードのカプセル化を助けます。ハイレベルには、コンポーネントは Vue.js のコンパイラが指定された振舞いを加えるカスタム要素です。場合によっては、特別な `is` 属性で拡張されたネイティブな HTML 要素の姿をとることもあります。
翻訳のポリシーとして、なるべく日本語に翻訳するというポリシーなので、ここは現状のままにしておきましょう！

2017-01-25 15:32 UTC, knzm commented on src/v2/guide/components.md
> +コンポーネントは Vue.js の最も強力な機能の 1 つです。基本的な HTML 要素を拡張して再利用可能なコードのカプセル化を助けます。ハイレベルには、コンポーネントは Vue.js のコンパイラが指定された振舞いを加えるカスタム要素です。場合によっては、特別な `is` 属性で拡張されたネイティブな HTML 要素の姿をとることもあります。
原文の意図は「抽象度が高い」という意味であって、「高度なレベル」は誤訳だと思います。

2017-01-25 16:22 UTC, kazupon reviewed
そうですね。確かに、文章の文脈を考える、ここでの`at a hight level`の訳は `高度` ではないですね。

`高次`とありますが、普段あまり使わない用語なので、もう少し誰でも分かる一般的な単語を使った方がいいですね。`高い次元では`などとかどうでしょうか。

2017-01-28 13:42 UTC, kazupon approved these changes
とりあえず、大きな問題はないので、一旦マージします。
こちらで細かい修正します。
何かあれば、再度PRなどでお願いします。

翻訳改善ありがとうございました！

2017-01-28 13:42 UTC, merged