[Doc]: deduplicate change detection caveat sections #2043
vuejs/jp.vuejs.org pull request #2092
Opened 2020-03-31 14:29 UTC by satomixx

## 概要

resolve #2043

## 補足

Original:vuejs/vuejs.org@17ab220

2020-04-04 02:16 UTC, kazupon requested changes
レビュー 👀 しました！確認お願いします！ 🙏

2020-04-04 02:16 UTC, kazupon commented on src/v2/guide/reactivity.md
> +ばなりません。例えば:
ここ改行されてしまっているので、原文のように一行でお願いします！ 🙏

2020-04-06 06:44 UTC, satomixx commented on src/v2/guide/reactivity.md
> +ばなりません。例えば:
@kazupon 修正しました! 🙇 
https://github.com/vuejs/jp.vuejs.org/pull/2092/commits/ee8d8d89177f86ee7465dd06cf1a3356276b68cd

2020-04-07 01:16 UTC, kazupon approved these changes

2020-04-07 01:16 UTC, merged