update unit test code examples with Vue Test Utils
vuejs/jp.vuejs.org pull request #2107
Opened 2020-04-21 16:13 UTC by 53able

## 概要

resolve https://github.com/vuejs/jp.vuejs.org/issues/2016
resolve https://github.com/vuejs/jp.vuejs.org/issues/2024

## 補足
#2024 は、 #2016 の差分の修正なので合わせて対応 dae939f しました。

ご確認よろしくお願いします🙇

2020-04-21 23:23 UTC, oohira requested changes
翻訳ありがとうございます！ 👍 
いくつか指摘がありますのでご確認いただけますか？

2020-04-21 23:23 UTC, oohira commented on src/v2/guide/unit-testing.md
> +[Vue Test Utils](https://vue-test-utils.vuejs.org/) を利用して、異なるプロパティを用いた描画結果の検証が可能です。
MUST: 翻訳が追いついていないのが気になりますが、日本語サイトがある場合はそちらにリンクを張ることになっているので、 https://vue-test-utils.vuejs.org/ja/ にしていただけますか

2020-04-21 23:23 UTC, oohira commented on src/v2/guide/unit-testing.md
> +function getMountedComponent (Component, propsData) {
nits: 細かいですが、原文ではメソッド名の後にスペースがないです

```js
function getMountedComponent(Component, propsData) {
```

2020-04-21 23:23 UTC, oohira commented on src/v2/guide/unit-testing.md
> +    expect(
nits: 原文ではここに空行が入っていますので、合わせていただけますか

2020-04-21 23:23 UTC, oohira commented on src/v2/guide/unit-testing.md
> +Vue は[非同期に DOM の更新を行う](reactivity.html#Async-Update-Queue)ため、state の変更に対する DOM の更新に関する検証は、`Vue.nextTick()` が解決した後に行う必要があります。
SHOULD: 今回の翻訳と直接関係がないのですが、リンク先の期待値が `reactivity.html#非同期更新キュー` だと思いますので、もし余力があれば合わせて修正をお願いしてしまってもよいでしょうか。

2020-04-21 23:23 UTC, oohira commented on src/v2/guide/unit-testing.md
> +  // 状態が変化して、DOM の更新をアサート前に "tick" を待つ
* nits: 原文ではこの前にも空行が入っているので、合わせていただけますか？
* IMO: `after state change` は124行目のsetDataを指しているので、元の `state 変更後、` の方が意味が近い気がします。121行目でも `state の更新後、` と表現しているので、`state の変更後、DOM の更新をアサートする前に "tick" を待つ` ぐらいでいかがでしょうか

2020-04-21 23:30 UTC, oohira commented
すみません、1点漏れていました。一応ファイル先頭の `updated: ` の日付も更新いただけますか

2020-04-25 14:00 UTC, 53able commented
@oohira レビューありがとうございます!
ご指摘箇所の修正をご確認お願いします🙏

2020-04-25 14:24 UTC, 53able commented
すみません。
 日本語サイトへのリンク修正が漏れてたところの修正後にデプロイが失敗しているようなので、プレビューを確認できていないです🙏

https://github.com/vuejs/jp.vuejs.org/pull/2107#discussion_r412551163

2020-04-26 12:39 UTC, oohira approved these changes

2020-04-26 12:41 UTC, merged

2020-04-26 12:43 UTC, oohira commented
@53able 修正ありがとうございました。リンクの修正も含めてOKです！ 👍