[WIP] fix: document that Vue uses semver
vuejs/jp.vuejs.org pull request #2117
Opened 2020-04-25 14:19 UTC by 53able

## 概要

resolve https://github.com/vuejs/jp.vuejs.org/issues/2017

## 補足

2020-04-27 11:22 UTC, oohira commented on src/v2/guide/installation.md
> +Vue は、すべての公式プロジェクトにおいてドキュメント化された機能や動作については、[セマンティックバージョニング](https://semver.org/lang/ja/)に準拠しています。ドキュメント化されていない動作や公開されている内容については、[リリースノート](https://github.com/vuejs/vue/releases)に変更点が記載されています。
* nits: リンクと日本語の間に半角スペースを入れたいです。この文書内のほかの箇所もそうなっているので
* SHOULD: `internals` は public に公開されているものではないので、`内部詳細` ぐらいでどうでしょうか

```suggestion
Vue は、すべての公式プロジェクトにおいてドキュメント化された機能や動作については、[セマンティックバージョニング](https://semver.org/lang/ja/) に準拠しています。ドキュメント化されていない動作や公開されている内部詳細については、[リリースノート](https://github.com/vuejs/vue/releases) に変更点が記載されています。
```

2020-04-27 11:23 UTC, oohira requested changes
翻訳ありがとうございました！1箇所ご確認ください 🙇‍♂️

2020-04-27 15:49 UTC, 53able commented on src/v2/guide/installation.md
> +Vue は、すべての公式プロジェクトにおいてドキュメント化された機能や動作については、[セマンティックバージョニング](https://semver.org/lang/ja/)に準拠しています。ドキュメント化されていない動作や公開されている内容については、[リリースノート](https://github.com/vuejs/vue/releases)に変更点が記載されています。
ご指摘ありがとうございます。
リンクと日本語の間のスペースは、文書を一通り見て入れました。
修正は、こちらです 9f751ba

2020-04-29 23:46 UTC, oohira approved these changes

2020-04-29 23:46 UTC, merged

2020-04-29 23:47 UTC, oohira commented
@53able 修正ありがとうございました！ 💯