fix: update more unit test code examples with Vue Test Utils
vuejs/jp.vuejs.org pull request #2121
Opened 2020-04-25 18:48 UTC by 53able

## 概要

resolve #2018

## 補足

https://github.com/vuejs/vuejs.org/commit/83f305616b9bcaf038838851ae1ae449eac68f53 の差分に対応しました。

ご確認よろしくお願いします🙇

2020-04-27 11:31 UTC, oohira requested changes
@53able 先行するPRをマージした影響だと思うのですが、conflictしているのでご確認いただけますか？お手間をとらせてスミマセン 🙏

2020-04-27 15:26 UTC, 53able commented
@oohira ご連絡ありがとうございます
`updated` 属性の変更がぶつかっていましたね💦
解消しましたので、レビューお願いします🙇🏻‍♂️

2020-04-29 23:55 UTC, oohira commented on src/v2/guide/unit-testing.md
> +// Mount the component
一貫性のため、ここも一応翻訳いただいてもよいでしょうか

2020-04-29 23:55 UTC, oohira requested changes
PRありがとうございます。1点だけご確認ください 🙏

2020-05-16 07:30 UTC, kazupon commented
@53able  こちらどうでしょうか？

2020-05-19 04:32 UTC, 53able commented
@oohira @kazupon  すみません。本日対応させていただきます🙇‍♂️

2020-05-20 01:00 UTC, 53able commented
@oohira @kazupon 🙇‍♂️遅くなりました🙏
ご指摘箇所と同じコードブロックのコメントも、一貫性のために ですます 調に修正させていただきました。
レビューお願い致します。
834a4df

2020-05-20 23:30 UTC, oohira approved these changes

2020-05-20 23:31 UTC, oohira commented
@53able 確認OKです。お忙しいところ対応ありがとうございました！

2020-05-20 23:31 UTC, merged