v2.2アップデートにおけるsrc/v2/api/index.mdの変更の翻訳
vuejs/jp.vuejs.org pull request #230
Opened 2017-02-26 14:38 UTC by potato4d

v2.2.0 アップデートにおける、index.mdの複数の変更の翻訳を行いました。
provide / inject辺りが概念としてもややこしく、翻訳に不安があるため、複数人にてレビューしていただけると幸いです。

原文： https://github.com/vuejs/vuejs.org/commit/4f81f9a79652f86f5468f9c337ccd7619d6548c3

2017-02-26 15:09 UTC, kitak commented on src/v2/api/index.md
> +    // `type` は Vue 固有のエラー種別です。（例： どのライフサイクルフックかなど）
```
  // `type` is a Vue-specific error type, e.g. which lifecycle hook
  // the error was found in. Only available in 2.2.0+
```

ここですが、`which lifecycle hook the error was found in` で一文ではないでしょうか？

2017-02-26 15:09 UTC, kitak commented on src/v2/api/index.md
> +  コンポーネントの描画関数とウォッチャにおいて未捕獲のエラーに対してハンドラを割り当てます。ハンドラはエラーと Vue インスタンスが引数に渡されて呼び出されます。
(細かいんですが)「おいて」「に対して」と「て」が続き、少し読みづらく感じました。

`コンポーネントの描画関数とウォッチャにおいて未捕獲のエラーに対し、ハンドラを割り当てます。`

でどうでしょうか？

2017-02-26 18:59 UTC, kazupon requested changes

2017-02-26 18:59 UTC, kazupon commented on src/v2/api/index.md
> +## performance
タイトルも訳しましょう！

2017-02-26 18:59 UTC, kazupon commented on src/v2/api/index.md
> +### productionTip
ここのタイトルも訳しましょう！

2017-02-26 18:59 UTC, kazupon commented on src/v2/api/index.md
> +  > 2.2.0 以降では、 Array とそのインデックスでも動作します。
Arrayも訳しておきましょう！

2017-02-26 18:59 UTC, kazupon commented on src/v2/api/index.md
> +## オプション / 組成
`組成` という訳に違和感を感じます。 `構成` でどうでしょうか？

2017-02-26 18:59 UTC, kazupon commented on src/v2/api/index.md
> +  <p class="tip">`provide` および `inject` は、高度なプラグインやコンポーネントのライブラリのために提供されています。一般的なアプリケーションのコードで利用することは推奨されません。</p>
`primarily` の訳が抜けています。

2017-02-26 18:59 UTC, kazupon commented on src/v2/api/index.md
> +  React に精通している人は、 React のコンテキストの概念と非常によく似ていると捉えると良いでしょう。
原文と同じく、同じパラグラフでオネガイします。

2017-02-26 18:59 UTC, kazupon commented on src/v2/api/index.md
> +  プロバイダとなるオブジェクトには、その子孫に注入可能なプロパティが含まれています。また、このオブジェクトのキーとして、 ES2015 の Symbol を利用することが可能です。
ここも、原文と同じく、同じパラグラフにしてください！

2017-02-26 18:59 UTC, kazupon commented on src/v2/api/index.md
> +  プロバイダとなるコンポーネントは、提供されたプロパティを注入するコンポーネントの親チェーン内である必要があります。
親チェーン(parent chain)、これそのまま訳すと非常に分かりづらいです。

プロバイダと注入する役割を持つコンポーネントつまりインジェクタ(ここではそう呼ぶことにしましょう)はルートなる Vue インスタンス (new Vue)において、それぞれ**木構造**でコンポーネントとして管理されると思います。
ここで言うchain とは、プロバイダとインジェクタを含んだコンポーネント郡で構成されたツリーにおいてプロバイダからインジェクタまでたどれる筋のことを言っていて、その筋においてプロバイダはインジェクタの親であるということを **parent chain**と言っているのだと思います。

なので、日本訳独自に註釈として、

```
プロバイダコンポーネントは、提供されたプロパティを注入するコンポーネント(インジェクタコンポーネント)の親チェーン内である必要があります。(註釈: ここで言う親チェーンとは、コンポーネント郡で構成されるツリー構造において、プロバイダコンポーネントからトップダウンでインジェクタコンポーネントまでたどれる筋のことを表します。)
```

@ktsn 確認と、何か他にいい案があれば助かります！

2017-02-26 18:59 UTC, kazupon commented on src/v2/api/index.md
> +  カスタムコンポーネント内の `v-model` によって利用される prop 及びイベントのカスタマイズを許可します。デフォルトでは、コンポーネントにおける `v-model` は、 `value` を prop として、 `input` をイベントして用います。しかし、チェックボックスやラジオボタンなどの入力タイプを利用する場合は、 `value` prop をその他の目的で利用することが
`prop` は`プロパティ`と訳しましょう！

2017-02-26 18:59 UTC, kazupon commented on src/v2/api/index.md
> +      // これによって、 `value` prop を別の目的で利用することを許可します。
ここのコメントも`prop`を`プロパティ`で訳しましょう！

2017-02-26 18:59 UTC, kazupon commented on src/v2/api/index.md
> +  上の例の場合は、こうなります:
`上の例の場合は、こうなります:` は少しカジュアルすぎるので、`上記の例は、下記になります:｀にしましょう！

2017-02-26 18:59 UTC, kazupon commented on src/v2/api/index.md
> +  コンポーネントが受け取った現在の props を表すオブジェクトです。
`props` は `プロパティ`で訳しましょう！

2017-02-26 18:59 UTC, kazupon commented on src/v2/api/index.md
> +  > 2.2.0 以降では、`<keep-alive>`ツリーの中の全てのネストされたコンポーネントに対して、 `activated` および `deactived` が発火します。
"`<keep-alive>`ツリー" にスペースいれてください！

2017-02-26 19:00 UTC, kazupon commented
レビュー 👀 しました。コメント 💬 の対応お願いします！

2017-02-28 11:28 UTC, potato4d commented
@kazupon 
修正対応いたしました！ご確認お願いいたします。

@kitak @hkdnet 
翻訳の修正ありがとうございます！このページは難しいかと思いながらもやってみたのですが、案の条拙くて申し訳ありません :bow:

2017-03-01 01:42 UTC, kazupon approved these changes
ありがとうございました！
大方よい感じなので、マージしますね。

2017-03-01 01:42 UTC, merged