Tweak installation page
vuejs/jp.vuejs.org pull request #231
Opened 2017-02-28 09:14 UTC by tadyjp

https://github.com/vuejs/vuejs.org/commit/08f08c1cde3a0a91408d88c4e3a3f3b4a074e73c
こちらの差分の適用です

2017-02-28 09:19 UTC, tadyjp commented
`production` を「プロダクション」と訳すか「本番」と訳すか揺れているのでですが、どちらがいいでしょうか？

2017-02-28 10:38 UTC, kazupon requested changes
レビュー 👀 しました。
コメント 💬 の対応お願いします！ 🙏

2017-02-28 10:38 UTC, kazupon commented on src/v2/guide/installation.md
> +Vue.js は意欲的なシングルページアプリケーションをすぐに足場固めするために、[オフィシャル CLI](https://github.com/vuejs/vue-cli) を提供します。それはモダンなフロントエンドのフレームワークのワークフローに対して、Battery-included なビルド手順を提供します。ホットリローディング、保存時のリント、そして本番可能なビルドを実行して準備するの
`batteries-included build setups` の訳ですが、`すぐに利用できるビルド環境のセットアップ` でいかがでしょうか？

`batteries-included` は直訳すると、`電池が付属する`という意味になりますが、これは、おもちゃ買ったときに電池が入っているとすぐに遊べるというシチュエーションなどから来ていると思うので。

2017-02-28 10:38 UTC, kazupon commented on src/v2/guide/installation.md
> +## 様々なビルドの説明
`Explanation of Different Builds` の訳ですが、そのまま訳すとそうなりますが、ここでは Vue.js が提供するビルドファイルについて説明している部分なので、ドキュメント読み手を考えて、`さまざまなビルドについて` という訳にしましょう！

2017-02-28 10:38 UTC, kazupon commented on src/v2/guide/installation.md
> +- **コンパイラ**: テンプレート文字列を JavaScript レンダリング関数にコンパイルするためのコード。
`ですます` 調にしましょう！

2017-02-28 10:38 UTC, kazupon commented on src/v2/guide/installation.md
> +- **ランタイム**: Vue インスタンスの作成やレンダリング、仮想 DOM の変更などのためのコード。基本的にコンパイラを除く全てのもの。
`ですます` 調にしましょう！

2017-02-28 10:38 UTC, kazupon commented on src/v2/guide/installation.md
> +- **[UMD](https://github.com/umdjs/umd)**: UMD ビルドは `<script>` タグによってブラウザに直接利用される。[https://unpkg.com/vue](https://unpkg.com/vue) の Unpkg CDN からの既定のファイルは ランタイム + コンパイラ UMD ビルド (`vue.js`) である。
`ですます` 調にしましょう！

2017-02-28 10:38 UTC, kazupon commented on src/v2/guide/installation.md
> +- **[CommonJS](http://wiki.commonjs.org/wiki/Modules/1.1)**: CommonJS ビルドは [browserify](http://browserify.org/) や [webpack 1](https://webpack.github.io) のような古いバンドラでの利用を意図している。これらのバンドラ (`pkg.main`) のた
`ですます` 調にしましょう！

2017-02-28 10:38 UTC, kazupon commented on src/v2/guide/installation.md
> +- **[ES Module](http://exploringjs.com/es6/ch_modules.html)**: ES module ビルドは [webpack 2](https://webpack.js.org) や [rollup](http://rollupjs.org/)のような最新のバンドラでの利用を意図している。これらのバンドラ (`pkg.module`) のための既定
`ですます` 調にしましょう！

2017-02-28 10:41 UTC, kazupon commented
>production を「プロダクション」と訳すか「本番」と訳すか揺れているのでですが、どちらがいいでしょうか？

これについては、本番で統一しましょう！

2017-02-28 23:40 UTC, tadyjp commented
@kazupon 修正しました！

2017-03-01 01:43 UTC, kazupon approved these changes
ありがとうございました！
マージしますね！

2017-03-01 01:43 UTC, merged