fix mistranslations in `render functions`
vuejs/jp.vuejs.org pull request #292
Opened 2017-08-02 13:14 UTC by wonderful-panda

描画関数のページ内で、誤訳と思われる箇所を修正しました。

2017-08-02 13:30 UTC, chi-bd commented on src/v2/guide/render-function.md
> +これは render 関数では JavaScript の `if` / `else` と `map` を使って書き換えることができます。
ここは元の訳（「の中で」）のほうが適切と思われます："in"を生かす
```
This could be rewritten with JavaScript’s if/else and map in a render function:
```

2017-08-02 13:48 UTC, wonderful-panda commented on src/v2/guide/render-function.md
> +これは render 関数では JavaScript の `if` / `else` と `map` を使って書き換えることができます。
outに対するinなら「中で」ですが、「in template」に対する「in render function」なので「render関数においては」の方がニュアンスとして近いと思うんですよね。

2017-08-02 13:56 UTC, kazupon commented on src/v2/guide/render-function.md
> +これは render 関数では JavaScript の `if` / `else` と `map` を使って書き換えることができます。
そうですね。`in` を素朴に訳すと物理空間の `〜の中`と訳しますが、この文脈では、`〜においては`の方が読んでいて自然な気がしますね。

2017-08-03 02:13 UTC, kazupon requested changes

2017-08-03 02:13 UTC, kazupon commented on src/v2/guide/render-function.md
> +  // カスタムディレクティブ。バインディングのoldValueは、
翻訳ガイドラインに従い、
`oldValue`の前後半角スペースお願いします！ 🙏

2017-08-03 12:35 UTC, wonderful-panda commented on src/v2/guide/render-function.md
> +  // カスタムディレクティブ。バインディングのoldValueは、
ご指摘ありがとうございます。

この部分ですが、なるべく原文(`the binding's oldValue cannot be set, as Vue keeps track of it for you.`)に忠実にと思ったのですがやっぱり分かりにくい気がするので、

`バインディングの oldValue についてはあなたの代わりに Vue が面倒をみるので、設定することはできません`

くらいの意訳にしてしまいたいのですが、いかがでしょうか？

2017-08-03 12:40 UTC, kazupon commented on src/v2/guide/render-function.md
> +  // カスタムディレクティブ。バインディングのoldValueは、
LGTM 👍
おまかせします？

2017-08-03 12:41 UTC, kazupon commented on src/v2/guide/render-function.md
> +  // カスタムディレクティブ。バインディングのoldValueは、
おまかせします！

2017-08-03 12:57 UTC, wonderful-panda commented
コメントいただいた箇所を修正しました。

2017-08-03 13:37 UTC, kazupon approved these changes

2017-08-03 13:37 UTC, merged

2017-08-03 13:37 UTC, kazupon commented
ありがとうございました！🙏