Add virtual dom description to render functions page
vuejs/jp.vuejs.org pull request #326
Opened 2017-09-04 15:24 UTC by re-fort

Cherry-picked from
https://github.com/vuejs/vuejs.org/commit/eef32831073173d5e8144a00aecbd29e25697134

2017-09-04 16:48 UTC, kazupon requested changes
レビュー 👀 しました。コメント 💬 の対応お願いします！

2017-09-04 16:48 UTC, kazupon commented on src/v2/guide/render-function.md
> +Vue は**実際の DOM に加える必要がある変更を追跡する**仮想DOM **を構築することでこれを達成します。この行を詳しく見てみましょう:
強調`**`がtypoしていたので、以下のように、読みやすやも考慮して読点いれてみました。

```
Vue は、実際の DOM に加える必要がある変更を追跡する**仮想 DOM** を構築することで、これを達成します。
```

2017-09-05 14:03 UTC, re-fort commented on src/v2/guide/render-function.md
> +Vue は**実際の DOM に加える必要がある変更を追跡する**仮想DOM **を構築することでこれを達成します。この行を詳しく見てみましょう:
ありがとうございます！
対応しました！

2017-09-05 14:35 UTC, kazupon approved these changes

2017-09-05 14:35 UTC, kazupon commented
ありがとうございます😊

2017-09-05 14:35 UTC, merged