Readd reactivity page in new internals section
vuejs/jp.vuejs.org pull request #329
Opened 2017-09-08 13:19 UTC by re-fort

Cherry-picked from
https://github.com/vuejs/vuejs.org/commit/3990ea1f7c3cef9d23571ae7b7267716a254af26

2017-09-08 15:48 UTC, kazupon requested changes
レビュー 👀 しました！
コメント 💬 の対応お願いします！

2017-09-08 15:48 UTC, kazupon commented on themes/vue/layout/partials/toc.ejs
> +                <li><h3>インターナル</h3></li>
`internals`の訳ですが、Vueの内部のものに関するものなので、一般的な訳で使われる`内部`にしておきましょう！

2017-09-11 07:09 UTC, re-fort commented on themes/vue/layout/partials/toc.ejs
> +                <li><h3>インターナル</h3></li>
了解です！修正しました！

2017-09-11 15:18 UTC, kazupon approved these changes
👍

2017-09-11 15:18 UTC, merged