Pick up some changes
vuejs/jp.vuejs.org pull request #330
Opened 2017-09-08 14:18 UTC by re-fort

Cherry-picked from
https://github.com/vuejs/vuejs.org/commit/e51d0ef921217889901169fe342631e71805db74
https://github.com/vuejs/vuejs.org/commit/2e4d65f87f5a0c2980c0aa8d297504df94c35ee8
https://github.com/vuejs/vuejs.org/commit/7636c347c407289a4c6145c154e4a6601c1173b6
https://github.com/vuejs/vuejs.org/commit/19d8fa77ac4c3f67e0a7e81cff879cbfa23eddb5
https://github.com/vuejs/vuejs.org/commit/60731eff55c393adbb0da43c61a975edfd084386

2017-09-08 15:50 UTC, kazupon requested changes
レビュー 👀 しました！
コメント 💬 の対応お願いします！

2017-09-08 15:50 UTC, kazupon commented on src/v2/guide/deployment.md
> +- [Webpack + vue-loader](https://vue-loader.vuejs.org/en/configurations/extract-css.html) (`vue-cli` の webpack テンプレートは既に設定済み)
日本語向けなので、下記日本語訳のvue-loaderのリンク先にしましょう！
https://vue-loader.vuejs.org/ja/configurations/extract-css.html

2017-09-11 07:17 UTC, re-fort commented on src/v2/guide/deployment.md
> +- [Webpack + vue-loader](https://vue-loader.vuejs.org/en/configurations/extract-css.html) (`vue-cli` の webpack テンプレートは既に設定済み)
ありがとうございます！修正しました！

2017-09-11 15:17 UTC, kazupon approved these changes
👍

2017-09-11 15:17 UTC, merged