公式blog/Upcoming TypeScript Changes in Vue 2.5の翻訳
vuejs/jp.vuejs.org pull request #355
Opened 2017-09-23 12:53 UTC by chi-bd

https://medium.com/the-vue-point/upcoming-typescript-changes-in-vue-2-5-e9bd7e2ecf08
の翻訳です

2017-09-23 15:54 UTC, kazupon requested changes
レビュー 👀 して、コメント 💬 しました。
対応お願いします！ 🙏

2017-09-23 15:54 UTC, kazupon commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +title: Vue 2.5 での来る TypeScript の変更
`やって来る Vue 2.5 での TypeScript の変更` とかどうでしょう？
こちらの方が興味をそそるタイトルになると思います。

2017-09-23 15:54 UTC, kazupon commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +私たちは Vue 2.0 のリリース以来、よりよい TypeScript 統合を求められています。リリース以来、私たちはほとんどのコアライブラリ (`vue`, `vue-router`, `vuex`) のための公式の Typescript の型宣言を含めました。しかし、箱から出したままの Vue API を使用するとき、現在の統合は幾分不足しています。たとえば、 TypeScript は V
`out-of-the-box` は `すぐに使える` という意味で使われるのでそちらにしましょう！

2017-09-23 15:54 UTC, kazupon commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +- デフォルトの Vue API を使用する際の `this` の適切な型推論。これは単一ファイルのコンポーネントの中でも動作します！
`single-file component` は `単一ファイルコンポーネント` に訳しておきましょう！

2017-09-23 15:54 UTC, kazupon commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +- `as ComponentOptions<Something>`でコンポーネントオプションに注釈を付ける場合、`computed`, `watch`, `render` の ThisType とライフサイクルのフックは手作業で型の注釈を付ける必要があります。
`annotations` は日本においてもそのままカタカナ用語で読んでいる事が多いので、 `注釈` ではなく、`アノテーション` で訳しても通じると思います。

2017-09-24 09:14 UTC, ktsn commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +## 型宣言の改善
typings, type declaration, type definition はすべて型定義と訳したほうが良いと思います。TypeScript の d.ts はほとんど日本語だと型定義と呼ばれているように思います。

2017-09-24 09:14 UTC, ktsn commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +私たちは Vue 2.0 のリリース以来、よりよい TypeScript 統合を求められています。リリース以来、私たちはほとんどのコアライブラリ (`vue`, `vue-router`, `vuex`) のための公式の Typescript の型宣言を含めました。しかし、すぐに使える Vue API を使用するとき、現在の統合は幾分不足しています。たとえば、 TypeScript は Vue
out-of-the-box は直訳するとすぐに使えるですが、日本語にすると意図がぼやけるので、「Vue API をそのまま使用するとき」にするのはいかがでしょうか？

2017-09-24 09:14 UTC, ktsn commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +- 最も重要なのは、<b>これらの改善点が素の JavaScript ユーザーにとっても有益だということです！</b> VSCode を素晴らしい [Vetur](https://github.com/vuejs/vetur) 拡張機能とともに使用している場合、 Vue コンポーネントで素の JavaScript を使用すると、自動補完候補が大幅に改善され、ヒントも入力されるようになります！これ
> `<b>これらの改善点が素の JavaScript ユーザーにとっても有益だということです！</b>`

明らかに強調の意図なので `<strong>` (markdown の `**XXX**`) の方が良いのではないでしょうか。

2017-09-24 09:14 UTC, ktsn commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +- 最も重要なのは、<b>これらの改善点が素の JavaScript ユーザーにとっても有益だということです！</b> VSCode を素晴らしい [Vetur](https://github.com/vuejs/vetur) 拡張機能とともに使用している場合、 Vue コンポーネントで素の JavaScript を使用すると、自動補完候補が大幅に改善され、ヒントも入力されるようになります！これ
> これは vue-language-server のおかげで、 Vue コンポーネントの分析を担当する内部パッケージが

vue-language-server === Vue のコンポーネントの分析を担当する内部パッケージ です。原文では後者は vue-language-server に対する修飾節になっているかと思います。
「これは Vue コンポーネントの分析を担当する内部パッケージである vue-language-server のおかげで、」でいかがでしょう？

2017-09-24 09:14 UTC, ktsn commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +- 最も重要なのは、<b>これらの改善点が素の JavaScript ユーザーにとっても有益だということです！</b> VSCode を素晴らしい [Vetur](https://github.com/vuejs/vetur) 拡張機能とともに使用している場合、 Vue コンポーネントで素の JavaScript を使用すると、自動補完候補が大幅に改善され、ヒントも入力されるようになります！これ
Language Server Protocol はまだあまり和訳して使われている例を見かけないので括弧で元の語を書いたほうが良さそうです。

2017-09-24 09:14 UTC, ktsn commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +![Action 中の VSCode + Vetur + 新しい型宣言](https://cdn-images-1.medium.com/max/2000/1*ftKUpzYGIzn1eS87JcBS8Q.gif)
In action はおそらく「動作中の」みたいな意味じゃないですかねー。

2017-09-24 09:14 UTC, ktsn commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +興味のある方は、[この実験プロジェクト](https://github.com/octref/veturpack/tree/new-types) を clone して（ `new-types` ブランチをチェックアウトしてください） VSCode + Vetur で開くことで今すぐ試すことができます！
> この実験プロジェクト

experimental と誤解される恐れもあるので、(playground project) と書いても良いかもしれません。

2017-09-24 09:14 UTC, ktsn commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +- 以前は、`tsconfig.json` に `“allowSyntheticDefaultImports”: true` を指定することでどこでも ES 形式のインポート(`import Vue from ‘vue’`)を使用することをお勧めしていました。新しいタイピングは正式に ES スタイルの import/export 構文に移行するため、 config はもはや不要となり全てのケース
> 以前は、~~ お勧めしていました

今は違うような印象を持ってしまうので、「以前から、~~ お勧めしています」にするのはいかがでしょうか。

2017-09-24 09:14 UTC, ktsn commented on src/contribution/index.md
> +Upcoming TypeScript Changes in Vue 2.5 | Vue 2.5 での来る TypeScript の変更 | [chi-bd](https://github.com/chi-bd)
ここのタイトルも「やって来る Vue 2.5 での TypeScript の変更」に修正する必要ありますよね？

2017-09-24 13:01 UTC, chi-bd commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +興味のある方は、[この実験プロジェクト](https://github.com/octref/veturpack/tree/new-types) を clone して（ `new-types` ブランチをチェックアウトしてください） VSCode + Vetur で開くことで今すぐ試すことができます！
直訳の「遊び場プロジェクト」も訳候補だったのですが、どう思いますか？

2017-09-24 13:51 UTC, ktsn commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +興味のある方は、[この実験プロジェクト](https://github.com/octref/veturpack/tree/new-types) を clone して（ `new-types` ブランチをチェックアウトしてください） VSCode + Vetur で開くことで今すぐ試すことができます！
その訳でも良いと思いますー。

2017-09-25 00:27 UTC, kazupon commented on src/_posts/upcoming-typeScript-changes-in-vue-2.5.md
> +私たちは Vue 2.0 のリリース以来、よりよい TypeScript 統合を求められています。リリース以来、私たちはほとんどのコアライブラリ (`vue`, `vue-router`, `vuex`) のための公式の Typescript の型宣言を含めました。しかし、すぐに使える Vue API を使用するとき、現在の統合は幾分不足しています。たとえば、 TypeScript は Vue
確かに。🙂

2017-09-25 13:36 UTC, ktsn approved these changes
良いと思います！ 👍

2017-09-26 08:57 UTC, merged

2017-09-26 08:58 UTC, kazupon commented
ありがとうございました！