translating style-guide: Priority B (#373)
vuejs/jp.vuejs.org pull request #381
Opened 2017-10-03 11:36 UTC by wonderful-panda

Self-closing components までを訳しました。
レビューお願いします。

- Bad / Good はとりあえず「悪い例」「良い例」としています。統一する必要があると思うので、変えた方がよければご指摘ください。

- コメントで「自信なし」と書いているところ (`**what's considered "highest-level" will be contextual to your app**`) が、よく分かりませんでした。

2017-10-05 09:48 UTC, kazupon requested changes
レビュー 👀し、コメント 💬 しました！
対応お願いします 🙏

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
> +### シングルファイルコンポーネントのファイル名の形式 <sup data-p="b">強く推奨</sup>
`Single-file component`の訳ですが、jp.vuejs.org 公式ドキュメントと訳語を整合したいので、`単一ファイルコンポーネント`でお願いします！ 🙏

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
> +### シングルファイルコンポーネントのファイル名の形式 <sup data-p="b">強く推奨</sup>
以降で訳されたものについても、統一お願いします！

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
> +### 基本コンポーネントの名前 <sup data-p="b">強く推奨</sup>
日本のプログラミング言語のclassの説明では Base Class の `Base` は、`基底` という訳語がよく使われて馴染みが深いと思うので、そちらでお願いします！ 🙏

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
> +### 基本コンポーネントの名前 <sup data-p="b">強く推奨</sup>
以降で訳されたものについても、統一お願いします！

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
> +- HTML要素、
[こちらガイドライン](https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#半角スペースでアルファベット両端を入れて読みやすく)に従って半角スペースお願いします。 🙏 
`HTML 要素`

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
> +- これらのコンポーネントはとても頻繁に使われるので、あらゆる場所でimportするよりも単純にグローバルにしてしまいたいと思うかもしれません。プレフィックスによって、それをWebpackでできるようになります。
[こちらガイドライン](https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#半角スペースでアルファベット両端を入れて読みやすく)に従って半角スペースお願いします。 🙏 
- `で import するよりも`
- `それを Webpack で`

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
> +もしpropsを追加する必要があることに気づいたのなら、それは _現時点で_ ページごとに一回しか使われていないだけで実際には再利用可能なコンポーネントであることを示すよい目印です。
ここの`props`もそうですね。

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
> +これらのコンポーネントは、アプリケーション内のコンテキストではなく、アプリケーションに対して固有のため、決してpropsを受け入れることはありません。
propsの訳ですが、コンポーネントのプロパティを意味しているので、普通に訳しましょう！

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
> +### 強い関連性を持つコンポーネントどうしの名前 <sup data-p="b">強く推奨</sup>
`Tightly coupled` はソフトウェア用語でよく使う `密結合` の方がしっくりくるので、それでお願いします。 🙏

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
> +### 強い関連性を持つコンポーネントどうしの名前 <sup data-p="b">強く推奨</sup>
以降で訳されたものについても、統一お願いします！

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
> +XXX: 強調部分自信なし
この訳でいいと思います。

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
> +### セルフクロージング形式のコンポーネント <sup data-p="b">強く推奨</sup>
`Self-closing`ですが、現状下記のURLでは、`自己終了`にしているので、そちらでお願いします。
https://jp.vuejs.org/v2/guide/components.html#コンポーネントの命名の慣習

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
> +### セルフクロージング形式のコンポーネント <sup data-p="b">強く推奨</sup>
以降で訳されたものについても、統一お願いします！

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
> +**中身を持たないコンポーネントは、 [シングルファイルコンポーネント](../guide/single-file-components.html) 、文字列テンプレート、および [JSX](render-function.html#JSX) の中ではセルフクロージング形式で書くべきです。ただし、DOMテンプレート内ではそうしてはいけません。**
[こちらガイドライン](https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#半角スペースでアルファベット両端を入れて読みやすく)に従って半角スペースお願いします。 🙏 
`ただし、DOM テンプレート`

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
>  <!-- In single-file components, string templates, and JSX -->
HTML コメントの訳もお願いします！ 🙏

2017-10-05 09:48 UTC, kazupon commented on src/v2/style-guide/index.md
>  <!-- In single-file components, string templates, and JSX -->
HTML コメントの訳もお願いします！ 🙏

2017-10-05 09:50 UTC, kazupon commented
>Bad / Good はとりあえず「悪い例」「良い例」としています。統一する必要があると思うので、変えた方がよければご指摘ください。

こちらついては、これの訳で問題ないのでこれでいきましょう！
/cc @shika358 @zakuro9715 @hisako135

2017-10-06 12:34 UTC, wonderful-panda commented
指摘箇所を修正しました。
ついでに２か所ほど、少し表現を変えています。

「最高レベル」として尊重されるものは、アプリケーションの文脈になる
↓
何を「最高レベル」として尊重するかがアプリケーションの文脈になる

すべての検索コンポーネントを search ディレクトリの下にネストし、すべての設定コンポーネントを settings ディレクトリに置く
↓
すべての検索コンポーネントは search ディレクトリの下に、すべての設定コンポーネントは settings ディレクトリの下にネストする

2017-10-06 12:37 UTC, wonderful-panda commented
すみません。一か所修正漏れがありました

2017-10-07 01:33 UTC, wonderful-panda commented
後半の訳も終わったのですが、このままこのPRに追加してもかまわないでしょうか？

2017-10-07 04:42 UTC, kazupon commented
ok 🙆 です！

2017-10-07 05:43 UTC, wonderful-panda commented
pushしました。よろしくお願いします。

原文で気になった箇所(↓)については、本家の方にissueを投げています。
```
XXX:
    in-DOM components は in-DOM templates の間違いではないかと思われる
    #Component-name-casing-in-templates は正しいリンクになっていない。正しくは #Component-name-casing-in-templates-strongly-recommended
```

2017-10-07 12:56 UTC, wonderful-panda commented
すみません。いくつかミスがあったので修正しました。

2017-10-07 14:16 UTC, kazupon requested changes
レビュー 👀 し、コメント 💬 しておきました。
対応お願いします！

2017-10-07 14:16 UTC, kazupon commented on src/v2/style-guide/index.md
> +
`__Easier to read__` の部分、漏れてませんか？

2017-10-07 22:03 UTC, wonderful-panda commented
修正しました

2017-10-08 08:58 UTC, kazupon reviewed
本家のStyle Guideの更新に伴い、jp.vuejs.orgのリポジトリに取り込みました。それとも無い、いくつか対応が必要な部分があるので、お手数ですがよろしくお願いします！ 🙏

2017-10-08 08:58 UTC, kazupon commented on src/v2/style-guide/index.md
> +**In most projects, component names should always be PascalCase in [single-file components](../guide/single-file-components.html) and string templates - but kebab-case in DOM templates.**
すいません、本家からstyle guideの取り込みでconflictの解消時に、この部分こちらで翻訳漏れてしましました。 🙇 
こちら、すいませんが翻訳お願いします！ 🙏

2017-10-08 08:58 UTC, kazupon commented on src/v2/style-guide/index.md
> +- These applications always include many in-DOM templates, where [kebab-case **must** be used](#Component-name-casing-in-templates-strongly-recommended).
https://github.com/vuejs/vuejs.org/issues/1194 で指摘していた部分、間違っていたようで修正され、本家からjaに取り込みました。この部分、対応お願いします！ 🙏

2017-10-08 21:26 UTC, wonderful-panda commented
対応しました。

2017-10-09 01:27 UTC, kazupon reviewed
👍 です！

2017-10-09 01:27 UTC, kazupon approved these changes

2017-10-09 01:27 UTC, merged

2017-10-09 01:28 UTC, kazupon commented
翻訳ありがとうございました！