rewrite into plain Japanese (guide/installation.html#CLI)
vuejs/jp.vuejs.org pull request #395
Opened 2017-10-10 13:17 UTC by reppets

複雑だった部分を平易な表現に置き換えました。

2017-10-10 14:06 UTC, re-fort requested changes
改善ありがとうございます！
思ったことを記載いたしました〜

2017-10-10 14:06 UTC, re-fort commented on src/v2/guide/installation.md
> +意欲的なシングルページアプリケーション開発のための足場を素早く組むために、Vue.js では[オフィシャル CLI](https://github.com/vuejs/vue-cli) を提供します。この CLI にはモダンなフロントエンドワークフローのための、すぐに使えるビルド設定を用意しています。ホットリロード、保存時リント、製品リリース用ビルドができるようになるまでに、ほんの数分しかかかり
`ambitious` は「意欲的な」というよりは「大規模な」という意味で使われていると思います！

2017-10-10 14:06 UTC, re-fort commented on src/v2/guide/installation.md
> +意欲的なシングルページアプリケーション開発のための足場を素早く組むために、Vue.js では[オフィシャル CLI](https://github.com/vuejs/vue-cli) を提供します。この CLI にはモダンなフロントエンドワークフローのための、すぐに使えるビルド設定を用意しています。ホットリロード、保存時リント、製品リリース用ビルドができるようになるまでに、ほんの数分しかかかり
細かくてすみませんが、`保存時リント`は元の`保存時リント`の方がわかりやすいかなーと思います！

2017-10-11 14:06 UTC, reppets commented
レビューありがとうございます。
修正しました。

2017-10-11 14:08 UTC, re-fort approved these changes

2017-10-11 14:08 UTC, re-fort commented
ありがとうございます！😍

2017-10-11 14:09 UTC, merged