公式blog/Vue 2.5 releasedの翻訳
vuejs/jp.vuejs.org pull request #407
Opened 2017-10-14 07:11 UTC by chi-bd

https://medium.com/the-vue-point/vue-2-5-released-14bd65bf030b
の翻訳です

2017-10-14 09:13 UTC, chi-bd commented
うーむ、CIでエラーが出ているようなのですが何がダメかは表示されない（Progress Circleが回ったまま）ので対処のしようがないです。

2017-10-14 13:18 UTC, re-fort commented
@chi-bd 
lintで落ちてるみたいです
詳細リンクから確認できますよ〜
(それか手元で`npm run lint`でも)
https://circleci.com/gh/vuejs/jp.vuejs.org/1384?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

2017-10-14 15:57 UTC, kazupon requested changes
いつもありがとうございます！ 👍 
いいと思います。

CI で ESLint のエラーがでているので、修正してお願いします！ 🙏

2017-10-15 02:16 UTC, chi-bd commented
@re-fort 
そのリンクにアクセスしてもエラー箇所と思われる"npm test"でProgress Circleが回ったまま手がかりとなるようなものは何も表示されない、という意味でした。
"v $npm test"の"v"を押していったん閉じる＆">"を押下して開き直す、の操作でようやくエラーが見えるようになりました。

ちなみに手元の"npm run test"では、今指摘されている”」"の前の空白が無いと逆にエラーになるのですが、ルールの最新化はどうやって行えばいいですか？

2017-10-15 03:22 UTC, re-fort commented
@chi-bd 
そういうことだったんですね、GitHubの下部に表示されてる部分の話だと思っていました:bow:
Circle CI側の不具合ですかね...

ルールの最新化は`npm install`で行われるはずです
実行前後で`node_modules`以下にある`textlint-checker-for-vuejs-jp-docs`のpackagae.jsonの`_resolved`の値が更新されていれば正しく更新できています

lintに関しては`textlint-plugin-JTF-style`と整合性が取れていなかったので、全角括弧を通すよう
`textlint-checker-for-vuejs-jp-docs`にpull requestを投げました〜

2017-10-15 04:14 UTC, kazupon approved these changes

2017-10-15 04:15 UTC, kazupon commented
@chi-bd 対応ありがとうございました！問題ないので、これでマージしますね。

@re-fort Vue.js日本語翻訳ガイドラインと整合できてきない件の対応ありがとうございます！PRみますね！

2017-10-15 04:15 UTC, merged