Translate Priority D Rules on style-guide
vuejs/jp.vuejs.org pull request #416
Opened 2017-10-31 09:35 UTC by zakuro9715

お待たせしてしまいました 🙇 

レビューよろしくお願いします

2017-10-31 14:30 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
対応お願いします！

2017-10-31 14:30 UTC, kazupon commented on src/v2/style-guide/index.md
> +## 優先度 D のルール: 慎重に使用（危険をはらんだパターン）
`Potentially`の訳ですが、`はらんだ`という訳は性関連を彷彿させるような訳なので、`潜在的`などのような訳でお願いします。

2017-10-31 14:30 UTC, kazupon commented on src/v2/style-guide/index.md
>  #### Bad
`Bad`/`Good`は、ぞれぞれ既に他の方の訳で`悪い例`/`良い例`にしているのでそれでお願いします。:pray:

2017-10-31 14:30 UTC, kazupon commented on src/v2/style-guide/index.md
> +## 優先度 D のルール: 慎重に使用（危険をはらんだパターン）
`Use with Caution`ですが、素朴に訳すとまさに`慎重に使用`なのですが、`使用注意`の方が語呂的にいいので、それで統一しましょう！

2017-10-31 14:30 UTC, kazupon commented on src/v2/style-guide/index.md
> +### `key` を使わない `v-if`/`v-if-else`/`v-else` <sup data-p="d">慎重に使用</sup>
ここの`use with caution`もそうですね。以降に登場するところも`使用注意`でお願いします！

2017-10-31 14:30 UTC, kazupon commented on src/v2/style-guide/index.md
> +理想的な Vue アプリケーションでは、プロパティは下がり、イベントは上がります。この習慣に従えば、コンポーネントの理解が簡単になります。ですが、プロパティの変化や `this.$parent` が、深く結合している2つのコンポーネントを単純化できるようなエッジケースも存在します。
`props down, events up`の訳ですが、訳すと返ってわかりにくくなるので、ここでは下記URLのように原文のままとしておいてください。
https://jp.vuejs.org/v2/guide/components.html#コンポーネントの構成

2017-11-02 17:39 UTC, potato4d commented on src/v2/style-guide/index.md
> +### 暗黙的な親子間のコミュニケーション <sup data-p="d">慎重に使用</sup>
提案）
あくまでも個人的な印象ですが、コミュニケーションと訳してしまうよりも、イベントやデータの通信処理のことですので、「伝達」や「やりとり」みたいな形のほうが崩しすぎず読みやすいかもしれないなぁと思いました。

@zakuro9715 さん側でより適切と思うほうでお願いします！

2017-11-02 17:39 UTC, potato4d commented on src/v2/style-guide/index.md
> +**親子間のコミュニケーションは、`this.$parent` や変化するプロパティよりも、プロパティとイベントが推奨されます。**
こちらも上記同様です。

2017-11-03 08:41 UTC, zakuro9715 commented on src/v2/style-guide/index.md
> +### 暗黙的な親子間のコミュニケーション <sup data-p="d">慎重に使用</sup>
双方向通信のイメージでコミュニケーションとしたのですが、たしかに「やりとり」のほうがわかりやすいですね！ 「伝達」だと自分のイメージとは少し違うので、「やりとり」にします。

2017-11-03 08:49 UTC, potato4d approved these changes
良いと思います！

2017-11-03 23:32 UTC, kazupon approved these changes

2017-11-03 23:32 UTC, merged

2017-11-03 23:32 UTC, kazupon commented
翻訳ありがとうございました！ 🌐