update CONTRIBUTING.md
vuejs/jp.vuejs.org pull request #479
Opened 2017-11-24 10:24 UTC by kazupon

2017-11-24 13:21 UTC, re-fort requested changes
さっそくありがとうございます！
流れはOKだと思います！

2017-11-24 13:21 UTC, re-fort commented on CONTRIBUTING.md
> +12. レビュー :eyes: で OK :ok_womain: ならば、マージされて内容がデプロイされてドキュメントに反映されます! :tada:
typoです
ok_woman

2017-11-24 13:23 UTC, re-fort commented
@kazupon self assignできる人たちは、そのままself assignして更新する流れでよいでしょうか？

2017-11-24 22:01 UTC, kazupon commented
@re-fort 
レビューありがとうございます！
`self assign`については記載しておきました！

2017-11-25 00:26 UTC, re-fort approved these changes
:ok_woman:

2017-11-25 14:40 UTC, merged