Tweak v-bind boolean example
vuejs/jp.vuejs.org pull request #502
Opened 2017-12-03 07:39 UTC by re-fort

This PR resolves #465

2017-12-03 17:22 UTC, kazupon requested changes
レビュー 👀 しました！コメント 💬 の対応お願いします！:pray:

2017-12-03 17:22 UTC, kazupon commented on src/v2/guide/syntax.md
> +`isButtonDisabled` が `null`、`undefined`、または `false` の値を持つ場合、`disabled` 属性はレンダリングされた `<button>` 要素に含められません。
`render`は`描画`で役してきているので、`rendered`は`描画された`で統一お願いします！

2017-12-04 01:48 UTC, re-fort commented on src/v2/guide/syntax.md
> +`isButtonDisabled` が `null`、`undefined`、または `false` の値を持つ場合、`disabled` 属性はレンダリングされた `<button>` 要素に含められません。
OKです！

2017-12-04 02:03 UTC, re-fort commented
@kazupon 統一しました！

2017-12-04 02:18 UTC, kazupon approved these changes
👍

2017-12-04 02:18 UTC, merged