Adding Why Vue.js video to Introduction page
vuejs/jp.vuejs.org pull request #641
Opened 2018-01-16 13:35 UTC by re-fort

This PR resolves #606

2018-01-16 13:38 UTC, re-fort commented on src/v2/guide/index.md
> +Vue について深く知る前にもっと学びたい場合、中心となる原則とサンプルプロジェクトを説明する<a id="modal-player"  href="javascript:;">ビデオを作成しました。</a>
原文は
`If you’d like to learn more about Vue before diving in, we created a video walking through the core principles and a sample project.`
です。
原文に引きづられて日本語訳もちょっと不自然になってます。

2018-01-17 01:51 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
確認お願いします。 🙏

2018-01-17 01:51 UTC, kazupon commented on src/v2/guide/index.md
> +Vue について深く知る前にもっと学びたい場合、中心となる原則とサンプルプロジェクトを説明する<a id="modal-player"  href="javascript:;">ビデオを作成しました。</a>
`core`は`中心`ではなく`中核`の方が違和感ないに感じます。

ここでは、以下のように少し意訳した方が、前後の流れ的に分かりやすい気がします。

```
あなたが Vue についてもっと深く学ぶ前に概要を知りたいのなら、中核となる原則とサンプルプロジェクトを元に説明するビデオを作成しているので、それを見るとよいでしょう。
```

2018-01-17 14:41 UTC, re-fort commented on src/v2/guide/index.md
> +Vue について深く知る前にもっと学びたい場合、中心となる原則とサンプルプロジェクトを説明する<a id="modal-player"  href="javascript:;">ビデオを作成しました。</a>
ありがとうございます！
意訳した文に変更しました！
とりあえず原文に忠実に、と思ってましたが、こういうのは意訳するようにします！

2018-01-17 15:14 UTC, kazupon approved these changes

2018-01-17 15:15 UTC, merged