translate of `Clariy unit testing resources` commit
vuejs/jp.vuejs.org pull request #802
Opened 2018-03-19 16:53 UTC by kazupon

closes #762

2018-03-19 16:54 UTC, kazupon commented on src/v2/guide/unit-testing.md
> +Vue の単体テストに関する詳細情報については、[vue-test-utils](https://vue-test-utils.vuejs.org/en/) とクックブックエントリの [unit testing vue components](https://vuejs.org/v2/cookbook/unit-testing-vue-components.html) について確認してください。
`unit testing vue components` についてはまだ、翻訳されていないので、そのままにしておきました。

2018-03-20 02:32 UTC, re-fort commented on src/v2/guide/unit-testing.md
> +Vue の単体テストに関する詳細情報については、[vue-test-utils](https://vue-test-utils.vuejs.org/en/) とクックブックエントリの [unit testing vue components](https://vuejs.org/v2/cookbook/unit-testing-vue-components.html) について確認してください。
よいとおもいます👍
vue-test-utilsのリンクは日本語サイトにしたほうが親切だとおもいます！

2018-03-20 02:34 UTC, re-fort requested changes
ありがとうございます！
いってん変更したほうが良いかなーと思う点があるので、確認お願いします🙏

2018-03-20 05:04 UTC, kazupon commented
@re-fort レビューありがとうございました！こちら対応しました！

2018-03-20 05:09 UTC, re-fort approved these changes
ありがとうございます！

2018-03-20 05:10 UTC, merged