[WIP] Translate 'Creating custom scroll directives'
vuejs/jp.vuejs.org pull request #859
Opened 2018-03-30 13:02 UTC by pipopotamasu

2018-03-31 16:09 UTC, pipopotamasu commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +一貫したサイトを作成する過程で、様々な箇所で同じアニメーションロジックを再利用していることに気づくかもしれません。シンプルなロジックに思えますが、再利用し辛いカスタムディレクティブを作成していたことでしょう。何も考えずに再利用すれば、使用の度に「ほんの」些細な変更を必要とすることになります。
`a cohesive site`というものが何だかわからないです。
文脈から適当に`一貫したサイト`という風に訳してみましたがしっくりきません。
一体どういうものなのでしょうか?

2018-04-02 07:49 UTC, re-fort commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +一貫したサイトを作成する過程で、様々な箇所で同じアニメーションロジックを再利用していることに気づくかもしれません。シンプルなロジックに思えますが、再利用し辛いカスタムディレクティブを作成していたことでしょう。何も考えずに再利用すれば、使用の度に「ほんの」些細な変更を必要とすることになります。
`cohesive site`は説明するのも難しいですが、、要はUI/UXなどが統一されているサイトのことだと思います。
ずっと赤系統の背景だったのに、意味もなくいきなり青系統になるサイトが`not cohesive site`にあたります。
`consistent`とか`unity`とかに近い語ですかね。。
訳的には、`統一されたサイト`とか`まとまりのあるサイト`とかがわかりやすいかな？と個人的に思いました！

2018-04-03 11:46 UTC, pipopotamasu commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +一貫したサイトを作成する過程で、様々な箇所で同じアニメーションロジックを再利用していることに気づくかもしれません。シンプルなロジックに思えますが、再利用し辛いカスタムディレクティブを作成していたことでしょう。何も考えずに再利用すれば、使用の度に「ほんの」些細な変更を必要とすることになります。
説明ありがとうございます！

`統一感のあるサイト`←こちら使わせていただきました。

2018-04-03 11:47 UTC, pipopotamasu commented
翻訳完了しました。
レビューよろしくお願いします。

2018-04-04 13:08 UTC, re-fort commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +Web サイト上でスクロールイベントと連動するアニメーションなど、ちょっとした振る舞いを加えたくなる時は多くあります。やり方は多くありますが、最も少ないコード量と依存で実現できる方法はおそらく、特定のスクロールイベントを発火させるフックを作成する、[カスタムディレクティブ](https://vuejs.org/v2/guide/custom-directive.html)を使用することでしょう。
リンク先はhttps://jp.vuejs.org/v2/guide/custom-directive.htmlでお願いします！

2018-04-04 13:11 UTC, re-fort commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +以下のケースでは、トランジションのスタイルプロパティも必要となります。
`that will transition the intermediary values here` も訳していただけるとより善いかなと思います！

2018-04-04 13:26 UTC, re-fort commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +統一感のあるサイトを作成する過程で、様々な箇所で同じアニメーションロジックを再利用していることに気づくこともあるでしょう。それはシンプルなロジックに見えますが、カスタムディレクティブは再利用し辛いものになっているかもしれません。何も考えずに再利用すれば、使用の度に「ほんの」些細な変更を必要とすることになるでしょう。
`_just_` の箇所はそのまま `_ほんの_` と訳していただいて大丈夫です！

2018-04-04 13:32 UTC, re-fort commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +上のデモで、それぞれのセクションはスクロールによって引き起こされる、2つの異なるアニメーションがあります。変形アニメーションと、SVG内の個々のパスに沿って動く描画アニメーションです。これら2つのアニメーションを再利用するため、それぞれのカスタムディレクティブを作成します。カスタムディレクティブに渡す引数は、シンプルかつ再利用可能なコードの維持に役立ちます。
`それぞれのセクションには`のほうがわかりやすいかもしれません。
`変形アニメーション`も下にも出てくるので、`モーフィングアニメーション`としてしまってよいかと思われます！

2018-04-04 13:35 UTC, re-fort commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +やり方を示すために、モーフィングシェイプの例を見てみましょう。ここでは開始・終了座標の状態と共に、モーフィングを作成するパス値が必要です。これらの引数はそれぞれ `binding.value.foo` に定義されています。
s/に定義/として定義

2018-04-04 13:42 UTC, re-fort requested changes
さっそくの翻訳ありがとうございます！
何点か気になった箇所をコメントしたので、確認おねがいします！

2018-04-07 01:43 UTC, pipopotamasu commented
@re-fort レビューありがとうございます。確認させていただきます。

2018-04-07 01:59 UTC, pipopotamasu commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +やり方を示すために、モーフィングシェイプの例を見てみましょう。ここでは開始・終了座標の状態と共に、モーフィングを作成するパス値が必要です。これらの引数はそれぞれ `binding.value.foo` に定義されています。
こちらのコメントはどういう意味でしょうか?

2018-04-07 03:21 UTC, pipopotamasu commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +Web サイト上でスクロールイベントと連動するアニメーションなど、ちょっとした振る舞いを加えたくなる時は多くあります。やり方は多くありますが、最も少ないコード量と依存で実現できる方法はおそらく、特定のスクロールイベントを発火させるフックを作成する、[カスタムディレクティブ](https://vuejs.org/v2/guide/custom-directive.html)を使用することでしょう。
修正しました。
a5b93d2

2018-04-07 03:21 UTC, pipopotamasu commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +統一感のあるサイトを作成する過程で、様々な箇所で同じアニメーションロジックを再利用していることに気づくこともあるでしょう。それはシンプルなロジックに見えますが、カスタムディレクティブは再利用し辛いものになっているかもしれません。何も考えずに再利用すれば、使用の度に「ほんの」些細な変更を必要とすることになるでしょう。
修正しました。
09affda

2018-04-07 03:21 UTC, pipopotamasu commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +上のデモで、それぞれのセクションはスクロールによって引き起こされる、2つの異なるアニメーションがあります。変形アニメーションと、SVG内の個々のパスに沿って動く描画アニメーションです。これら2つのアニメーションを再利用するため、それぞれのカスタムディレクティブを作成します。カスタムディレクティブに渡す引数は、シンプルかつ再利用可能なコードの維持に役立ちます。
修正しました。
a81893d

2018-04-07 03:22 UTC, pipopotamasu commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +以下のケースでは、トランジションのスタイルプロパティも必要となります。
修正しました。
6773463

2018-04-07 03:22 UTC, pipopotamasu commented
@re-fort 修正および不明点コメントしました。ご確認お願いします！

2018-04-07 03:26 UTC, re-fort commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +やり方を示すために、モーフィングシェイプの例を見てみましょう。ここでは開始・終了座標の状態と共に、モーフィングを作成するパス値が必要です。これらの引数はそれぞれ `binding.value.foo` に定義されています。
`に定義`を`として定義`に置換という意味合いでした(vimの記法)

2018-04-10 07:06 UTC, pipopotamasu commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +やり方を示すために、モーフィングシェイプの例を見てみましょう。ここでは開始・終了座標の状態と共に、モーフィングを作成するパス値が必要です。これらの引数はそれぞれ `binding.value.foo` に定義されています。
@re-fort こちら修正完了しました。
4d7dfc6

2018-04-11 03:26 UTC, pipopotamasu commented
@re-fort 全て修正完了しました。
再レビューお願いします。

2018-04-12 02:23 UTC, re-fort commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +以下のケースでは、中継値を遷移するスタイルプロパティも必要となります。
`中間値`のほうが自然な気がしました

2018-04-12 02:27 UTC, re-fort requested changes
修正ありがとうございます！
1箇所気になったところにコメントしました。
あと、タイトルを翻訳していただきたいです！

2018-04-12 15:11 UTC, pipopotamasu commented on src/v2/cookbook/creating-custom-scroll-directives.md
> +以下のケースでは、中継値を遷移するスタイルプロパティも必要となります。
修正しました。
856a156

2018-04-12 15:16 UTC, pipopotamasu commented
@re-fort コメントいただいた修正点及びタイトルの翻訳完了しました。

2018-04-15 10:47 UTC, re-fort approved these changes
ありがとうございます:tada:
一番乗りで公開させていただきます！:+1:

2018-04-15 10:47 UTC, merged

2018-04-15 13:50 UTC, kazupon commented
@pipopotamasu
翻訳ありがとうございました！🎉

2018-04-16 07:13 UTC, pipopotamasu commented
@re-fort レビューありがとうございました！

2018-04-16 07:13 UTC, pipopotamasu commented
@kazupon こちらこそ翻訳の機会をいただきありがとうございました！