[WIP] [Cookbook]: Adding Instance Propertiesの翻訳
vuejs/jp.vuejs.org pull request #890
Opened 2018-04-07 06:44 UTC by k-okina

#816

2018-04-07 08:34 UTC, re-fort commented
@k-okina 翻訳着手ありがとうございます！
強調について分かりやすくしてくれてありがたいんですが、原文で強調されてないものはそのままにしていただいてよいでしょうか？

2018-04-07 10:06 UTC, k-okina commented
@re-fort 
了解です！
すべて直しました！

2018-04-07 10:09 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +**この利便性は明確さとのトレードオフです**。コンポーネントを見たとき、`this.$http` がどこから来たのかを知ることは不可能です。Vue 本体のですか？A プラグインのですか？それとも他のですか？
ここだけ、`$http`となっているのですが、これは表記ミスではないでしょうか？
そのまま`$http`の表現にしたほうが良いでしょうか？一応確認です！

2018-04-12 02:34 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +**この利便性は明確さとのトレードオフです**。コンポーネントを見たとき、`this.$http` がどこから来たのかを知ることは不可能です。Vue 本体のですか？A プラグインのですか？それとも他のですか？
ここは`$http`のままのほうがわかりやすいかと思います！

2018-04-15 11:04 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +`"My App"` はコンソールに記録されます。これはとてもシンプルです!
どうやらこの変更が取り込めていなかったようです
`これはとてもシンプルです！`を消してもらってもよいでしょうか？
https://github.com/vuejs/vuejs.org/commit/fe25553b14eb9a094f3038e8b52412468d203000#diff-83f2259c183489887360fde1372f9a74

2018-04-15 11:07 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +それでは[使われなくなったVueのリソースを置き換えるとしましょう](https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4)。あなたは `this.$http` を通してリクエストメソッドにアクセスすることを凄く楽しんでいましたが、代わりにAxiosで同じことをしたいと思います。
Vue Resource は昔Vue公式で提供していたツールの名前なので、そのままでよいです！

2018-04-15 11:09 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +JavaScriptのプロトタイプに追加されたメソッドはインスタンスのコンテキストを取得します。 つまり、インスタンスに定義された data、computed プロパティ、methods、その他のものにアクセスするために this を使用できます。
`In case you're not aware` -> `気付いてないかもしれませんが`

2018-04-15 11:11 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +JavaScriptのプロトタイプに追加されたメソッドはインスタンスのコンテキストを取得します。 つまり、インスタンスに定義された data、computed プロパティ、methods、その他のものにアクセスするために this を使用できます。
`data、computed プロパティ、methods` -> `データ、算出プロパティ、メソッド`
でお願いします！

2018-04-15 11:12 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +*Note* コンテキストバインディングは、ES6/2015のアロー演算子を使用している場合は、親スコープに暗黙的にバインドされるため、**機能しません**。次はアロー関数のパターン：
`*Note*`は消してしまって大丈夫です！

2018-04-15 11:15 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +ただし、他の開発者と混乱することがあります。例えば、`this.$http` を見て、「ああ、私はこのVueの機能について知らなかった！」と思うかもしれません。 その後、彼らは別のプロジェクトに移り、`this.$http` が定義されていなかった場合は混乱します。 あるいは、Googleで `this.$http` で何かできないか調べたいかもしれませんが、実際はAxios を別名で使用してい
`他の開発者と混乱する` -> `他の開発者との間で混乱を引き起こす`
のほうがわかりやすいかもしれません

2018-04-15 11:18 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +**この利便性は明確さとのトレードオフです**。コンポーネントを見たとき、`$http` がどこから来たのかを知ることは不可能です。Vue 本体のですか？A プラグインのですか？それとも他のですか？
Aは可算名詞なので訳さなくて大丈夫です！
`Vue 本体のですか？A プラグインのですか？それとも他のですか？` -> `Vue 本体ですか？プラグインですか？それとも同僚ですか？`

2018-04-15 11:27 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +    // 純粋に機能的なバージョンです
`purely functional`は`純粋関数`でよいかとおもいます！
先程の`$reverseText`とは違い、`this`に依存せず、引数のみに依存しているということかと！

2018-04-15 11:29 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +もう一つの利点は、Vue 関連であろうとなかろうと、あなたのコードで `App` オブジェクトを使用できるようになりました。これでインスタンスに直接オプションを追加する必要がなくなり、関数で `this` からプロパティにアクセスする必要がなくなりました。
`_anywhere_` をいれてもらえると！

2018-04-15 11:32 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +これはとてもわかりやすく、各ファイルで依存関係のリストが得られます。それにより、あなたはそれぞれのコードがどこからのコードかを正確に知ることができます。
`_正確に_`

2018-04-15 11:32 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +冗長ですが、このアプローチは、他の開発者や大規模なアプリケーションを開発する際に、最も保守性が高いです。
`他の開発者や` -> `他の開発者と働いたり`

2018-04-15 11:33 UTC, re-fort requested changes
レビューしました！
確認お願いします！
それに加えて、タイトルの翻訳と重複している`updated`も削除していただければと思います！
https://github.com/k-okina/jp.vuejs.org/blame/59f2bdeacdc1491a81ef896919e88adf48731e54/src/v2/cookbook/adding-instance-properties.md#L2-L3

2018-04-27 00:28 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +`"My App"` はコンソールに記録されます。これはとてもシンプルです!
了解です！対応しました！

2018-04-27 00:29 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +それでは[使われなくなったVueのリソースを置き換えるとしましょう](https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4)。あなたは `this.$http` を通してリクエストメソッドにアクセスすることを凄く楽しんでいましたが、代わりにAxiosで同じことをしたいと思います。
あ、そうだったんですね！了解です！対応しました！

2018-04-27 00:32 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +JavaScriptのプロトタイプに追加されたメソッドはインスタンスのコンテキストを取得します。 つまり、インスタンスに定義された data、computed プロパティ、methods、その他のものにアクセスするために this を使用できます。
了解です！対応しました！

2018-04-27 00:32 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +*Note* コンテキストバインディングは、ES6/2015のアロー演算子を使用している場合は、親スコープに暗黙的にバインドされるため、**機能しません**。次はアロー関数のパターン：
了解です！対応しました！

2018-04-27 00:40 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +ただし、他の開発者と混乱することがあります。例えば、`this.$http` を見て、「ああ、私はこのVueの機能について知らなかった！」と思うかもしれません。 その後、彼らは別のプロジェクトに移り、`this.$http` が定義されていなかった場合は混乱します。 あるいは、Googleで `this.$http` で何かできないか調べたいかもしれませんが、実際はAxios を別名で使用してい
確かに！対応しました！

2018-04-27 00:41 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +**この利便性は明確さとのトレードオフです**。コンポーネントを見たとき、`$http` がどこから来たのかを知ることは不可能です。Vue 本体のですか？A プラグインのですか？それとも他のですか？
あ、そういうことだったんですか！お恥ずかしい。笑
A, B, Cで対象を表してるのかとおもいました！
対応しました！

2018-04-27 00:42 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +    // 純粋に機能的なバージョンです
確かに！
対応しました！

2018-04-27 00:49 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +もう一つの利点は、Vue 関連であろうとなかろうと、あなたのコードで `App` オブジェクトを使用できるようになりました。これでインスタンスに直接オプションを追加する必要がなくなり、関数で `this` からプロパティにアクセスする必要がなくなりました。
_anywhere_がなんなのか軽く調べてもよくわからなかったのですが、文書はこれで大丈夫でしょうか？
```
もう一つの利点は、Vue 関連であろうとなかろうと、あなたのコードでは `App` が _anywhere_ で使用できるようになりました。
```

2018-04-27 00:50 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +これはとてもわかりやすく、各ファイルで依存関係のリストが得られます。それにより、あなたはそれぞれのコードがどこからのコードかを正確に知ることができます。
対応しました！

2018-04-27 00:51 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +冗長ですが、このアプローチは、他の開発者や大規模なアプリケーションを開発する際に、最も保守性が高いです。
対応しました！

2018-04-27 00:53 UTC, k-okina commented
@re-fort 
お疲れ様です！
細かいレビューありがとう御座います！

お待たせしました、レビュー対応しました！
ご確認お願いします！

2018-04-29 03:02 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
>  title: Adding Instance Properties
タイトルも翻訳お願いします！

2018-04-29 03:04 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +ここでは特別な事は一切起きていません。 Vueは全てのインスタンスが利用できるプロパティに対して接頭辞に `$` をつけるよう規約を設けています。この規約により、定義した data、computed プロパティ、または methods との衝突を回避できます。
computed プロパティは算出プロパティでおねがいします！

2018-04-29 03:11 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +この場合、まずは `"My App"` が記録され、それから `"The name of some other app"` が記録されます。なぜなら `this.appName` はインスタンスが([作成されるとき](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/c
リンクをつけるのは`作成されるとき`ではないですかね
sort ofは`並び替えられる`でOKです

2018-04-29 03:13 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +## 代替案
代替パターンでお願いします！

2018-04-29 03:14 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +もう一つの利点は、Vue 関連であろうとなかろうと、あなたのコードでは `App` が _anywhere_ で使用できるようになりました。これでインスタンスに直接オプションを追加する必要がなくなり、関数で `this` からプロパティにアクセスする必要がなくなりました。
anywhereを翻訳お願いします！

2018-04-29 03:16 UTC, re-fort commented on src/v2/cookbook/adding-instance-properties.md
> +もう一つの利点は、Vue 関連であろうとなかろうと、あなたのコードで `App` オブジェクトを使用できるようになりました。これでインスタンスに直接オプションを追加する必要がなくなり、関数で `this` からプロパティにアクセスする必要がなくなりました。
そのまま「どこでも」と訳していただいて問題ありません！

2018-04-29 03:19 UTC, re-fort requested changes
@k-okina 再レビューしました！いくつかコメントを追加したのと質問に答えました！
また、以下の対応が済んでない気がするので、ここも含めて再チェックおねがいできると！
https://github.com/vuejs/jp.vuejs.org/issues/814#issuecomment-381481939

すでに大型連休に入られている場合、明けてからの対応で問題ありませんので:blush:

2018-05-01 01:11 UTC, k-okina commented
すいません、確認しました！
本日再度修正します。。！

2018-05-02 02:43 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +ここでは特別な事は一切起きていません。 Vueは全てのインスタンスが利用できるプロパティに対して接頭辞に `$` をつけるよう規約を設けています。この規約により、定義した data、computed プロパティ、または methods との衝突を回避できます。
あ、すいません、ここもでしたね（汗）

2018-05-02 02:44 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +## 代替案
対応しました！

2018-05-02 02:53 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
>  title: Adding Instance Properties
対応しました！

2018-05-02 02:53 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +この場合、まずは `"My App"` が記録され、それから `"The name of some other app"` が記録されます。なぜなら `this.appName` はインスタンスが([作成されるとき](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/c
すいません、意味がよくわかってないのですが、 作成される時 => 並び替えられるとき に修正すればいいってことですか？

2018-05-02 02:53 UTC, k-okina commented
@re-fort こういうことでしょうか？
お願いします！

2018-05-02 02:57 UTC, k-okina commented on src/v2/cookbook/adding-instance-properties.md
> +この場合、まずは `"My App"` が記録され、それから `"The name of some other app"` が記録されます。なぜなら `this.appName` はインスタンスが([作成されるとき](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/c
でも確かにインスタンスが作成された時だとbeforecreateで既に反映されてますもんね。
これ出会ってる感じですかね？？？

2018-05-07 02:57 UTC, re-fort approved these changes
@k-okina 説明がわるくてすみません！こちらのほうで修正しました！翻訳ありがとうございました:tada:

2018-05-07 02:57 UTC, merged

2018-05-07 05:30 UTC, k-okina commented
理解が足りなくて、お手数おかけしてすいませんでした🙇‍♂️
レビュー本当にありがとうございました！！！🙇‍♂️