WIP: [Cookbook]: Form Validationの翻訳
vuejs/jp.vuejs.org pull request #891
Opened 2018-04-08 13:58 UTC by potato4d

この PR は、 WIP PR となります。翻訳完了箇所から随時コメントをつけていきますが、完全に完了するまでしばらくお待ち下さい。

## About
close #817 

Cookbook の「Form Validation」を翻訳しました。

2018-04-08 14:22 UTC, potato4d commented
@re-fort もう少しだけ翻訳時間がかかりそうです 🙇

2018-04-08 23:23 UTC, potato4d commented on src/v2/cookbook/form-validation.md
> +そして、その HTML をラップしましょう。 `<form>` タグには、 Vue コンポーネントに使用する ID が存在します。 submit のハンドラと `action` がありますが、一時的な URL であり、現実のサーバーのどこかを指しています(ここでは、サーバーサイドでのバリデーションをバックアップしています)。
submit を「フォーム送信」「送信」と訳すべき？

2018-04-08 23:23 UTC, potato4d commented on src/v2/cookbook/form-validation.md
> +その子には、エラーの状態にもとづいてそれ自身を表示・非表示とするための段落があります。これによって、フォーム上にシンプルなエラーのリストが表示されます。バリデーションはフィールドの変更時ではなく、 submit の際に実行されることに注意してください。
submit を「フォーム送信」「送信」と訳すべき？

2018-04-08 23:24 UTC, potato4d commented on src/v2/cookbook/form-validation.md
> +## 代替パターン
「代替手段」ぐらい思い切ってもよさそう？

2018-04-08 23:28 UTC, potato4d commented on src/v2/cookbook/form-validation.md
> -Fairly short and simple. We define an array to hold errors and set `null` values for the three form fields. The `checkForm` logic (which is run on submit remember) checks for name and age only as mov
前後文脈をみて `And that's really it` を単純に「〜エラーを設定する〜」の末尾に「だけです」と書いたけれど不安あり

2018-04-08 23:28 UTC, potato4d reviewed
翻訳で気になっている箇所をコメントしています。

2018-04-12 02:35 UTC, re-fort commented on src/v2/cookbook/form-validation.md
> +そして、その HTML をラップしましょう。 `<form>` タグには、 Vue コンポーネントに使用する ID が存在します。 submit のハンドラと `action` がありますが、一時的な URL であり、現実のサーバーのどこかを指しています(ここでは、サーバーサイドでのバリデーションをバックアップしています)。
`フォーム送信` のほうがわかりやすそうですね！

2018-04-12 02:41 UTC, re-fort commented on src/v2/cookbook/form-validation.md
> +## 代替パターン
これ他のcookbookにも出てくるので、表現統一したほうが良さそうですね
`代替パターン`にしましょうか！

2018-04-12 02:47 UTC, re-fort commented on src/v2/cookbook/form-validation.md
> -Fairly short and simple. We define an array to hold errors and set `null` values for the three form fields. The `checkForm` logic (which is run on submit remember) checks for name and age only as mov
それでよいとおもいます！

2018-04-14 13:46 UTC, potato4d commented on src/v2/cookbook/form-validation.md
> +## 代替パターン
ではそうしましょう！

2018-04-14 14:23 UTC, potato4d commented on src/v2/cookbook/form-validation.md
> +3 つめの例は、アンケートアプリにて見たことがあるかもしれません。ユーザーは、 戦艦のそれぞれの機能に対して予算を振り分ける必要があります。かつ合計は必ず 100 である必要があります。まずは HTMLです。
ここに出てくる「new Star Destroyer model」は、おそらく映画スター・ウォーズに登場する戦艦のことで、その設備の内訳という意味なのですが、わかりにくいので単純に戦艦と置き換えてみましたがどうでしょうか。

2018-04-14 14:24 UTC, potato4d commented on src/v2/cookbook/form-validation.md
> +次の例では、２つめのテキストフィールドを email へと切り替え、カスタマイズしたロジックでバリデーションをします。このコードは、 StackOverflow の質問「[How to validate email address in JavaScript?](https://stackoverflow.com/questions/46155/how-to-validate-email-add
ここに関しては `Seriously - it's insane.`  の表現があまり綺麗ではないこと、 `Facebook political/religious argument look like ...` のくだりがどうするのが適切かがあまり判断できず悩んでいます。
よかったら意見をいただけると！

@re-fort

2018-04-14 14:24 UTC, potato4d commented
@re-fort 

おまたせいたしました 🙇 
一通り翻訳完了したのでレビューお願いいたします。一点だけ、英語らしい表現で日本語に落とし込みづらいところがあってコメントしています。

2018-04-15 11:40 UTC, re-fort commented on src/v2/cookbook/form-validation.md
> +## ベースとなる例
`基本的な例`とかでよいかと！

2018-04-15 11:45 UTC, re-fort commented on src/v2/cookbook/form-validation.md
> +最後に、3つのフィールドそれぞれに対応、対応する `v-model`が存在し、これをJavaScriptで利用する値と接続する必要があります。その例を見てみましょう。
`接続する` -> `紐付ける`
のほうがわかりやすそうです！

2018-04-15 12:05 UTC, re-fort commented on src/v2/cookbook/form-validation.md
> +次の例では、２つめのテキストフィールドを email へと切り替え、カスタマイズしたロジックでバリデーションをします。このコードは、 StackOverflow の質問「[How to validate email address in JavaScript?](https://stackoverflow.com/questions/46155/how-to-validate-email-add
うーん、StackOverflowの質問とどう結びついてるかよくわかんないですね...
必要な文章とも思わないので、抜いてしまって`Here is the HTML`から始めるのもありかと思います

2018-04-15 12:08 UTC, re-fort commented on src/v2/cookbook/form-validation.md
> +ここでの変更は少しだけですが、トップのフォームに対して `novalidate="true"` をつけます。 `type="email"` の場合、ブラウザがフィールドに入力された E メールアドレスをバリデーションしようするため、この設定は重要です。率直に言えば、この場合はブラウザを信用すべきかもしれませんが、ここではカスタムバリデーションのサンプルであるため無効化しています。 JavaScr
`トップのフォームに対して `novalidate="true"` をつけます` -> `トップの `novalidate="true"` に注目してください`

2018-04-15 12:15 UTC, re-fort commented on src/v2/cookbook/form-validation.md
> +3 つめの例は、アンケートアプリにて見たことがあるかもしれません。ユーザーは、 戦艦のそれぞれの機能に対して予算を振り分ける必要があります。かつ合計は必ず 100 である必要があります。まずは HTMLです。
わたしもスターウォーズわかんないので、そっちのほうがよいとおもいます！

2018-04-15 12:25 UTC, re-fort commented on src/v2/cookbook/form-validation.md
> +OpenWhisk にて実行される API の URL を表す変数から始まります。 `checkForm` を見てみましょう。この例においては、フォームが送信されないようにしています(ただし、 HTML 上で Vue にて動かすことはできます). ここで、 `this.name` が空であるかのチェックを行い、その後 API を叩いていることが見てとれます。問題がある場合は、先ほどの例と同じよう
カッコが閉じてません

2018-04-15 12:26 UTC, re-fort requested changes
チェックしました！
コード内のコメントも翻訳していただけるとうれしいです！

2018-04-15 12:28 UTC, potato4d commented
@re-fort
レビューありがとうございます！今晩中に直して再度ご連絡しますね。

2018-04-15 13:55 UTC, potato4d commented on src/v2/cookbook/form-validation.md
> +次の例では、２つめのテキストフィールドを email へと切り替え、カスタマイズしたロジックでバリデーションをします。このコードは、 StackOverflow の質問「[How to validate email address in JavaScript?](https://stackoverflow.com/questions/46155/how-to-validate-email-add
了解です〜

2018-04-15 13:58 UTC, potato4d commented
@re-fort 
こちら対応いたしましたので再度レビューお願いいたします 🙏

2018-04-16 00:43 UTC, re-fort commented on src/v2/cookbook/form-validation.md
> +       // Vue は空の値を string に変換する必要があります
`Vue は空の値を string に変換するので、パースする必要があります`

2018-04-16 00:44 UTC, re-fort requested changes
何度もすみません！
この一箇所だけ直したら公開しましょう！

2018-04-16 00:45 UTC, potato4d commented
@re-fort 
こちらこそお手数おかけしてしまってすみません 🙇 
すぐに対応しますね！

2018-04-16 00:46 UTC, potato4d commented
@re-fort 対応しました！

2018-04-16 00:56 UTC, re-fort approved these changes
ありがとうございます:tada:

2018-04-16 00:57 UTC, merged

2018-04-16 01:06 UTC, kazupon commented
@potato4d 翻訳ありがとうございました！🎉