Moving Components Page into its Own Category
vuejs/jp.vuejs.org pull request #908
Opened 2018-04-15 10:36 UTC by re-fort

This PR resolves #851, resolves #862, resolves #883, resolves #894 

Components In-Depthは未着手です、cookbook同様caveatだけ追加しました
これがmergeされたら各セクションの翻訳issueを立てるでいいかな、と思ってます

2018-04-15 10:42 UTC, re-fort commented on src/v2/guide/components.md
> +これが動的コンポーネントについて今のところ知っておくべきことです。そして、実際には Vue の <em>本質</em> の最後となります。おめでとうございます！まだまだ学ぶことはありますが、最初に Vue を自身で遊ぶために休憩をとり、何か面白いものを作ってみることをお勧めします。
原文と違い、わざわざ`<em>`を使用しています。
`hexo-renderer-marked`のレンダリングエンジンである`marked`にバグがあり、3文字以下で`_この記法_`が正しく動かないためです。(masterにｍergeされているものの未リリース)
https://github.com/markedjs/marked/pull/1181

2018-04-15 10:44 UTC, re-fort commented
original: https://github.com/vuejs/vuejs.org/blob/75309fc3c2286f0c78ca46d6932a92815e7ba881/src/v2/guide/components.md
deploy preview: https://deploy-preview-908--vuejs-jp.netlify.com/v2/guide/components.html

2018-04-15 14:35 UTC, kazupon requested changes

2018-04-15 14:35 UTC, kazupon commented on src/v2/guide/components.md
> +それぞれの投稿ごとにコンポーネントをレンダリングします:
`render`の訳は確か、公式ドキュメントの翻訳では`描画`にしていたと思うので、それでお願いします！ 🙏

2018-04-15 14:36 UTC, kazupon commented
ありがとうございます。

>これがmergeされたら各セクションの翻訳issueを立てるでいいかな、と思ってます

コンポーネントのところ、大分構成が変わりましたね。
今クックブックのところ翻訳されているかと思いますが、それと同じ感じで、issue 立てるのいいと思います。

2018-04-16 00:39 UTC, re-fort commented on src/v2/guide/components.md
> +それぞれの投稿ごとにコンポーネントをレンダリングします:
統一しました！
https://github.com/vuejs/jp.vuejs.org/pull/908/commits/18c3761e171b62088c5f3b2224514973c38c9e58

2018-04-16 01:06 UTC, kazupon approved these changes

2018-04-18 09:22 UTC, potato4d approved these changes
👍 🙏

2018-04-18 11:57 UTC, kazupon commented
@re-fort @potato4d
マージですが、20日のハンズオン終わるまで、待ってもらえます？🙏

2018-04-18 15:46 UTC, re-fort commented
🙆

2018-04-21 08:03 UTC, potato4d commented
@kazupon これ入れちゃって大丈夫な感じですか

2018-04-21 08:31 UTC, kazupon commented
🙆

2018-04-24 05:18 UTC, merged