[Cookbook]: Unit Testing Vue Componentsの翻訳
vuejs/jp.vuejs.org pull request #912
Opened 2018-04-16 14:27 UTC by ykhirao

お手すきのときにご確認ください！ @re-fort 

よろしくお願いします！

issue https://github.com/vuejs/jp.vuejs.org/issues/822

2018-04-16 15:43 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +title: 単体テスト Vue コンポーネント
`Vue コンポーネントの単体テスト` のほうが自然かもしれません

2018-04-16 15:49 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +単体テストはソフトウエア開発の基本的な部分です。単体テストは、新しい機能の追加やバグの追跡を容易にするために、最小単位のコードを独立して実行します。 Vue の[単一ファイルコンポーネント](../guide/single-file-components.html)は独立したコンポーネントの単体テストを書くことを容易にします。これによって、あなたは既存の機能を壊さない確信を持って新しい機能を開発
`単体テストはソフトウェア開発の重要な部分です。`ぐらいでよいと思います

2018-04-16 15:49 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +この簡単な例はいくつかのテキストがレンダリングされるかどうかをテストします:
`レンダリング ` -> `描画` でお願いします！

2018-04-16 15:53 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +単体テストコンポーネントはたくさんの利益を持っています:
`利点`がよいと思います

2018-04-16 15:54 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +- デザインを改良します
ここでのdesignは設計だと思います

2018-04-16 15:56 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +自動テストは大規模な開発チームチームが複雑なコードベースを維持するのを許します。
`自動テストは大規模な開発チームが複雑なコードベースを保つのを可能にします。`くらいでよいかなーと

2018-04-16 15:58 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +## 現実的な例
`実例`でお願いします！

2018-04-16 15:59 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +- _一つの仕事_だけをテストすること
`仕事` -> `作業`

2018-04-16 16:00 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +上記のコードスニペットは、 username の長さに基づいてエラーメッセージがレンダリングされるかどうかをテストする方法を示しています。単体テスト Vue コンポーネントの一般的なアイデアを示します: コンポーネントをレンダリングし、マークアップがコンポーネントの状態に一致するかをアサートします。
`username`は`ユーザー名`としてしまってよいと思います

2018-04-16 16:02 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +- 1つのテストが異なることについてアサーションが行っています
`アサーションが` -> `アサーションを`

2018-04-16 16:04 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +- 二重のロジック（`wrapper` の作成と `username` 変数の設定）をファクトリ関数にリファクタリングする
`二重の` -> `重複した`

2018-04-16 16:05 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +*テストの更新*:
`更新したテスト`

2018-04-16 16:06 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +一番上に `values` オブジェクトをまとめて `data` にして、新しい `wrapper` インスタンスを返すファクトリ関数を宣言します。このようにすると、すべてのテストで `const wrapper = shallow（Foo）` を複製する必要がありません。このことのもう1つの大きな利点は、メソッドや computed プロパティを持つ複雑なコンポーネントをすべてのテストでモック
`computed` -> `算出`でおねがいします！

2018-04-16 16:07 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +- API コールの作成
シンプルに`API 呼び出し`でオッケーです

2018-04-16 16:10 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +Vue Test Utils と巨大な JavaScript エコシステムはほぼ 100％ のテスト網羅率を容易にする豊富なツールを提供します。とはいえ、単体テストはテストピラミッドの一部に過ぎません。その他のタイプのテストには e2e (end to end) テストとスナップショットテストがあります。単体テストは最小で最も簡単なテストです - 最小の仕事単位でアサーションを行い、単一のコンポ
`仕事` -> `作業`

2018-04-16 16:12 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +- 対話的テスト
`相互作用テスト`

2018-04-16 16:14 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +Vue コンポーネントのテストについてらさらなる情報はコアチームメンバー [Edd Yerburgh](https://eddyerburgh.me/) による [Testing Vue.js Applications](https://www.manning.com/books/testing-vuejs-applications) で見つけることができます。
`ついてら` -> `ついての`

2018-04-16 16:16 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +そのようなテストを示すより完全な例が Vue Test Utils [ガイド](https://vue-test-utils.vuejs.org/en/guides/)にあります。
こちらも日本語版へのリンクでおねがいします！

2018-04-16 16:17 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +単体テストは重大なアプリケーションの重要な部分です。まず最初は、アプリケーションのビジョンが明確ではない時、単体テストによって開発が遅くなる可能性がありますが、しかし一度ビジョンが決まり、実際のユーザーがアプリケーションとやりとりをすると、単体テスト（と他の種類の自動テスト）はコードベースが維持可能でスケーラブルなことを保証するために絶対に必要です。
`アプリケーションにふれると`くらいでよいかなーと

2018-04-16 16:18 UTC, re-fort requested changes
レビューして気になったことを記載しました！

2018-04-16 16:22 UTC, ykhirao commented
@re-fort 
たくさんレビューいただきありがとうございます。
一旦コメント頂いたところは直したのですが、コメントの意味を読み違えているところあればまたコメントください！

@potato4d 
👍 の反応ありがとうございます！
気になる日本語とかあったらコメントいただけると幸いです。

2018-04-17 08:50 UTC, potato4d reviewed
@ykhirao いくつかコメントしました！見ていただけると！

2018-04-17 08:50 UTC, potato4d commented on src/v2/cookbook/unit-testing-vue-components.md
> +e2e テストは複数のコンポーネントがうまく相互作用することを保証します。それらはより高いレベルです。幾つかの例は、ユーザーがサインアップやログインやユーザー名を更新できるかどうかをテストするものです。これらは単体テストやスナップショットテストより実行が遅くなります。
ここの e2e と二つ次の段落の「エンドツーエンド」は統一して良さそうです。

2018-04-17 08:50 UTC, potato4d commented on src/v2/cookbook/unit-testing-vue-components.md
> +エンドツーエンドテストなどのレベルの高いテストはかなり遅く実行されます。これらは通常デプロイ前に実行されて、システムの各部分がそれぞれ正しく連携して動いていることを確かにします。
ここのエンドツーエンドと二つ前の段落の「e2e」は統一して良さそうです。

2018-04-17 08:50 UTC, potato4d commented on src/v2/cookbook/unit-testing-vue-components.md
> +Vue Test Utils と巨大な JavaScript エコシステムはほぼ 100％ のテスト網羅率を容易にする豊富なツールを提供します。とはいえ、単体テストはテストピラミッドの一部に過ぎません。その他のタイプのテストには e2e (end to end) テストとスナップショットテストがあります。単体テストは最小で最も簡単なテストです - 最小の作業単位でアサーションを行い、単一のコンポ
ここで e2e が使われているので以下全て e2e にしましょうか。

2018-04-17 08:50 UTC, potato4d commented on src/v2/cookbook/unit-testing-vue-components.md
> +自動テストは大規模な開発チームが複雑なコードベースを保つのを可能にします。
「保つことを」のほうが読みやすいかもしれません。

2018-04-17 15:03 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +単体テストコンポーネントはたくさんの利益を持っています:
`コンポーネントの単体テストにはたくさんの利点があります`が自然かなーと

2018-04-17 15:06 UTC, re-fort commented on src/v2/cookbook/unit-testing-vue-components.md
> +そのようなテストを示すより完全な例が Vue Test Utils [ガイド](https://vue-test-utils.vuejs.org/en/guides/)にあります。
上記、未反映のようです

2018-04-19 14:42 UTC, ykhirao commented
@re-fort @potato4d 
レビューありがとうございます！直させていただきました。

2つコミット追加しました。
1つ目はレビュー対応のコミットです。
2つ目は、 `markdownの修正`と`。の統一`と`翻訳の修正`です！

お手数ですがもう一度確認できますでしょうか。

2018-04-21 08:03 UTC, potato4d approved these changes
良さそうです

2018-04-24 15:46 UTC, re-fort approved these changes

2018-04-24 15:47 UTC, re-fort commented
@ykhirao ありがとうございます:tada:

2018-04-24 15:47 UTC, merged

2018-04-24 15:48 UTC, kazupon commented
@ykhirao 
翻訳ありがとうございました！

2018-04-24 15:56 UTC, ykhirao commented
@re-fort 
大変お世話になりました！！
Slack見る限りお忙しそうですがお体には気をつけてください！！👍

@potato4d 
いくつか翻訳のレビューありがとうございました。次のMeetupでの発表楽しみにしています！

翻訳という貴重な経験をさせていただきました。Vue.jsのコミュニティの皆様(cc: @kazupon さん)ありがとうございました！