[Cookbook]Using Axils to Consume APIsの翻訳
vuejs/jp.vuejs.org pull request #913
Opened 2018-04-17 04:14 UTC by masaakikunsan

遅くなってすみません。
レビューお願いします。

close [#824](https://github.com/vuejs/jp.vuejs.org/issues/824)

2018-04-17 04:15 UTC, masaakikunsan commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +API から情報を取得する方法はいくつかありますが、表示する内容を知るために、まずデータ形式どうなっているかを調べることをオススメします。 API エンドポイントを呼び出して出力をすることでデータ形式がどうなっているか調べられます。 CoinDesk API ドキュメントをみることによって `https://api.coindesk.com/v1/bpi/currentprice.json` と
```
We can see in the CoinDesk API documentation, that this call will be made to `https://api.coindesk.com/v1/bpi/currentprice.json`.
```

の翻訳が微妙なのですが、ここどうするのが良いでしょうか？

2018-04-17 05:40 UTC, potato4d requested changes
@masaakikunsan 
翻訳ありがとうございます。
誤字脱字含めていくつかコメントしたのでみていただけると 🙏

2018-04-17 05:40 UTC, potato4d commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +この例題では、 [CoinDesk API](https://www.coindesk.com/api/) を利用して Bitcoin の価格を表示し、毎分更新します。最初に、 npm/yarn か CDN リンクのいずれかを利用して axios をインストールします。
`npm か yarn もしくは` みたいな形にしても良いかもしれません。

2018-04-17 05:40 UTC, potato4d commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +Excellent! 私たちはは様々なデータを持っています。しかし、今は乱雑だと思われるので、適切に表示して、期待通りに動作しない場合や、情報を取得するのに時間がかかる場合に備えて、エラー処理を追加してみましょう。
> 私たちはは

私たちは

2018-04-17 05:40 UTC, potato4d commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +## 他のパターン
ここは「代替パターン」で統一されています！変えていただけると

2018-04-17 05:40 UTC, potato4d commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +この [Fetch API](https://developers.google.com/web/updates/2015/03/introduction-to-fetch) はこれらのタイプの要求のための強力なネイティヴ API です。あなたは聞いたことがあるかもしれませんが、Fetch API の1つの利点は、これを使用するために外部リソースを読み込む必要がないことです。ただし、まだ完全にサ
```
[potato4d@snowcat jp.vuejs.org (lang-ja)]$ git grep 'ネイティブ' | wc -l
39
[potato4d@snowcat jp.vuejs.org (lang-ja)]$ git grep 'ネイティヴ' | wc -l
0
```

jp.vuejs.org としては「ネイティブ」が使われているようなのでこちらに統一しましょうか。

2018-04-17 05:40 UTC, potato4d commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +title: axiosを利用したAPIの使用
`axios を利用した API の使用` へ！

2018-04-17 05:40 UTC, potato4d commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +ウェブアプリケーション構築するとき、 API からデータを取得して表示することがよくあります。これを行うにはいくつかの方法があり、一般的なアプローチは Promise ベースの HTTP クライアントの [axios](https://github.com/axios/axios) を使うことです。
> ウェブアプリケーション構築するとき、 

ウェブアプリケーションを構築するとき、

2018-04-17 05:47 UTC, masaakikunsan commented
@potato4d レビューいただいた分修正しました

2018-04-17 08:25 UTC, masaakikunsan commented on src/v2/cookbook/using-axios-to-consume-apis.md
> -## Wrapping Up
Cookbookですし仕上げに的な意味の方が正しい気がするのですが、内容的にも最後に的なニュアンスだと思い結論にさせていただいたのですがいかがでしょうか？

2018-04-17 08:40 UTC, potato4d commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +これは使用している API とアプリケーションの複雑さに依存して、異なるセクションのコンポーネントの使用とより明確なエラー報告によってさらに改善されます。
[want] ここの読みづらさ改善したいですね、優先ではないので難しそうなら大丈夫です！

2018-04-17 08:41 UTC, potato4d reviewed
対応ありがとうございます！
いくつか [want] を追加しました。必須ではないかと思う箇所ですが、一応いご確認いただけると！

2018-04-17 08:41 UTC, potato4d commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +この [Fetch API](https://developers.google.com/web/updates/2015/03/introduction-to-fetch) はこれらのタイプの要求のための強力なネイティブ API です。あなたは聞いたことがあるかもしれませんが、Fetch API の1つの利点は、これを使用するために外部リソースを読み込む必要がないことです。ただし、まだ完全にサ
[want] `have heard ~ ...` 、日本語に訳すなら「ご存知かもしれませんが」のほうが自然かもしれません。すこし意訳チックになってしまう気もするので、ご意見をいただけると。

2018-04-17 08:42 UTC, potato4d commented on src/v2/cookbook/using-axios-to-consume-apis.md
> -## Wrapping Up
あくまでも比喩表現なのでそこまで Cook に合わせる必要はないかと思います。

2018-04-17 08:43 UTC, potato4d approved these changes
一旦自分は Approve としてつけておきますが、気になっている点

https://github.com/vuejs/jp.vuejs.org/pull/913#discussion_r181947797
https://github.com/vuejs/jp.vuejs.org/pull/913#discussion_r181990507

について @re-fort さんの判断を知りたいところです。

2018-04-17 08:43 UTC, masaakikunsan commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +この [Fetch API](https://developers.google.com/web/updates/2015/03/introduction-to-fetch) はこれらのタイプの要求のための強力なネイティブ API です。あなたは聞いたことがあるかもしれませんが、Fetch API の1つの利点は、これを使用するために外部リソースを読み込む必要がないことです。ただし、まだ完全にサ
ご存知かもしれませんがのほうが自然だと思うのでそちらで修正させていただきます。

2018-04-17 15:12 UTC, re-fort commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +API から情報を取得する方法はいくつかありますが、表示する内容を知るために、まずデータ形式どうなっているかを調べることをオススメします。 API エンドポイントを呼び出して出力をすることでデータ形式がどうなっているか調べられます。 CoinDesk API ドキュメントをみることによって `https://api.coindesk.com/v1/bpi/currentprice.json` と
`まずデータ形式` -> `まずデータ形式が`

2018-04-17 15:19 UTC, re-fort commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +API から情報を取得する方法はいくつかありますが、表示する内容を知るために、まずデータ形式どうなっているかを調べることをオススメします。 API エンドポイントを呼び出して出力をすることでデータ形式がどうなっているか調べられます。 CoinDesk API ドキュメントをみることによって `https://api.coindesk.com/v1/bpi/currentprice.json` と
`We can see in the CoinDesk API documentation, that this call will be made to https://api.coindesk.com/v1/bpi/currentprice.json`

`CoinDesk API ドキュメントをみると、 https://api.coindesk.com/v1/bpi/currentprice.json を呼べばいいことがわかります`

2018-04-17 15:22 UTC, re-fort commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +Excellent! 私たちは様々なデータを持っています。しかし、今は乱雑だと思われるので、適切に表示して、期待通りに動作しない場合や、情報を取得するのに時間がかかる場合に備えて、エラー処理を追加してみましょう。
Excellent!はこのままでもよいかもですが、`素晴らしい！`くらいに訳していただけるとー

2018-04-17 15:23 UTC, re-fort commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +### API のデータを表示
`APIから取得した`くらいに意訳してしまって大丈夫です！

2018-04-17 15:33 UTC, re-fort commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +典型的には私たちが必要とする情報はレスポンスの中にあり、正しくアクセスするにはトラバースし終えたもの格納する必要があります。このケースでは、求めている価格情報が `response.data.bpi` にあることがわかります。代わりにこれを使用すると、出力は次のようになります。
`we'll have to traverse what we've just stored to access it properly`

`適切にアクセスするには今取得したレスポンスを辿る必要があります`

2018-04-17 15:38 UTC, re-fort commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +これは私たちが表示するほうが簡単なので、受信したデータから必要な情報だけを表示するように HTML を更新できるようになりました。[filter](../api/#Vue-filter) を使用して小数点が適切な場所にあるかどうか確かめます。
`表示するのがはるかに簡単になったので`

2018-04-17 15:43 UTC, re-fort commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +このリクエストをする時、そのような状況を確認し、情報を渡し全ての問題を処理する方法を知れます。 axios コールでは、 `catch` を使用して呼び出します。
`When making this request, we should be checking for just such circumstances, and giving ourselves information in every case so we know how to handle the problem`

`APIリクエストをする際は、そのような状況を確認し、全てのケースで情報を渡す必要があります。それにより問題の取扱い方が分かります。`

2018-04-17 15:52 UTC, re-fort commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +これは使用している API とアプリケーションの複雑さに依存して、異なるセクションのコンポーネントの使用とより明確なエラー報告によってさらに改善されます。
`これは使用している API とアプリケーションの複雑さに依存しますが、異なる区分のコンポーネントの使用とより明確なエラー報告によってさらに改善することが可能です。`

2018-04-17 15:55 UTC, re-fort commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +この [Fetch API](https://developers.google.com/web/updates/2015/03/introduction-to-fetch) はこれらのタイプの要求のための強力なネイティブ API です。ご存知かもしれませんが、Fetch API の1つの利点は、これを使用するために外部リソースを読み込む必要がないことです。ただし、まだ完全にサポートされていない
`そういうわけで多くの人が今のところ axios を使用することを好んでいます。`

2018-04-17 15:56 UTC, re-fort commented on src/v2/cookbook/using-axios-to-consume-apis.md
> -## Wrapping Up
`結論`でよいかとおもいます！

2018-04-17 15:59 UTC, re-fort commented on src/v2/cookbook/using-axios-to-consume-apis.md
> +API を使用して表示するだけでなく Vue や axios で作業する方法はたくさんあります。さらに、サーバレス関数と通信したり、書き込み権限を持っているAPI から post/edit/delete したり、他にも多くのメリットがあります。これら2つのライブラリの正しい統合によって、 HTTP クライアントの統合をワークフローに必要とする開発者にとって非常に一般的な選択です。
`これら2つのライブラリの正しい統合によって、` -> `これら2つのライブラリを組み合わせるのは難しくないため、`

2018-04-17 15:59 UTC, re-fort requested changes
レビューしました！
確認おねがいします！

2018-04-18 05:13 UTC, masaakikunsan commented
@re-fort 修正しました！
再レビューお願いします

2018-04-18 16:01 UTC, re-fort approved these changes
ありがとうございます！:tada:

2018-04-18 16:01 UTC, merged

2018-04-24 06:24 UTC, kazupon commented
@masaakikunsan 
事後になってあれですが、翻訳ありがとうございました！