[Cookbook]: Create a CMS-Powered Blogの翻訳
vuejs/jp.vuejs.org pull request #917
Opened 2018-04-22 15:59 UTC by hikimon

大変遅くなりましたが、以下の対応を行いました。  
https://github.com/vuejs/jp.vuejs.org/issues/819  

かなり口語的な表現があったため、意訳が多くなってしまっています。 。。  
レビュー指摘よろしくお願いいたします！

2018-04-23 12:01 UTC, potato4d requested changes
@hikimon 
翻訳ありがとうございます :pray:

サッと見られる分だけで恐縮ですが、軽く全体目を通したので対応いただければと思います 🙇

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +## 代替手段
これはクックブックでは「代替パターン」で統一されているのでそちらでお願いします！

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +このファイルを ButterCMS を使いたいコンポネントでインポートし、コンソールで以下を実行します。:
「コンポーネント」でお願いします :pray:

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +この API リクエストは、あなたのブログの投稿をフェッチします。あなたのアカウントは、レスポンスから1つの投稿例とセットで取得します。
ここを愚直に「フェッチ」としてしまうと少し読みづらいですし「取得します」くらいでも良いかもしれませんね。
@re-fort どうでしょうか。

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +投稿を表示するには、アプリケーションで、`/blog` ルーティングを (Vue Router を使用) 作成し、Butter API でブログの投稿をフェッチします。`/blog/:slug` ルーティングが同様に各々の投稿をハンドルします。
- `ルーティング(Vue Router を使用) を`
- `ルーティングを (Vue Router を使用して)`

のどちらかのほうが読みやすそうです

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +カテゴリ、または著者によるフィルタリングのような追加オプションは、ButterCMS [API reference](https://buttercms.com/docs/api/?javascript#blog-posts) を参照してください。 レスポンスは、あなたがページネーションのために使用するいくつかのメタデータも含みます。
reference は「リファレンス」とすると良さそうです

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +              <!-- 結果をバインディングするには、`:` を使います。-->
`':' を利用した結果のバインディング` くらいのほうが素直そうですかね？

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +              <!-- 結果をバインディングするには、`:` を使います。-->
@hikimon さん自身の意見を聞けると :pray:

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +              <!-- `featured_image` を使うかどうかは、`v-if`/`else` で判定します。-->
ここは「。」は不要そうです。

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +これはこのように表示されます。:
`こちらがプレビューです` くらいのほうが良さそうです。

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +## 要約
内容的に特に要約していないので要約ではなさそうな気がします。

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +あなたが Vue.js のウェブサイトをちょうど立ち上げたばかりならば、おめでとうございます！いま、あなたは自分のウェブサイトに早くブログを追加したいが、1つの Wordpress のインスタンス（また、さらに言えば DB の動作する CMS）だけをホスティングするためにサーバ全体をスピンアップさせたくはないでしょう。あなたは、少しの Vue.js のブログ構成要素といくつかのルーティングを追加
これはちょっと原文が悪くて申し訳ないですが Wordpress は WordPress が正しいですね 😅

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +私たちは、Vue.js で CMS によるブログを素早くつくっていきます。これには、[ButterCMS](https://buttercms.com/) を使います。これは、あなたに、ButterCMS ダッシュボードでコンテンツを管理させ、 コンテンツをあなたの Vue.js アプリケーションに API で統合させる API first な CMS です。あなたは、新しく、または既にある V
> これは、あなたに、ButterCMS ダッシュボードでコンテンツを管理させ、 コンテンツをあなたの Vue.js アプリケーションに API で統合させる API first な CMS です。

`your` を素直に翻訳していただいたかと思いますが、表現として少し冗長なので

> これは、 ButterCMS ダッシュボードを利用してコンテンツを管理し、コンテンツ API を Vue.js アプリケーションに統合させる API ファーストな CMS です。

あたりにしましょうか。

> あなたは、新しく、または既にある Vue.js のプロジェクトのために、ButterCMS を使えます。

こちらも

> 新しく、または既にある Vue.js のプロジェクトのために、ButterCMS を使えます。

あたりで良さそうです。

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +Butter は、CDN からも読み込めます。:
`.` で終わっていないところはそのままにしてください！ 🙇 

> Butter は、CDN からも読み込めます:

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +あなたの API token を設定します。:
`API トークンの設定:` でどうでしょう？

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +`components/BlogPost.vue` 内の `<script>` を以下のように更新します。:
ここも「。」はなしで 🙏

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +以上です！あなたはいま、アプリケーション上で動作する完全な機能を持った CMS によるブログを手に入れました。私たちは、このチュートリアルが役に立つことと、あなたの Vue.js の開発経験をより一層楽しくすることを願っています。:)
ここも「。」不要です。

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +もし、あなたがマークダウンでのみの記述を好むなら、特に代替手段として考えられるのは、[Nuxtent](https://nuxtent.now.sh/guide/writing#async-components) のようなものを使う方法です。Nuxtent は、マークダウン形式のファイルの代わりに、`Vue Component` の利用をあなたに提供します。 このアプローチは、マークダウン形式の
ここもそのまま you/your が表現されていて読みづらいのでちょっと適度に梳いてもらえますか 🙇

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +ES6 を使用する場合:
`ES6 の使用` くらいで良いかと 🙏

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +CDN を使用する場合:
`CDN の使用` くらいで良いかと 🙏

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +<p class="tip">注意してください。この方法でコンポネントが使われるということは、コンポネントのライフサイクルによるフックが呼ばれないことを意味します。より詳しくは、Vue Router のドキュメントを参照してください。[動的ルートマッチング] (https://router.vuejs.org/ja/essentials/dynamic-matching.html)</p>
「コンポーネント」でお願いします

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +ルーティングをパラメータと一緒に使用する際にもう1つ注意すべきなのは、ユーザが `/blog/foo` から `/blog/bar` へ遷移するとき、同じコンポネントのインスタンスが再利用される点です。各々のルーティングが同じコンポネントを描画するため、これは古いインスタンスの破棄と新しいインスタンスの生成をするより、効率的です。
「コンポーネント」でお願いします

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +あなたが Vue.js のウェブサイトをちょうど立ち上げたばかりならば、おめでとうございます！いま、あなたは自分のウェブサイトに早くブログを追加したいが、1つの Wordpress のインスタンス（また、さらに言えば DB の動作する CMS）だけをホスティングするためにサーバ全体をスピンアップさせたくはないでしょう。あなたは、少しの Vue.js のブログ構成要素といくつかのルーティングを追加
> あなたが Vue.js のウェブサイトをちょうど立ち上げたばかりならば、おめでとうございます！

ちょっと場面を限定しすぎて煽りっぽくなってしまっているので

> Vue.js の Web サイトを新しく立ち上げたとしましょう。おめでとうございます！

くらいのほうが良いかもしれませんね 🤔

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +以下は、あなたのブログの投稿ページをただ1つのリストにする `components/BlogPost.vue` を生成します。
これは「ただひとつのリスト」ではなく `single post` 、要は単純な CMS の投稿という概念( WP をはじめとして CMS での一般的な投稿単体の呼称ですね)をリスト表示しているという意味なので、そういった形で書き換えていただけますか 🙇

2018-04-23 12:01 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +これはこのようになります（注釈：速くスタイリングするために、from https://bulma.io/ の CSS を追加しました）:
from が適切に訳されていません

2018-04-23 12:21 UTC, potato4d requested changes
更に追加しました 🙇

2018-04-23 12:21 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +これはこのようになります（注釈：速くスタイリングするために、from https://bulma.io/ の CSS を追加しました）:
追加：これ下にある画像をさしているので「以下」のほうが良さそうです

2018-04-23 12:21 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +これを固定するために、私たちは `$route` オブジェクトをウォッチし、ルーティングが変わるときに、`getPost()` を呼ぶ必要があります。
```
[potato4d@snowcat jp.vuejs.org (lang-ja)]$ git grep '監視' | wc -l
43
[potato4d@snowcat jp.vuejs.org (lang-ja)]$ git grep 'ウォッチ' | wc -l
18
```

監視としましょうか 🙏

2018-04-23 12:21 UTC, potato4d commented on src/v2/cookbook/serverless-blog.md
> +これらのオブジェクトについて、より情報を得るには、ButterCMS API リファレンスを参照してください。
ButterCMS `の` API リファレンス
くらいあったほうが良いかもしれません。

2018-04-23 13:55 UTC, hikimon commented
@potato4d レビューありがとうございます！対応します。

2018-04-23 14:30 UTC, hikimon commented on src/v2/cookbook/serverless-blog.md
> +              <!-- 結果をバインディングするには、`:` を使います。-->
こちら語順的に、`:`を使います、で終わったらそもそも変ですね。。。
`:`を使った or `:`による、に直します。

2018-04-23 15:41 UTC, hikimon commented
@potato4d @re-fort 
レビューいただいた内容を反映しました。  
- 文言の統一、表記ルールから外れているものの修正    
- 冗長な `you` `your` 等の削除、接続詞の見直し、言い回しの修正    
「フェッチ」は「取得」のほうが確かにわかりやすそうなので一旦そのように修正しています。  
ご確認よろしくお願いします！

2018-04-24 01:45 UTC, re-fort commented on src/v2/cookbook/serverless-blog.md
> +title: CMS による Blog の作成
ここもブログに合わしちゃいましょう

2018-04-24 01:56 UTC, re-fort commented on src/v2/cookbook/serverless-blog.md
> +あなたが Vue.js のウェブサイトを新しく立ち上げたとしましょう。おめでとうございます！いま、あなたは自分のウェブサイトに早くブログを追加したいでしょうが、1つの WordPress のインスタンス（また、さらに言えば DB の動作する CMS）だけをホスティングするためにサーバ全体をスピンアップさせたくはないでしょう。少しの Vue.js のブログ構成要素といくつかのルーティングを追加でき
`1つの WordPress のインスタンス（また、さらに言えば DB の動作する CMS）ホスティングするためだけにサーバ全体をチューニングさせたくはないでしょう`
spin upのうまい訳が思いつきませんでしたが、ひとことでいうならチューニングかなーとおもいました

2018-04-24 02:00 UTC, re-fort commented on src/v2/cookbook/serverless-blog.md
> +あなたが Vue.js のウェブサイトを新しく立ち上げたとしましょう。おめでとうございます！いま、あなたは自分のウェブサイトに早くブログを追加したいでしょうが、1つの WordPress のインスタンス（また、さらに言えば DB の動作する CMS）だけをホスティングするためにサーバ全体をスピンアップさせたくはないでしょう。少しの Vue.js のブログ構成要素といくつかのルーティングを追加でき
`少しの Vue.js のブログ構成要素といくつかのルーティングを追加でき、1つの サーバにすべてを適切に持たせられるようにしたいですよね？`

`いくつかの Vue.js ブログのコンポーネントといくつかのルーティングを追加して、それがすべてうまく動作するようにしたいだけですよね？`

2018-04-24 02:01 UTC, re-fort commented on src/v2/cookbook/serverless-blog.md
> +あなたが Vue.js のウェブサイトを新しく立ち上げたとしましょう。おめでとうございます！いま、あなたは自分のウェブサイトに早くブログを追加したいでしょうが、1つの WordPress のインスタンス（また、さらに言えば DB の動作する CMS）だけをホスティングするためにサーバ全体をスピンアップさせたくはないでしょう。少しの Vue.js のブログ構成要素といくつかのルーティングを追加でき
dive in は`詳しく見ていきましょう！`ぐらいで大丈夫です

2018-04-24 02:13 UTC, re-fort commented on src/v2/cookbook/serverless-blog.md
> +この API リクエストは、ブログの投稿をフェッチします。あなたのアカウントは、レスポンスから1つの投稿例とセットで取得します。
`Your account comes with one example post which you'll see in the response.`

`あなたのアカウントには1つの投稿例が付属していて、レスポンスで見ることができるでしょう。`

2018-04-24 02:16 UTC, re-fort commented on src/v2/cookbook/serverless-blog.md
> +<p class="tip">注意してください。この方法でコンポーネントが使われるということは、コンポーネントのライフサイクルによるフックが呼ばれないことを意味します。より詳しくは、Vue Router のドキュメントを参照してください。[動的ルートマッチング] (https://router.vuejs.org/ja/essentials/dynamic-matching.html)</p>
リンクが正しく描画されてないです

2018-04-24 02:17 UTC, re-fort commented on src/v2/cookbook/serverless-blog.md
> +これを固定するために、私たちは `$route` オブジェクトを監視し、ルーティングが変わるときに、`getPost()` を呼ぶ必要があります。
`これを修正するために`

2018-04-24 02:19 UTC, re-fort commented on src/v2/cookbook/serverless-blog.md
> +以下は、すべてのカテゴリーと、カテゴリーによる投稿を取得する例です。これらの関数は、`created()` のライフサイクルをフックとして呼び出してください。
`これらの関数を `created()`  のライフサイクルフックで呼び出してください。`

2018-04-24 02:22 UTC, re-fort requested changes
翻訳ありがとうございます！
気になる点を記載しました〜

2018-04-24 03:11 UTC, hikimon commented
@re-fort ありがとうございます！対応します。

2018-04-24 03:16 UTC, hikimon commented on src/v2/cookbook/serverless-blog.md
> +あなたが Vue.js のウェブサイトを新しく立ち上げたとしましょう。おめでとうございます！いま、あなたは自分のウェブサイトに早くブログを追加したいでしょうが、1つの WordPress のインスタンス（また、さらに言えば DB の動作する CMS）だけをホスティングするためにサーバ全体をスピンアップさせたくはないでしょう。少しの Vue.js のブログ構成要素といくつかのルーティングを追加でき
spin upって、「スタッガード・スピンアップ」とかの「スピンアップ」なのですかね。。。？
だと「システムの起動」とかそんな意味合いでしょうか。
こんな記事もありました。
https://www.reddit.com/r/PUBATTLEGROUNDS/comments/65ieyt/what_the_hell_does_it_mean_to_spinup_a_server/?st=jgd3k0r6&sh=4e9d7c3e

2018-04-24 03:35 UTC, hikimon commented on src/v2/cookbook/serverless-blog.md
> +あなたが Vue.js のウェブサイトを新しく立ち上げたとしましょう。おめでとうございます！いま、あなたは自分のウェブサイトに早くブログを追加したいでしょうが、1つの WordPress のインスタンス（また、さらに言えば DB の動作する CMS）だけをホスティングするためにサーバ全体をスピンアップさせたくはないでしょう。少しの Vue.js のブログ構成要素といくつかのルーティングを追加でき
純粋な疑問なのですが原文の
```
a few Vue.js blog components and some routes
```
は、`a few` と `some` をあえて使い分けてるのですかね？

2018-05-05 13:53 UTC, hikimon commented
@potato4d @re-fort 
大変遅くなりましたが、レビューいただいた内容を反映しました。
- おかしい言い回しを修正
- 指摘修正漏れを反映
お手数おかけいたしますが再度ご確認よろしくお願いいたします！
# 間違って会社のアカウントからコミットしてたことにいまさら気づいてrebaseしようとしたりしていますが、そこは無視してください。。。

2018-05-07 04:21 UTC, re-fort approved these changes

2018-05-07 04:21 UTC, re-fort commented
@hikimon ありがとうございます！
@potato4d OKそうならmergeおねがいします！

2018-05-07 04:31 UTC, potato4d approved these changes

2018-05-07 04:32 UTC, potato4d commented
@re-fort 
よさそうなのでマージします！

@hikimon 
翻訳ありがとうございます！お疲れ様でした。

2018-05-07 04:32 UTC, merged

2018-05-07 04:32 UTC, kazupon commented
@hikimon 
翻訳ありがとうございました！ 🎉

2018-05-07 04:33 UTC, hikimon commented
ご対応ありがとうございます！
大変遅くなってしまい申し訳ありませんでした。。。！