[Components In-Depth]: Custom Eventsの翻訳 #920
vuejs/jp.vuejs.org pull request #935
Opened 2018-04-24 14:45 UTC by moksahero

2018-04-24 15:54 UTC, re-fort commented on src/v2/guide/components-custom-events.md
> +コンポーネントや props とは違い、イベント名の大文字と小文字は自動的に変換されません。その代わり放出されるイベント名とイベントリスナ名は全く同じにする必要があります。例えばキャメルケース(camelCase)のイベント名でイベントを発火した場合:
`props`はプロパティに統一させていただきたく:pray:

2018-04-24 15:59 UTC, re-fort commented on src/v2/guide/components-custom-events.md
> +コンポーネントや props とは違い、イベント名は Javascript 内で変数やプロパティ名として扱われることはないので、キャメルケース(camelCase)やパスカルケース(PascalCase)を使う理由はありません。さらに DOM テンプレート内の `v-on` イベントリスナは自動的に小文字に変換されます (HTML が大文字と小文字を判別しないため)。このため `v-on:myE
s/Javascript/JavaScript

2018-04-24 15:59 UTC, re-fort commented on src/v2/guide/components-custom-events.md
> +デフォルトではコンポーネントにある `v-model` は `value` を prop として、`input` をイベントして使いますが、チェックボックスやラジオボタンなどのインプットタイプは `value` 属性を[別の目的](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Value)で使う事
MDNの日本語訳があるので、そちらにリンクお願いします
https://developer.mozilla.org/ja/docs/Web/HTML/Element/input/checkbox#Value

2018-04-24 16:07 UTC, re-fort commented on src/v2/guide/components-custom-events.md
> +コンポーネントの元要素にあるネイティブイベントを購読したい場合もあるかもしれません。こういった場合は `.native` 修飾子を `v-on` に付けてください。
s/元/ルート
で大丈夫です！

2018-04-24 16:19 UTC, re-fort commented on src/v2/guide/components-custom-events.md
> +`$listeners` プロパティを使うことで、コンポーネントの全てのイベントリスナを `v-on="$listeners"` を使って特定の子要素に送ることができます、`<input>` の様な要素の場合は `v-model` を使ったほうがいいでしょう。以下の `inputListeners` の様に新しい computed property を作った方が便利なことも多いです。
`v-model` を使って動作させたいでしょう

2018-04-24 16:20 UTC, re-fort commented on src/v2/guide/components-custom-events.md
> -Using the `$listeners` property, you can forward all event listeners on the component to a specific child element with `v-on="$listeners"`. For elements like `<input>`, that you also want to work wit
s/computed property/算出プロパティ
でおねがいします！

2018-04-24 16:22 UTC, re-fort commented on src/v2/guide/components-custom-events.md
> +`<base-input>` コンポーネントが **完全に透明なラッパ** として扱えるようになったため、普通の `<input>` 要素と全く同じように使うことができるようになりました。全ての同じ要素とリスナが動作します。
s/透明な/透過的な

2018-04-24 16:25 UTC, re-fort commented on src/v2/guide/components-custom-events.md
> +"two-way バインディング"が prop に対して必要な場合もあります。変更ポイントの元が子コンポーネントと親コンポーネントに対して明確にならない状態で子コンポーネントが親コンポーネントを変更してしまうことがあるため、残念ながら本当の two-way バインディングを行うとメンテナンスで問題が発生します。
s/two-way バインディング/双方向バインディング

2018-04-24 16:31 UTC, re-fort commented on src/v2/guide/components-custom-events.md
> -In some cases, we may need "two-way binding" for a prop. Unfortunately, true two-way binding can create maintenance issues, because child components can mutate the parent without the source of that m
残念ながら、本当の双方向バインディングはメンテナンスの問題を引き起こす可能性があります。子コンポーネントは親でも子でもその変更元が明らかでなくても親を変更させることができるからです。

2018-04-24 16:33 UTC, re-fort commented on src/v2/guide/components-custom-events.md
> +このため代わりに `update:my-prop-name` というパターンでイベントを発火させる事をお薦めします。例えば `title` というコンポーネントがあった場合に新しい値を割り当てる事ができます
例えば `title` というプロパティを持つ仮のコンポーネントがあった場合、意図的に新しい値を割り当てる事ができます

2018-04-24 16:34 UTC, re-fort commented on src/v2/guide/components-custom-events.md
> +こうする事で親がこのイベントに購読できるようになり、ローカルデータプロパティを更新します。この様な事をした場合例えば：
s/イベントに/イベントを

2018-04-24 16:35 UTC, re-fort commented on src/v2/guide/components-custom-events.md
> -Then the parent can listen to that event and update a local data property, if it wants to. For example:
こうする事で、必要であれば、親がこのイベントを購読し、ローカルデータプロパティを更新することができます。例えば:

2018-04-24 16:38 UTC, re-fort requested changes
早速ありがとうございます！
レビューしました:eyes:

2018-04-24 20:57 UTC, moksahero commented on src/v2/guide/components-custom-events.md
> +コンポーネントや props とは違い、イベント名の大文字と小文字は自動的に変換されません。その代わり放出されるイベント名とイベントリスナ名は全く同じにする必要があります。例えばキャメルケース(camelCase)のイベント名でイベントを発火した場合:
prop もプロパティですか？

2018-04-24 21:07 UTC, moksahero commented
イベントの
emitted -> 発火
で統一ですか？
他はそうなっていたので

2018-04-24 21:13 UTC, moksahero commented on src/v2/guide/components-custom-events.md
> -Then the parent can listen to that event and update a local data property, if it wants to. For example:
no-mix-dearu-desumasu: 本文: "である"調 と "ですます"調 が混在
=> "であれば、" がである調
Total:
である  : 1
ですます: 2

これでtextlintひっかかりますね。「である。」だけ感知して「である」は感知しないようにしたほうがいいのかもしれません

2018-04-26 15:39 UTC, re-fort commented
@moksahero emitはいまのところ訳が統一されていないですねー
発火はどちらかというとfireなイメージなので、自分が訳してる部分だと送出とかにしています

2018-04-26 15:47 UTC, re-fort commented on src/v2/guide/components-custom-events.md
> +<p class="tip"><code>v-bind.sync</code> を<code>v-bind.sync="{ title: doc.title }"</code> などの様に文字列オブジェクトと一緒に使う場合、ここういった複雑な表現をパースする際に様々なケースが考えられるのでうまく動作しません。</p>
s/ここういった/こういった

2018-04-26 15:48 UTC, re-fort commented
@moksahero 1点だけtypoありました
そのあと、取り込まさせていただこうかと！

2018-04-26 15:49 UTC, kazupon commented
@re-fort @moksahero /cc @potato4d 
`fire`の他に`render`とかもそうですが、頻出するような単語の訳は、長音訳例外リストのように、どこかのタイミングで辞書にしておいてもいいかもしれませんね。

https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#長音訳例外リスト

2018-04-27 00:57 UTC, moksahero commented on src/v2/guide/components-custom-events.md
> +<p class="tip"><code>v-bind.sync</code> を<code>v-bind.sync="{ title: doc.title }"</code> などの様に文字列オブジェクトと一緒に使う場合、ここういった複雑な表現をパースする際に様々なケースが考えられるのでうまく動作しません。</p>
修正しました！

2018-04-29 03:25 UTC, re-fort approved these changes
@moksahero 素早い対応ありがとうございました:tada:
取り込まさせていただきます！

2018-04-29 03:25 UTC, merged

2018-04-29 04:33 UTC, kazupon commented
@moksahero 翻訳ありがとうございました！ 🎉