[Components In-Depth]: Dynamic & Async Componentsの翻訳
vuejs/jp.vuejs.org pull request #936
Opened 2018-04-25 03:19 UTC by ryota-yamamoto

#922

レビューお願いします🙏

2018-04-25 17:22 UTC, resessh commented on src/v2/guide/components-dynamic-async.md
> +動的コンポーネントの再生成は通常は便利な挙動です。しかし、このケースでは最初に作成されたタブコンポーネントのインスタンスがキャッシュされるのが好ましいでしょう。この解決策として、動的コンポーネントを `<keep-alive>` 要素でラップすることができます。
末尾 `:` が抜けてる

2018-04-26 15:52 UTC, re-fort commented on src/v2/guide/components-dynamic-async.md
> +post を選択し、 _Archive_ タブに切り替えてから _Posts_ に戻ると、選択していた post は表示されなくなります。 これは、新しいタブに切り替えるたびに、Vue が `currentTabComponent` の新しいインスタンスを作成するからです。
このpostは訳してよいとおもわれます！

2018-04-26 16:00 UTC, re-fort commented on src/v2/guide/components-dynamic-async.md
> +[ローカル登録](components.html#Local-Registration) を使っている場合、, `Promise` を返す関数を直接与えることもできます:
,が余計です

2018-04-26 16:05 UTC, re-fort requested changes
レビューしました:eyes:
確認おねがいします！

2018-04-26 16:14 UTC, ryota-yamamoto commented
@re-fort レビューありがとうございます！
PTALでございます 🙇

2018-04-29 03:30 UTC, re-fort approved these changes
@ryota-yamamoto 翻訳ありがとうございました:tada:

2018-04-29 03:30 UTC, merged

2018-04-29 04:33 UTC, kazupon commented
@ryota-yamamoto 翻訳ありがとうございました！ 🎉