Translate introduction
vuejs/jp.vuejs.org pull request #937
Opened 2018-04-25 03:31 UTC by nicedchy

レビューお願いします 🙇 
気になっている訳にコメントしています

2018-04-25 03:51 UTC, nicedchy commented on src/v2/cookbook/index.md
> +このセクションは、回避に関する上記のセクションを使用したとき必須になります。驚いていないという特定の状況下で人々はアンチパターンを伝えるので、別の方法を探ることは重要です。探り続けることで、ウェブ多岐にわたりたくさんの人が異なったコードベースと異なる目標を解決していると思えます。アプリケーションは大規模または小規模ですか？　Vue を既存のプロジェクトに統合していますか？または新しく構築していま
`web is a big tent` のニュアンスが少し解釈に困ったので、 `ウェブは多岐にわたりたくさんの〜` としましたが何か良い訳し方ありますか？

2018-04-25 03:52 UTC, nicedchy commented on src/v2/cookbook/index.md
> +このセクションは、回避に関する上記のセクションを使用したとき必須になります。驚いていないという特定の状況下で人々はアンチパターンを伝えるので、別の方法を探ることは重要です。探り続けることで、ウェブ多岐にわたりたくさんの人が異なったコードベースと異なる目標を解決していると思えます。アプリケーションは大規模または小規模ですか？　Vue を既存のプロジェクトに統合していますか？または新しく構築していま
typo はニュアンスのレビュー頂き次第修正

2018-04-25 03:53 UTC, nicedchy commented on src/v2/cookbook/index.md
> +このドキュメンテーションに貢献するためにはたくさんの時間が必要です。もしあなたが私たちのドキュメントにプルリクエストを送っていただけたら、感謝します。
`you do so with our gratitude.` のニュアンス良い日本語のフレーズがでてきませんでした
何か適当なものがあればご教示いただけるとうれしいです 🙏

2018-04-26 16:17 UTC, re-fort commented on src/v2/cookbook/index.md
> +このセクションは、回避に関する上記のセクションを使用したとき必須になります。驚いていないという特定の状況下で人々はアンチパターンを伝えるので、別の方法を探ることは重要です。探り続けることで、ウェブ多岐にわたりたくさんの人が異なったコードベースと異なる目標を解決していると思えます。アプリケーションは大規模または小規模ですか？　Vue を既存のプロジェクトに統合していますか？または新しく構築していま
そうするときには、ウェブは大きな集合体だということであり、多くの人々が異なったコードベースを持ち、異なった目標を解決しようとしていることを考慮してください。

2018-04-26 16:18 UTC, re-fort commented on src/v2/cookbook/index.md
> +このドキュメンテーションに貢献するためにはたくさんの時間が必要です。もしあなたが私たちのドキュメントにプルリクエストを送っていただけたら、感謝します。
このままでOKです！

2018-04-26 16:19 UTC, re-fort commented
@nicedchy 他の箇所についてはWIPがとれたらみます

2018-04-27 01:14 UTC, nicedchy commented
@re-fort @potato4d 
WIP外しました。
全体のレビューお願いします

2018-04-29 03:42 UTC, re-fort commented on src/v2/cookbook/index.md
> +* **JavaScript の指導**: ガイドでは、少なくとも ES5 JavaScript に精通している必要があります。 例えば、  `Array.prototype.filter` がリストをフィルタする computed プロパティでどのように動作するかは説明しません。 しかし、クックブックにおいては、より良い Vue アプリケーションを構築するためにどのように私たちの手助けをしてく
computed -> 算出でお願いします！

2018-04-29 03:45 UTC, re-fort commented on src/v2/cookbook/index.md
> +* **エコシステムを学習する**: 高度な機能はについては、エコシステムの知識を前提にしています。 例えば、 Webpack で単一ファイルコンポーネントを使用する場合、 Webpack config の Vue 以外の部分の設定については説明しません。 クックブックでは、これらのエコシステムやライブラリ群をより深く学習する余裕があります。 - 少なくとも、 Vue 開発者にとって一般的な有用
s/高度な機能は/高度な機能

2018-04-29 03:46 UTC, re-fort commented on src/v2/cookbook/index.md
> -* **Greater Depth**: To avoid making the guide too long, we try to include only the simplest possible examples to help you understand each feature. Then we move on. In the cookbook, we can include mo
ここでのspaceはそのまま場所でOKです！

2018-04-29 03:46 UTC, re-fort commented on src/v2/cookbook/index.md
> -* **Greater Depth**: To avoid making the guide too long, we try to include only the simplest possible examples to help you understand each feature. Then we move on. In the cookbook, we can include mo
s/一般的な/一般的に

2018-04-29 03:50 UTC, re-fort commented on src/v2/cookbook/index.md
> +### 基本の例
基本例でお願いします！

2018-04-29 03:53 UTC, re-fort commented on src/v2/cookbook/index.md
> +1. 例を見ているうちに、共通の質問を呼び出してください。 (ブロッククォートはこれに最適です)
例を見ながら、持つかもしれない共通の質問について取り扱ってください。

2018-04-29 03:57 UTC, re-fort commented on src/v2/cookbook/index.md
> +もし後者を選択した場合、それはどんなものか、またどのように動作するか話し合う必要があります。
s/話し合う/についてしっかりと話す

2018-04-29 03:58 UTC, re-fort commented on src/v2/cookbook/index.md
> +どこに適用するのか、なぜそれがうまくいくのかというパターンについて書くときにとても役立ちます。自分でやるかまたは、人々にここの読書資料を見せてコードを実行してください。
意訳になっちゃいますが、参考資料のほうが伝わりそうです

2018-04-29 04:01 UTC, re-fort commented on src/v2/cookbook/index.md
> +このセクションは必須ではありませんが、強くお勧めします。 それは状態の変化に基づいてクラスを切り替えるなど非常にシンプルなものを書くには向いておらず、 mixins のようなさらに高度なパターンでは意味を成します。 開発に関するほとんどの質問に対しての答えは ["頼りになる!"](https://codepen.io/rachsmith/pen/YweZbG) でした。 このセクションでは以下の
s/"頼りになる！"でした/"時と場合による！"です

2018-04-29 04:02 UTC, re-fort commented on src/v2/cookbook/index.md
> -### When To Avoid This Pattern
`このセクションではそれを受け入れます`

2018-04-29 04:06 UTC, re-fort commented on src/v2/cookbook/index.md
> -### When To Avoid This Pattern
ここでは、パターンが有用なとき、それを避けるべきとき、また他のものがなにか意味をなすときなどについて、隠すことなく見ていきます。

2018-04-29 04:07 UTC, re-fort commented on src/v2/cookbook/index.md
> +このセクションは、回避に関する上記のセクションを使用したとき必須になります。驚いていないという特定の状況下で人々はアンチパターンを伝えるので、別の方法を探ることは重要です。そうするときには、ウェブは大きな集合体だということや、多くの人々が異なったコードベースを持ち、異なった目標を解決しようとしていることを考慮してください。アプリケーションは大規模または小規模ですか？　Vue を既存のプロジェクト
s/使用/提供

2018-04-29 04:15 UTC, re-fort requested changes
@nicedchy レビューしました！
すでに大型連休に入られている場合、明けてからの対応で問題ありません😊

2018-04-30 05:14 UTC, nicedchy commented
@re-fort 
指摘していただいた箇所を取り込み修正しました 🙏 
再レビューお願いします 🙇

2018-05-07 04:30 UTC, re-fort approved these changes
@nicedchy ありがとうございます:tada:

2018-05-07 04:30 UTC, merged

2018-05-07 04:33 UTC, kazupon commented
@nicedchy 
翻訳ありがとうございました！ 🎉