[Cookbook]: Debugging in VS Code and Chromeの翻訳
vuejs/jp.vuejs.org pull request #938
Opened 2018-04-25 13:48 UTC by c-su

お待たせしました。翻訳完了したのでレビューお願いいたしますm(_ _)m

close #846

2018-04-26 16:24 UTC, re-fort commented on src/v2/cookbook/debugging-in-vscode.md
> +[vue-cli](https://github.com/vuejs/vue-cli) 使ってプロジェクトをインストールして作成します。インストールの手順はプロジェクトの readme に記載されています。新しく作成したアプリケーションディレクトリに移動し、VS Code を開いてください。
s/使って/を使って

2018-04-26 16:24 UTC, re-fort commented on src/v2/cookbook/debugging-in-vscode.md
> +VS Code から Vue コンポーネントをデバックする前に、あなたはソースマップを構築するために生成された Webpack のコンフィグを更新する必要があります。デバッガには圧縮ファイル内のコードを元のファイル内の位置にマップするための方法があります。これにより、Webpack によってアセットが最適化された後でもアプリケーションをデバックすることができます。
`あなたは`は抜いてしまってよいです

2018-04-26 16:32 UTC, re-fort commented on src/v2/cookbook/debugging-in-vscode.md
> +複雑さが変化する、他のデバッグの方法もあります。最も人気がありシンプルなのは、優れた [vue-devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd) を使用することです。devtools を使用する利点の 1 つは、データプロパティをライブ編集でき、
他にもデバッグの方法がありますが、複雑さは異なります。

2018-04-26 16:33 UTC, re-fort commented on src/v2/cookbook/debugging-in-vscode.md
> -There are other methods of debugging, varying in complexity. The most popular and simple of which is to use the excellent [vue-devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdog
s/反映反映/反映

2018-04-26 16:34 UTC, re-fort commented on src/v2/cookbook/debugging-in-vscode.md
> -There are other methods of debugging, varying in complexity. The most popular and simple of which is to use the excellent [vue-devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdog
s/デバッグデバッグ/デバッグ

2018-04-26 16:36 UTC, re-fort commented on src/v2/cookbook/debugging-in-vscode.md
> +* より素早いデバッグのためにアプリケーションの状態の特定部分に同意し、
特定部分を購読します。

2018-04-26 16:40 UTC, re-fort commented on src/v2/cookbook/debugging-in-vscode.md
> +### 単純なデバッグステイトメント
ステートメントでおねがいします！

2018-04-26 16:40 UTC, re-fort commented on src/v2/cookbook/debugging-in-vscode.md
> +上記の例は素晴らしいワークフローを持っています。しかしながら、[native debugger statement](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/debugger) をあなたのコード内に直接使用できる代替オプションがあります。この方法を用いることを選択する場合、完了した時にその
s/槊杖/削除

2018-04-26 16:41 UTC, re-fort commented on src/v2/cookbook/debugging-in-vscode.md
> +このレシピは、[Kenneth Auchenberg](https://twitter.com/auchenberg) の寄稿に基づいています。[ここから利用可能](https://github.com/Microsoft/VSCode-recipes/tree/master/vuejs-cli).
最後に`です。`とつけていただけると！

2018-04-26 16:42 UTC, re-fort requested changes
レビューしました:eyes:
確認おねがいします！

2018-04-28 00:14 UTC, c-su commented
@re-fort 
修正しましたー！ご確認お願いいたしますｍｍ

2018-04-29 04:17 UTC, re-fort approved these changes
@c-su ありがとうございました:tada:

2018-04-29 04:17 UTC, merged

2018-04-29 04:32 UTC, kazupon commented
@c-su 翻訳ありがとうございました！ 🎉