[Components In-Depth]: Component Registrationの翻訳
vuejs/jp.vuejs.org pull request #939
Opened 2018-04-25 16:24 UTC by RyoNkmr

closes #918 

よろしくおねがいします！

2018-04-29 04:23 UTC, re-fort commented on src/v2/guide/components-registration.md
> +> このページは[コンポーネントの基本](components.html)を読んでいることを前提としています。コンポーネントになじみがない方は、まずそちらから読んでください。
`このページは [コンポーネントの基本](components.html) を読まれていることが前提になっています。コンポーネントを扱った事のない場合はこちらのページを先に読んでください。`
他のページに合わせて、上記にしていただけると！

2018-04-29 04:34 UTC, re-fort commented on src/v2/guide/components-registration.md
> +もしくは、Babel と Webpack ようなものを用いて ES2015 モジュールを利用しているならば、このようになるでしょう:
s/ような/のような

2018-04-29 04:38 UTC, re-fort commented on src/v2/guide/components-registration.md
> +**(`new Vue` を使って)ルート Vue インスタンスの作成するより前に、グローバル登録を行う必要があることを** 覚えておいてください。[この例は](https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/src/components/_globals.js)実際のプロジェクトの文脈における、このパタ
s/インスタンスの/インスタンスを

2018-04-29 04:39 UTC, re-fort requested changes
@RyoNkmr レビューしました:eyes:

2018-05-01 01:40 UTC, RyoNkmr commented
@re-fort 
修正しましたー！ご確認おねがいします 🙏

2018-05-07 04:33 UTC, re-fort approved these changes
@RyoNkmr ありがとうございました:tada:

2018-05-07 04:33 UTC, merged

2018-05-07 04:34 UTC, kazupon commented
@RyoNkmr 
翻訳ありがとうございました！ 🎉