Remove space
vuejs/jp.vuejs.org pull request #979
Opened 2018-05-08 12:28 UTC by miyako-ep

Remove and replace 2byte-space.

2018-05-08 12:46 UTC, kazupon approved these changes

2018-05-08 12:47 UTC, kazupon requested changes
PRありがとうございます！ 🙏 
CIでエラーがでていますので、対応お願いできますか？

2018-05-15 09:17 UTC, potato4d approved these changes

2018-05-15 09:18 UTC, miyako-ep commented
OMGです。
遅くなりましたが修正してみました。
いかがでしょうか。

2018-05-15 09:20 UTC, kazupon approved these changes

2018-05-15 09:20 UTC, merged

2018-05-15 09:21 UTC, kazupon commented
@miyako-ep
ありがとうございました！