Translate avoiding memory leaks
vuejs/jp.vuejs.org pull request #984
Opened 2018-05-11 12:06 UTC by nicedchy

翻訳完了しましたので、レビューお願いします 🙏 
気になっている表現にはコメントを残してます

2018-05-11 12:14 UTC, nicedchy commented on src/v2/cookbook/avoiding-memory-leaks.md
> +Vue では驚くほどかんたんにリアクティブ Javascript アプリケーションが開発できますが、メモリリークについては注意を払う必要があります。これらのメモリリークは Vue 以外の DOM を扱う追加されたサードパーティーライブラリを使用するときよく発生します。アプリケーションでメモリリークが発生していないかテストし、必要に応じてコンポーネントをクリーンアップするための適切な処置を実行して
Javascript を日本語で書くのに違和感があるため、下記どちらかの表現に倒したく悩んでいます。
* `reactive Javascript applications`
* リアクティブジャバスクリプトアプリケーション

2018-05-11 12:16 UTC, nicedchy commented on src/v2/cookbook/avoiding-memory-leaks.md
> +メモリ管理とパフォーマンステストは素早いリリースの興奮でかんたんに無視できますが、小さなメモリフットプリントを維持することは全体のユーザーエクスペリエンスにとって依然として重要です。
`the excitement of shipping quickly` の良い言い回しが思いつきませんでした。

2018-05-12 07:56 UTC, potato4d commented on src/v2/cookbook/avoiding-memory-leaks.md
> +Vue では驚くほどかんたんにリアクティブ Javascript アプリケーションが開発できますが、メモリリークについては注意を払う必要があります。これらのメモリリークは Vue 以外の DOM を扱う追加されたサードパーティーライブラリを使用するときよく発生します。アプリケーションでメモリリークが発生していないかテストし、必要に応じてコンポーネントをクリーンアップするための適切な処置を実行して
今の表現で良い気がしますがどうでしょう？少し崩すなら「リアクティブな JavaScript アプリケーションが」でも良い気がしますね。

2018-05-12 15:47 UTC, kazupon commented on src/v2/cookbook/avoiding-memory-leaks.md
> +Vue では驚くほどかんたんにリアクティブ Javascript アプリケーションが開発できますが、メモリリークについては注意を払う必要があります。これらのメモリリークは Vue 以外の DOM を扱う追加されたサードパーティーライブラリを使用するときよく発生します。アプリケーションでメモリリークが発生していないかテストし、必要に応じてコンポーネントをクリーンアップするための適切な処置を実行して
自分も、`リアクティブな JavaScript アプリケーション` の方が読みやすいかと思います。

2018-05-12 16:04 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
対応お願いします！ 🙏

2018-05-12 16:04 UTC, kazupon commented on src/v2/cookbook/avoiding-memory-leaks.md
> +Vue アプリケーションのメモリーリークは一般的に Vue 自体からは起こらず、むしろ他のライブラリをアプリケーションに組み込む際発生する可能性があります。
`メモリーリーク` ではなく `メモリリーク`ですね！

2018-05-12 16:04 UTC, kazupon commented on src/v2/cookbook/avoiding-memory-leaks.md
> +Vue アプリケーションのメモリーリークは一般的に Vue 自体からは起こらず、むしろ他のライブラリをアプリケーションに組み込む際発生する可能性があります。
他にもあるので、`s/メモリーリーク/メモリリーク/` しておいてください。

2018-05-12 16:04 UTC, kazupon commented on src/v2/cookbook/avoiding-memory-leaks.md
> +次の例のメモリリークは Vue コンポーネント上で [Choices.js](https://github.com/jshjohnson/Choices) ライブラリが原因で引き起こされていて正しくクリーニングされません。それでは、どのようにして Choices.js のフットプリントを取り除くかメモリリークを回避するかを示します。
`クリーニング` は原文の`clearning`を直訳していますが、メモリリーク絡みの技術文書では一般的に`解放`と訳す事が多いでのそちらの意訳にしておきましょう。

2018-05-12 16:04 UTC, kazupon commented on src/v2/cookbook/avoiding-memory-leaks.md
> +メモリ管理とパフォーマンステストは素早いリリースの興奮でかんたんに無視できますが、小さなメモリフットプリントを維持することは全体のユーザーエクスペリエンスにとって依然として重要です。
この部分、直訳するとわかりにくいので少し用語たして、以下のような感じで意訳してもいいと思います。

`アプリケーションを素早くリリースする興奮のため`

2018-05-12 16:04 UTC, kazupon commented on src/v2/cookbook/avoiding-memory-leaks.md
> +ユーザーが使用している可能性があるデバイスの種類と通常のフローを検討します。ユーザーはメモリが制約を受けたラップトップまたはモバイルデバイスを使用していますか？　ユーザーは通常アプリケーション内をたくさん回遊していますか？　これらのいずれかが当てはまる場合、良いメモリ管理方法はユーザーのブラウザをクラッシュさせる最悪のシナリオを回避させるのに役立つはずです。これらのいずれかにも当てはまらない場合
全角スペースが入っているので削除お願いします 🙏

2018-05-12 16:04 UTC, kazupon commented on src/v2/cookbook/avoiding-memory-leaks.md
> +上記の例では、`v-if` ディレクティブを使用してメモリリークを説明しましたが、シングルページアプリケーションのコンポーネントに [vue-router](https://router.vuejs.org/en/) を使用してルーティングする場合、より一般的で現実的なシナリオが発生します。
vue-routerのリンクですが、日本訳先`https://router.vuejs.org/en/`にして、ユーザーフレンドリーにしておきましょう。

2018-05-12 19:01 UTC, nicedchy commented on src/v2/cookbook/avoiding-memory-leaks.md
> +Vue では驚くほどかんたんにリアクティブ Javascript アプリケーションが開発できますが、メモリリークについては注意を払う必要があります。これらのメモリリークは Vue 以外の DOM を扱う追加されたサードパーティーライブラリを使用するときよく発生します。アプリケーションでメモリリークが発生していないかテストし、必要に応じてコンポーネントをクリーンアップするための適切な処置を実行して
ありがとうございます 🙏 
そちらに直します

2018-05-14 02:39 UTC, re-fort commented on src/v2/cookbook/avoiding-memory-leaks.md
> +もしあなたが Vue でアプリケーションを構築しているとき、メモリリークに注意する必要があります。 この Issue はシングルページアプリケーション( SPAs )を設計する際には特に重要で、SPA を使っているときユーザはブラウザをリフレッシュする必要はなく、JavaScript アプリケーション自身でコンポーネントをクリーンアップすることとガベージコレクションが期待通りに動作することを確認
SPAsのsは取っちゃって大丈夫です

2018-05-14 02:41 UTC, re-fort commented on src/v2/cookbook/avoiding-memory-leaks.md
> +もしあなたが Vue でアプリケーションを構築しているとき、メモリリークに注意する必要があります。 この Issue はシングルページアプリケーション( SPAs )を設計する際には特に重要で、SPA を使っているときユーザはブラウザをリフレッシュする必要はなく、JavaScript アプリケーション自身でコンポーネントをクリーンアップすることとガベージコレクションが期待通りに動作することを確認
コンポーネントをクリーンアップすることとガベージコレクションが期待通りに動作することを確認することはJavaScript アプリケーションの責務です。

2018-05-14 02:42 UTC, re-fort commented on src/v2/cookbook/avoiding-memory-leaks.md
> +Vue アプリケーションのメモリーリークは一般的に Vue 自体からは起こらず、むしろ他のライブラリをアプリケーションに組み込む際発生する可能性があります。
s/組み込む際/組み込む際に/

2018-05-14 02:44 UTC, nicedchy commented on src/v2/cookbook/avoiding-memory-leaks.md
> +もしあなたが Vue でアプリケーションを構築しているとき、メモリリークに注意する必要があります。 この Issue はシングルページアプリケーション( SPAs )を設計する際には特に重要で、SPA を使っているときユーザはブラウザをリフレッシュする必要はなく、JavaScript アプリケーション自身でコンポーネントをクリーンアップすることとガベージコレクションが期待通りに動作することを確認
レビューありがとうございます
こちらも修正します

2018-05-14 02:54 UTC, nicedchy commented
@kazupon @re-fort @potato4d 
レビューしていただいたものを取り込みました 🙏 
再度レビューお願いします 🙇

2018-05-14 02:58 UTC, re-fort commented
@nicedchy 原文ではJavascriptとなっている箇所が2箇所ありますね！
細かいtypoですが、ぜひこの機会に本家にPR送ってみてはいかがでしょう？

2018-05-14 03:00 UTC, nicedchy commented
@re-fort 
たしかに！ありがとうございます
tryしてみます 🙏

2018-05-15 07:26 UTC, potato4d commented
@kazupon 👆 どうでしょう

2018-05-15 07:55 UTC, kazupon approved these changes

2018-05-15 09:07 UTC, merged

2018-05-15 09:07 UTC, kazupon commented
@nicedchy
翻訳ありがとうございました！ 🎉